### ISSUE TITLE
Document dagger auto-completion

### ISSUE THREAD

**Issue by samalba** [dagger/dagger#1159]
Thanks to viper, dagger supports shell auto-completion natively:

e.g.: `dagger completion zsh`

We should document it as it's a very low hanging fruit to improve the UX.

**Comment by dolanor** [comment]
I've dug in this topic a little bit.
According to [this](/usr/share/bash-completion/completions/) (and, thus, the FAQ), on linux, you should put it in: `/usr/share/bash-completion/completions/`, it will lazily load the completion on a case by case (if you put it in `/etc`, it will load them all.)

Apart from that, the completion we have only works for `do`, `help`, `version` and `project`. It is quite limited.
We need to add support to generate completion for `do` actions if we want it to be useful. I don't know how to do that, but I'm pretty sure cobra can handle that.
I guess we won't be able to make it for all actions/subactions, because some might not be evaluated at this point.

So first step would be to make sure it is packaged with goreleaser.
Second step would be to make it more useful by including actions completion.

**Comment by dolanor** [comment]
The homebrew script is dealing with the completions all right.

The `install.sh` we use for linux setup and mac os (no homebrew), doesn't deal with it. Where is that script located/generated?
It seems goreleaser doesn't have some autocompletion script setup routine.

Same for `install.ps1` for windows.
[Scoop script for Dagger](https://github.com/ScoopInstaller/Main/blob/master/bucket/dagger.json)
[Chocolatey script for Dagger](https://github.com/piraces/chocolatey-packages/tree/main/automatic/dagger)
I guess we should add the powershell completion on those package scripts.

**Comment by dolanor** [comment]
On windows, the way to have a permanent completion script is to store it here: `C:\Users\[User]\Documents\WindowsPowerShell\profile.ps1`

https://stackoverflow.com/a/37715242/1286423

I lack the knowledge to do it correctly on windows, but I'm gonna handle the `install.sh` used by linux and mac OS.
