### ISSUE TITLE
Exec: inject stdin, capture stdout and stderr

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#1620]
## Overview

It would be useful to allow injecting data into a command's standard input, and capture its standard output and error streams.
Unlike an earlier proposal, data would be buffered and not streamed.

Proposed design:

```
// dagger.io/dagger/engine
package engine

#Exec: {
  stdin?: string
  stdout?: string
  stdout?: string
  ...
}
```

```
// universe.dagger.io/docker
package docker

#Run: {
  stdin?: string
  stdout?: string
  stdout?: string
  ...
}
```

**Comment by sipsma** [comment]
I am curious what the specific use cases for this are if they can be shared. In general, stdio processing is something users might default to because it's a very generic mechanism, but I do want to make sure there aren't better ways to solve their problems.

---

Either way, support for async execs (`core.#Start` and `core.#Stop`) has just been added, and while I didn't include stdin/out/err support there, it uses the `NewContainer` API mentioned above, so we can support it quite easily if needed. I would caution that we should be careful how we provide this to users. The async execs are meant for non-deterministic "sidecar" services like a test DB, so I don't want users to try using the output of one of them to feed into cacheable `core.Exec` tasks, which can create non-determinism.

If we want to support these for normal `core.#Exec`, @helderco's suggestion seems like it should work. A few notes:
1. We can just bind-mount the wrapper program and stdin.log inside the container instead of copying
2. We can also write the stdout/err files to a separate mount, which can be retrieved after the exec (using the `GetMount` API, which I'm not sure we have used yet in Dagger).

---

In general, I can't think of any reason why we couldn't support at least the stdin part of this upstream, so then we could just provide the stdin buffer to use for an ExecOp as part of the LLB. The concern in general is making sure that we don't introduce a lot of non-determinism and/or parameters that can't be cached, but providing a stdin buffer is easily cached as part of the ExecOp's definition.

Upstream support for stdout/err is a little trickier because it's not completely obvious what the interface would be, but I can't imagine any technical reason why we couldn't have Buildkit just optionally tee the stdout/err to a file on a separate cache mount, which would create the same end effect as the stdio tee program. This should fit into the cache model well as far as I can tell. It's probably more a matter of convincing upstream to take on this complication when there is a mostly viable approach here.

**Comment by shykes** [comment]
> I am curious what the specific use cases for this are if they can be shared. In general, stdio processing is something users might default to because it's a very generic mechanism, but I do want to make sure there aren't better ways to solve their problems.

It's pretty common, when developing a new package, to find yourself wanting to expose the output of a command-line tool directly as an output field in your CUE definition. Since there is no API to do that, you have to 1) wrap the command in a shell script which redirects the output to a file 2) export the file 3) reference the contents of the exported file in your CUE field.

At best, it's verbose and adds friction ("what filename am I supposed to use? Do filenames have a meaning? Am I doing this right?"). At worst, it can add additional headaches, for example if you previously executed the command directly, and now are forced to add the indirection layer of the shell script.

Beyond that, there's a more general argument that, well - if a shell script can do it, and `cue cmd` can do it (they have a CUE API for this), then why couldn't I do it in Dagger? This one is less about an urgent need, and more about giving our developers more creative freedom to build fun and powerful things with Dagger.
