### ISSUE TITLE
Document running Dagger on Tekton

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#1655]
One of Dagger's flagship features is the ability to run on almost any CI environment. This includes [Tekton](https://tekton.dev), a popular option in the Kubernetes community. There should be a documentation page explaining how to run Dagger on Tekton, similar to the page explaining how to run it on Github Actions.

**Comment by mgreau** [comment]
>  So I don't understand why accessing fastly is a blocker for you, sorry.

No problem, not a blocker. It was more related to creating a Fastly account tied to a company vs an easier way for any developers to get access to the service.
I figured it out and will open a PR soon.

**Comment by mgreau** [comment]
I opened https://github.com/dagger/dagger/pull/2097 as a first example.

There are a few improvements we could do to in the near future to make it better (less `yaml` 😄 )
- use a dagger multi-arch container image instead of installing dagger
- create a Dagger Tekton Task and [publish it to Tekton Hub](https://hub.tekton.dev/)
- have an example fully based on Buildkit to build a container image to remove the dind sidecar

I will keep you posted when I have time to work on it.

**Comment by TomChv** [comment]
> use a dagger multi-arch container image instead of installing dagger

Related to #1371
