### ISSUE TITLE
Remove `llb.Copy` and use `llb.Local` directly

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#1868]
Whenever we need a `llb.Local` we wrap it in a `llb.Copy` because of a caching issue:

```go
	// FIXME: Remove the `Copy` and use `Local` directly.
	//
	// Copy'ing is a costly operation which should be unnecessary.
	// However, using llb.Local directly breaks caching sometimes for unknown reasons.
	st := llb.Scratch().File(
		llb.Copy(
			llb.Local(
				path,
				opts...,
			),
			"/",
			"/",
		),
		withCustomName(v, "Embed %s [copy]", path),
	)
```
We should find out if this still happens in Europa. Is this reproducible?

**Comment by aluzzardi** [comment]
/cc @sipsma to get your input here

I **believe** we're doing that because we were getting funky results with the cache, but I can't recall the exact condition.

It was something like, even if the content didn't change, buildkit ended up invalidating the cache for subsequent vertices. Adding an intermediary copy fixed the issue.

**Comment by sipsma** [comment]
@aluzzardi Yeah right now the expected behavior of `llb.Local` is that if you mount it with default options to an Exec, that Exec will end up invalidated on subsequent runs. There's a few ways to prevent this that can be more efficient than `Copy` but have some tradeoffs:
1. You can mount the `llb.Local` with `readonly`. Tradeoff being that you can't write to it obviously.
2. You can mount the `llb.Local` with the `llb.ForceNoOutput` option. This allows it to stay read-write, but means you won't be able to get the modified mount after the Exec.
    - However, I don't think we've actually implemented support for getting mounts after ExecOps (i.e. the equivalent of the `GetMount` api in the go LLB client), so this isn't significant to us at this time.
    - The tradeoff here though is that the local dir will need to be synced in full every run (reason explained below)

If we want to improve this there are some options for optimizing it upstream in Buildkit of varying degrees of complexity. Can go into detail if helpful. There's actually a surprising amount of overlap between the problems of importing local dirs and the problems we have with cache mounts, so there's some potential to kill two birds with one stone too.

In terms of short-term next steps, I will take a look at our current `llb.Local` implementation and see if we can selectively enable optimizations like skipping a `Copy` if the local will be mounted read-only. Enabling `ForceNoOutput` on local mounts is more risky IMO because it forces full resyncs of the local dir every time, and explaining all these subtleties and tradeoffs to users is very far from ideal.

---

### Explanation of the behavior (if interested):

The full explanation for all this is a bit convoluted, but I think it comes down to the fact that local refs were really only designed with the Dockerfile use case in mind a long time ago and other optimizations just haven't been implemented yet.

When you use an `llb.Local` state as a read-write Mount in an ExecOp, the underlying cache reference has to be "finalized", which prevents any changes to it going forward. This is because a snapshot layer now exists on top of it and changing it directly could thus cause corruption.

After that, if you do another build that uses the same local dir, Buildkit's logic is a bit simplistic. It just sees that the cache ref from the last run has been finalized and gives up trying to use it; instead it just starts fresh and syncs the entire local dir into a new cache ref ([here](https://github.com/sipsma/buildkit/blob/2683fbb986737fa744e7a9b00773347dd3d80e83/source/local/local.go#L141)). This is why an `llb.Local` mounted as read-write forces full resyncs every run.

When the local ref is instead mounted as read-only, that doesn't force it to be finalized. Buildkit can re-use it and just sync in any changes from the local dir rather than a forcing a full resync.

The reason that `llb.ForceNoOutput` allows the ExecOp using the mount to not be invalidated is because it enables the use of content-based hashing ([here](https://github.com/sipsma/buildkit/blob/2683fbb986737fa744e7a9b00773347dd3d80e83/solver/llbsolver/ops/exec.go#L221)). This is a whole other rabbit hole I won't go down. Use of read-only mounts enables use of content-based hashing though too, so it also has the more optimal behavior here.

The reason that Copy avoids all of this is that it doesn't require finalizing the source of the copy and it also always uses content based hashing, so it has all the benefits described above but at the cost of copying data on disk.

**Comment by sipsma** [comment]
> Given that and your explanation, I believe we're currently doing the best we can by wrapping llb.Local into a llb.Copy. Do you agree?

Yep I looked quickly and came to the same conclusion. Was planning on taking another look later to see if I missed something but based on this I'll take your word for it :-) 

I'm sure it would be possible to find a way to allow one cue task to inspect details about its inputs in order to selectively optimize, but I don't know if that complication would be worth it at the moment. Copies aren't as efficient as possible but I doubt it's really a bottleneck right now relative to other problems we can address. Happy to be wrong though if we have any data points showing otherwise. Either way this should stay in the backlog, just probably not with a high priority.

**Comment by aluzzardi** [comment]
> Copies aren't as efficient as possible but I doubt it's really a bottleneck right now relative to other problems we can address. 

Totally agree!

>  if we have any data points showing otherwise

I actually commented on this month old issue because I was able to get some fresh data out of OpenTelemetry:

<img width="982" alt="Screen Shot 2022-04-27 at 11 30 38 AM" src="https://user-images.githubusercontent.com/179503/165595283-498ba67d-7a4d-445f-9e2f-fee35541560f.png">

Turns out, `llb.Copy` takes slightly **more** time than `llb.Local` for the overall `client.filesystem.read` call.

**Comment by helderco** [comment]
Closing since the 0.2 CUE is frozen, unless @aluzzardi wants to reopen.
