### ISSUE TITLE
🐞 Dagger: Migrating from the dagger library to core

### ISSUE THREAD

**Issue by lyzhang1999** [dagger/dagger#1990]
### What is the issue?

When I use dagger.#Writefile to write file and mount it with docker.#Run.mounts, it says mounts key is not set, Instead of report dagger.#Writefile package does not exist. Finally with the help of @grouville I realized that some packages were migrated from dagger to core.

I think there should be a more friendly alert, such as a package does not exist, or a way to automatically link dagger to the core package.

Finally, I think this kind of migration should be such from 0.2 to 0.3 migration, because it already affects my usage.

### Log output

![image](https://user-images.githubusercontent.com/8142348/161289501-a7059aee-c361-4db2-b132-b5f3e3d87be3.png)

### Dagger version

0.2.4

### OS version

macOS12.2.1

**Comment by helderco** [comment]
Sorry about that. We have plans moving forward to implement deprecation warnings, but in this case it's hard because it creates a cyclic dependency error, so we decided to take the opportunity of the public launch to make this breaking change.

The fact that there was no error is dependent on upstream: 
- https://github.com/dagger/dagger/issues/493
