### ISSUE TITLE
Move a few definitions from `dagger` to `core`

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#1997]
The following definitions should be moved from `dagger.io/dagger` to `dagger.io/dagger/core`:

- `#ImageConfig` (tightly coupled to our image-related core actions)
- `#HealthCheck` (same)
- `#Ref` (same)
- `#Scratch` (tightly coupled to our fs-related core actions)

I just hit the issue while developing a plan. I used `core.#Copy` and automatically assumed `core.#Scratch`. This is made worse by #1635 because if a definition doesn't exist (in this case `core.#Scratch`) it's not clear at all from the error. So you waste time debugging.

**Comment by helderco** [comment]
I agree with all except `#Scratch`, which is an empty `dagger.#FS` (null id). Ironically it’s precisely the one that tripped you up 😁

**Comment by helderco** [comment]
Moved the image related defs, this is what's left in `dagger`:

- `#Plan`
- `#FS`
- `#Scratch`
- `#Secret`
- `#Socket`
- `#Address`

**Comment by shykes** [comment]
> ### Scratch?
> As for `#Scratch`, do you still feel it should be moved as well? You say it's "tightly coupled to our fs-related core actions", but it's only [referenced once](https://github.com/dagger/dagger/blob/1577ea4adf37f8971ba9a3d1ab2224063371417b/pkg/dagger.io/dagger/core/fs.cue#L121), and the same could be said about `#FS`. I think it's better to think of it as a type (a kind of `#FS`), and keep all types in `dagger`.

My issue with this, basically, is that it's confusing. See https://docs.dagger.io/1222/core-actions-reference#core-actions-related-to-filesystem-trees

In the list is "#Scratch | fs.cue | Create an empty filesystem tree". That entry makes perfect sense in that list. And it does map to an llb call, just like the rest of the list. The only reason we made `#Scratch` a value, instead of a regular action, is a workaround to our own design faults, specifically: we don't support inline actions, so instead of `#Action & { input: #Scratch.output }`, we would have to write `_scratch: #Scratch, #Action: { input: _scratch }`.

> Make address private?

> #Address perhaps should be made private. It's currently used to validate the address for client: network, so the available schemas are tied to that implementation and what's supported there. I know there'll be proxy support as well, but we can decide later if and what to publish as an #Address. Right now, at least, I'd hide it.

Yes, that makes sense to me.

Thanks

**Comment by helderco** [comment]
> it does map to an llb call, just like the rest of the list

You can say the same about all types.

> "#Scratch | fs.cue | Create an empty filesystem tree". That entry makes perfect sense in that list.

You can also say `"#Scratch | types.cue | An empty directory"`, and it would also make sense in the _types_ list. It's where it's actually located and that's its current description. That ref doc is incorrect.

> My issue with this, basically, is that it's confusing.

To me it's the opposite, i.e., more confusing to move, because even if being a type is an implementation detail, that detail is leaked to the API that people are using:

1. It's a type (`$dagger: fs`);
2. Name is conventionally a noun, not a verb;
3. No inputs/outputs like actions, or any other field, so no `#Scratch.output`;

I think we just need a tie breaker 😁 @aluzzardi @jlongtine ?

**Comment by shykes** [comment]
It's fine, we can keep `dagger.#Scratch`. Once we have inline actions I will propose `core.#NewFS` or something like that :)

Thanks for pushing this to the finish line. It's a small detail, but details add up!

**Comment by shykes** [comment]
@helderco would you mind correcting filename in the core action reference?

**Comment by helderco** [comment]
Now that I've slept for a bit I'm having second thoughts 🤣 

`#Scratch` is unique. Technically it's not an action but also not a type. **It's actually a value.**

You can't use it as a type:

```cue
#Ok: {
    input: dagger.#FS
}
#NotOk: {
    input: dagger.#Scratch
}
```

`#Scratch` is to `#FS` like `"Hello world"` is to `string`.

I think it's a bit clearer to move from `types.cue` into `values.cue` (in `dagger.io/dagger`), and update the reference doc accordingly.

But I'm also this close 🤏 to be persuaded to move to core. As you say, it's a shortcut for an inline action. When those become possible it would make sense to adjust the implementation and you wouldn't have to break imports because then it'll make even more sense to move to core actions.

**Comment by helderco** [comment]
I tried adjusting #2208 to move to `values.cue`, but then documenting it forces me to create a new concept of Dagger Values, which can become confusing over other types of values.

Now I'm on board. I'm moving to `core`. 😂

**Comment by shykes** [comment]
Up to you @helderco. I think it boils down to how much work is worth investing now, versus just waiting for inline actions, then introducing a new `core.#NewFS` and deprecating `dagger.#Scratch`. Up to you!

**Comment by helderco** [comment]
> I think it boils down to how much work is worth investing now

Yes, based on that I rather do `core.#NewFS` later. Do you approve https://github.com/dagger/dagger/pull/2208?
