### ISSUE TITLE
🐞 BuildKit job not spawning

### ISSUE THREAD

**Issue by verdverm** [dagger/dagger#2000]
### What is the issue?

BuildKit does not seem to be spawning

### Log output

$ dagger do build -l debug
10:49PM DBG spawning buildkit job    attrs=null localdirs={}  
... forever ...

### Steps to reproduce

Installed from GitHub.tar.gz

tried to run the examples from universe

### Dagger version

0.2.4

### OS version

Debian 10 on ChromeOS | amd64

**Comment by verdverm** [comment]
Problem: I had an old BUILDKIT_HOST value set, but no buildkit running

Solution: unset that variable

Enhancement: use a timeout and that the env var is set to warn the user that Dagger is expecting, but unable to talk to, an existing BuildKit instance

**Comment by sipsma** [comment]
I just debugged an issue w/ a user in discord that ended up in a similar situation where BUILDKIT_HOST was set to an endpoint that couldn't be reached. I'd just add that in addition to a connection timeout (as suggested already) a debug log like `Attempting to connect to Buildkit host at <endpoint>...` before the connection attempt is made would help a lot.

**Comment by sipsma** [comment]
I'm happy to fix this btw, shouldn't be too hard

**Comment by marcosnils** [comment]
> 'd just add that in addition to a connection timeout (as suggested already) a debug log like `Attempting to connect to Buildkit host at <endpoint>...` before the connection attempt is made would help a lot.

that'd be awesome! a contribution to improve this would be awesome!

**Comment by sipsma** [comment]
Turns out there was actually a more fundamental problem happening here involving deadlock in an error case, fixed in #2078 

In terms of whether it's still worth adding timeouts+logs for the connection attempt, it turns out that's actually more complicated than it originally seemed. The Go grpc client will by default not actually wait for the connection attempt to succeed and instead tries to connect asynchronously. This means that setting a timeout and adding a log there is not actually that useful. There's a `WithBlock` grpc option, but I think we'd need to update buildkit in order to use it; it's not an available option right now.

**Comment by shykes** [comment]
Considering that @verdverm solved his original issue, and the related deadlock problem was solved by @sipsma, OK to close this?

**Comment by sipsma** [comment]
> Considering that @verdverm solved his original issue, and the related deadlock problem was solved by @sipsma, OK to close this?

Yeah I think so. I'm going to try making a small upstream change to Buildkit to support a `WithBlock` option, which we can then decide if we want to use here to improve this further, but that is more of a tangent off this issue.
