### ISSUE TITLE
`client: platform:` example produces error unless used by another action

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#2103]
### What is the issue?

In the docs we have this example of how to get the client platform's os and arch:
https://docs.dagger.io/1203/client#platform

But if you flesh this out to make it runnable (package name, imports) and run this example as is, you get an error.

```cue
package main

import (
    "dagger.io/dagger"
    "universe.dagger.io/go"
)

dagger.#Plan & {
    client: _

    actions: build: go.#Build & {
        os:   client.platform.os
        arch: client.platform.arch
        // ...
    }
}
```

```
$ dagger do build --log-format plain
...
4:29PM INF actions.build.container._exec | computing
4:29PM ERR actions.build.container._exec | failed: invalid FS at path "actions.build.container._exec.mounts.source.contents": FS is not set
    duration=0s
4:29PM FTL system | failed to execute plan: task failed: actions.build.container._exec: invalid FS at path "actions.build.container._exec.mounts.source.contents": FS is not set
```

If you take the code and put it with an action that references the `build` action, you'll get the same error by running the `build` action again.

```cue
package main

import (
	"dagger.io/dagger"
	"dagger.io/dagger/core"
	"universe.dagger.io/go"
)

_alpine: core.#Pull & {source: "alpine:3"}

dagger.#Plan & {
	client: _

	actions: {
		build: go.#Build & {
			os:   client.platform.os
			arch: client.platform.arch
		}
		info: core.#Exec & {
			input: _alpine.output
			args: ["echo", "{ \"os\": \"\(build.os)\",  \"arch\": \"\(build.arch)\" }"]
			always: true
		}
	}
}

```

```
$ dagger do build --log-format plain
...
4:30PM INF actions.build.container._exec | computing
4:30PM ERR actions.build.container._exec | failed: invalid FS at path "actions.build.container._exec.mounts.source.contents": FS is not set
    duration=0s
4:30PM FTL system | failed to execute plan: task failed: actions.build.container._exec: invalid FS at path "actions.build.container._exec.mounts.source.contents": FS is not set
```

But if you run the `info` action that uses the `build` action, then it works!

```
$ dagger do info --log-format plain
...
4:31PM INF actions.info | computing
4:31PM INF actions.info | #3 0.059 { "os": "darwin",  "arch": "arm64" }
4:31PM INF actions.info | completed    duration=100ms
...

```

There should be no errors for the `build` action running alone case. 

### Log output

see above

### Steps to reproduce

see above

### Dagger version

0.2.5

### OS version

macOS 12.3.1

**Comment by jpadams** [comment]
Same on Windows 11 Pro

```
PS C:\> dagger do build --log-format plain
...
4:42PM INF actions.build.container._exec | computing
4:42PM ERR actions.build.container._exec | failed: invalid FS at path "actions.build.container._exec.mounts.source.contents": FS is not set
    duration=0s
4:42PM FTL system | failed to execute plan: task failed: actions.build.container._exec: invalid FS at path "actions.build.container._exec.mounts.source.contents": FS is not set
```

```
PS C:\> dagger do info --log-format plain
...
4:42PM INF actions.info | computing
4:42PM INF actions.info | #3 0.176 { "os": "windows",  "arch": "amd64" }
4:42PM INF actions.info | completed    duration=200ms
```

**Comment by helderco** [comment]
I assume this issue is about finding the absense of an error when used as a dependency rather then the example not being a fully workable example. 🙂 If you want to focus on the example itself, I suggest opening another issue asking (in general) for complete examples in the _Core Concepts_ section.

## The problem

I don't see this as a bug really, but I may be wrong. What's happening is that you're referencing values that are already concrete (passthrough), and not triggering the task runner to see the dependency. In other words, the `build` action isn't being run (you can see that it doesn't show in the logs), thereby not triggering an error. It's like you have this:

```cue
dagger.#Plan & {
	client: _
	actions: {
		// not an action
		build: {
			os:   client.platform.os
			arch: client.platform.arch
		}
		info: core.#Exec & {
			input: _alpine.output
			args: ["echo", "{ \"os\": \"\(build.os)\",  \"arch\": \"\(build.arch)\" }"]
			always: true
		}
	}
}
```

By trying to run it directly though, you're telling the runner to explicitly run that action, but it doesn't have all it's inputs defined (souch as source code files), which is why it's failing.

Since you don't require any output from `go.#Build`, I think this is working as designed. We do have plans to add explicit dependencies (#940, #1248, #1598) if you really need to force something to run before an action.

## Task runner

To help you understand a little bit better, the task runner only runs _core actions_. You need to depend on something that "touches" a core action eventually. Let's look at a simple example:

```cue
package main

import (
	"dagger.io/dagger"
	"dagger.io/dagger/core"
)

dagger.#Plan & {
	client: _

	actions: {
		_alpine: core.#Pull & {
			source: "alpine"
		}
		build: #Build & {
			os: client.platform.os
		}
		noRun: core.#Exec & {
			input: _alpine.output
			// passthrough, doesn't end up referencing any field in a core action
			args: ["echo", build.os]
			always: true
		}
		runOutput: core.#Exec & {
			input: _alpine.output
			// needs an output, so it's a clear dependency
			args: ["echo", build.output]
			always: true
		}
		runInput: core.#Exec & {
			input: _alpine.output
			// just to see if referencing an input also works
			args: ["echo", build.op.input]
			always: true
		}
	}
}

// composite action
#Build: {
	os: string

	// core action
	// not _op because of runInput
	op: core.#Nop & {
		// need to reach fields in core action
		// to be seen as a dependency to run
		input: os
	}

	output: op.output
}
```
As you can see, `actions.build` is only run if something references any of its `op` core action's fields.
```console
➜  dagger do noRun
[✔] actions
[✔] client.platform
[✔] actions.noRun

➜  dagger do runOutput
[✔] actions
[✔] client.platform
[✔] actions.build.op
[✔] actions.runOutput

➜  dagger do runInput 
[✔] actions
[✔] client.platform
[✔] actions.build.op
[✔] actions.runInput  
```

## Solution

I think the best solution here is to document in a Knowledge Base article type of thing, about _understanding the task runner_ and _understanding CUE's evaluator_. These are two things that I find surprise people a lot, even me sometimes, although I've come to understand a bit more over time.

By having articles explaining how these work, and listing common pitfalls to avoid, that would help a lot. This is something I've alluded to a bit in https://github.com/dagger/dagger/discussions/2085#discussioncomment-2529147.

If the example helps to understand, it can be used as source for the article, but please, anyone correct me if I'm being incorrect on something. /cc @jlongtine @aluzzardi 🙂

**Comment by jpadams** [comment]
Thanks @helderco. I need to study/digest your content some more (thank you!), but I see that I misunderstood the docs when I first read them as a person new to dagger and CUE.

I took the docs example as "the way" to get the os and arch from the client. I've seen some things that were non-intuitive at first, so I wrongly took it as gospel that I needed to use the exact syntax shown, complete with `go.#Build`. In other words, the bits that were trying to show me how to access the client platform info were hidden in the example (for me), plus the example didn't work on it's own, so it was confusing.

I think this could be fixed in the docs with a complete working example like this that makes it clear that I'm just using fields from the `client.platform` struct:

```
package main

import (
	"dagger.io/dagger"
	"dagger.io/dagger/core"
)

_alpine: core.#Pull & {source: "alpine:3"}

dagger.#Plan & {
	client: platform: {}

	actions: {
		info: core.#Exec & {
			input: _alpine.output
			args: ["echo", "{ \"os\": \"\(client.platform.os)\",  \"arch\": \"\(client.platform.arch)\" }"]
			always: true
		}
	}
}
```

And/or perhaps some sort of highlighting could point out the bits that were important:

<pre><code>
dagger.#Plan & {
    client: _

    actions: build: go.#Build & {
        os:   <b><i>client.platform.os</i></b>
        arch: <b><i>client.platform.arch</i></b>
        // ...
    }
}
</pre></code>

**Comment by helderco** [comment]
Thanks for the feedback 🙂 

Can you please create an issue requesting that documentation examples be fully workable? It’s by design that articles in _Core Concepts_ are kept as simple as possible to help focus on the concepts. If that’s hindering beginners we should change the approach, rather then raise issues as people are trying to run the examples.

**Comment by samalba** [comment]
Seems related to #1784 from what you describe @helderco 

@jpadams Given you now have more experience with the docs and CUE, do you have an opinion here?

**Comment by helderco** [comment]
I think this issue is just asking for every example in the documentation to be fully working (copy/pastable).
