### ISSUE TITLE
Document better actions inputs / outputs

### ISSUE THREAD

**Issue by aluzzardi** [dagger/dagger#2162]
## Document better actions inputs / outputs

Sometimes I find myself jumping between a task definition [1] and it's corresponding source code [2] to understand what some actions are doing in regards to inputs and outputs. The API docs [3] also don't mention this information. 

It'd be nice to have a page a la `terraform` registry [4] with more structured information about the actions and their corresponding inputs / output values
[1]: https://github.com/dagger/dagger/blob/v0.2.4/pkg/dagger.io/dagger/core/fs.cue#L41
[2]: https://github.com/dagger/dagger/blob/main/plan/task/readfile.go#L40-L41
[3]: https://docs.dagger.io/1213/api
[4]: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket

_Originally posted by @marcosnils in https://github.com/dagger/dagger/discussions/2052#discussioncomment-2518338_

**Comment by shykes** [comment]
Yes I agree, I think this is related to `dagger doc` and the need to explore dagger universe.

**Comment by mircubed** [comment]
Closing #2269 since it reflects a similar ask, and adding the content here: 

" Many users have difficulties to understand input and output concept and that lead them to issues they do not really understand.

We should write a page in core concept category to explain how you can link action together through input and output.
We should also explain when use docker.#Build and when not.

And also explain how create dependency between actions that not necessary has input field : link docker.#Push and docker.#Pull for instance." 

[Example](https://discord.com/channels/707636530424053791/966990447065071648)

**Comment by marcosnils** [comment]
Closing since it's not relevant anymore
