### ISSUE TITLE
some characters (especially checkmarks) in dagger output render poorly on windows

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#2189]
![consolas_font](https://user-images.githubusercontent.com/3187222/163303821-5a42758a-b675-48f2-9d1d-c596d5c2d7d3.png)

![cascadia_code_font](https://user-images.githubusercontent.com/3187222/163303837-b49f1ac3-4f9f-43c5-a9ef-4bea66a8498d.png)

![jenkins_windows](https://user-images.githubusercontent.com/3187222/163298556-deb0fbf8-d730-4848-8e10-69f22f73159e.png)

**Comment by grouville** [comment]
This "[]" character is ugly, but I believe it's just because the windows ascii code doesn't translate well on its windows version.

Regarding the Jenkins version, the PR: https://github.com/dagger/dagger/pull/1674/files should have fixed the issue by replacing the stdin and stderr fds by a library that automatically converts the ascii escape sequences to windows compatible ones (which is why you have colors without issues on your Windows computer). It seems that, on Jenkins, it isn't the case. My guess would be that this shell has some specificities making us either not take that into account, or the library

**Comment by jpadams** [comment]
closing for now
