### ISSUE TITLE
✨ Improve log outputs for non-llb generated tasks

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#2224]
### What are you trying to do?

Currently for Dockerfile actions and the tty output, we've "hacked" an improvement to better display error messages here https://github.com/dagger/dagger/pull/2188. However, in order to have a "proper" solution for this, we'd need buildkit to return some metadata on it's SolveStatus here (https://github.com/moby/buildkit/blob/master/client/graph.go#L49) so we can get more contextual information about where events are coming from. After brainstorming this with @sipsma, we though it could be a good idea to open an issue in buildkit to follow-up on this. 

Related: 

https://github.com/dagger/dagger/issues/613
https://github.com/dagger/dagger/issues/2044
https://github.com/dagger/dagger/pull/2306

Observe:

-  https://github.com/moby/buildkit/issues/2826

### Why is this important to you?

To improve log outputs for buildkit actions that are non-llb handled in the Dagger side. For example, frontends natively handled by buildkit

### How are you currently working around this?

https://github.com/dagger/dagger/pull/2188

**Comment by sipsma** [comment]
I just remembered that [I recently added support for marking vertices as being in a "progress group"](https://github.com/moby/buildkit/blob/17b17564a43cc13a3069486f17a38c1a13466251/client/llb/state.go#L602), which ends up more or less just being metadata that gets passed back to the client during solves (I don't know how I forgot this when we talked about it last...). I think this could be a good fit here as we can probably just wrap the `llb.State` returned by the dockerfile frontend with a progress group name, which will result in events from the dockerfile build showing up in the progress stream from Buildkit with that group name [attached here](https://github.com/moby/buildkit/blob/26517e0ade3497f87aad0c1066d90031e0d5a18c/client/graph.go#L18).

The only thing I'm not immediately sure about is whether providing `llb.ProgressGroup` to `State.Marshal` results in it overriding every vertex in the LLB DAG (which is what we'd want here). It might, but it's a bit convoluted because of the way the frontend returns LLB to the client, so we'd just need to test to confirm. If that doesn't work, we may need to make an upstream change, but probably nothing very big at all.

**Comment by marcosnils** [comment]
> If that doesn't work, we may need to make an upstream change, but probably nothing very big at all.

Nice! I'll test this tomorrow. Thx for the pointer, this could definitely be the proper way to proceed here :muscle:

**Comment by marcosnils** [comment]
> The only thing I'm not immediately sure about is whether providing `llb.ProgressGroup` to `State.Marshal` results in it overriding every vertex in the LLB DAG (which is what we'd want here)

Just tested this and it doesn't seem to be the case. Tried wrapping the state here https://github.com/dagger/dagger/blob/main/plan/task/dockerfile.go#L57 using a ProgressGroup constraint and even setting it in the subsequent `Marshal` calls here (https://github.com/dagger/dagger/blob/main/plan/task/dockerfile.go#L63) and here (https://github.com/dagger/dagger/blob/main/plan/task/dockerfile.go#L76) and I'm not getting it back through the `SolveStatus` events.

**Comment by sipsma** [comment]
> Just tested this and it doesn't seem to be the case. 

Sad... I will make some time this week to double check that there's not some existing obscure way to get it to work, and if so open an issue in Buildkit for adding what we need.

**Comment by sipsma** [comment]
I found why this doesn't work. The LLB we get back from frontends is called a DefinitionOp, which is basically what you get when you have already marshalled LLB that you now want to unmarshal and use as a State again. Problem is that DefinitionOp just doesn't support overriding any metadata.

When I add `meta = mergeMetadata(meta, c.Metadata)` below [this line](https://github.com/moby/buildkit/blob/65f494851ae357698c8190bc5853ef1fe51cfe39/client/llb/definition.go#L161) then I can set ProgressGroup successfully when it's provided as a default constraint by Dagger [here](https://github.com/dagger/dagger/blob/fb7bcb48627c15adba8a735c6cfb9809fd601734/solver/solver.go#L145).

I'm double-checking to see whether this was intentional or not. If not I'll fix it upstream. We'll then need to either wait for the next release or pull in the master branch of buildkit (somewhat less painful in this case because it's a buildkit client change, not server).

**Comment by marcosnils** [comment]
:pray: thx for following up on this one. Let's see what Tonis says about this.

**Comment by sipsma** [comment]
https://github.com/dagger/dagger/pull/2306 Addresses most of this issue with some exceptions noted in the PR

**Comment by marcosnils** [comment]
> #2306 Addresses most of this issue with some exceptions noted in the PR

:+1: just updated this issue to :eye: for https://github.com/dagger/dagger/pull/2306 so we can finalize it after buildkit's changes.
