### ISSUE TITLE
Plan breaks when unifying with dagger.#Plan multiple times

### ISSUE THREAD

**Issue by aluzzardi** [dagger/dagger#2263]
If the `dagger.#Plan` definition is merged multiple times, it breaks the plan (I don't have the error handy).

For instance:

- a.cue
```cue
dagger.#Plan & {
  actions: a: ...
}
```

- b.cue
```cue
dagger.#Plan & {
  actions: b: ...
}
```

`dagger do -p ./a.cue` will work, but `dagger do` won't (e.g. loading twice).

I believe @marcosnils hit the same issue in a different way (e.g. `a.cue` and `subdir/b.cue`, running `dagger do` from `subdir` breaks because `#Plan` is unified twice).

Removing `#Plan` from every file except one (e.g. just using `actions: b: ...` rather than `#Plan & { actions: b: ... }`) fixes the problem.

I assume it's because we're doing stuff in `#Plan` that breaks when done multiple times.

/cc @helderco

**Comment by marcosnils** [comment]
> I believe @marcosnils hit the same issue in a different way (e.g. `a.cue` and `subdir/b.cue`, running `dagger do` from `subdir` breaks because `#Plan` is unified twice).

Yep, exactly this behavior. IIRC unification breaks with client filesystem mounts only  IIRC since the CUE evaluator can't resolve to what it should ultimately be.

**Comment by helderco** [comment]
This has come up a few times. I've just recomended to specify the plan with `-p` or keep only one plan in the same dir. Do we want to support unifying multiple plans together? I think that'll be confusing, but also if it's not on purpose and there's unexpected behavior because of that. So we should at least detect this situation and error early.

I first tried this back in january when trying to break a big plan:

- https://github.com/dagger/dagger/issues/1316

**Comment by aluzzardi** [comment]
@helderco Do we know what the root cause is? In theory there shouldn't be an issue unifying `#Plan` multiple times

**Comment by helderco** [comment]
At the time I ruled it down to scoping issues. But I can give it another look.

**Comment by d3rp3tt3** [comment]
@aluzzardi , can we close this one out now?

**Comment by aluzzardi** [comment]
Yep
