### ISSUE TITLE
Simpler Client API

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#2470]
## Problem

The [Client API](https://docs.dagger.io/1203/client) is causing a bad developer experience. Developers often report confusion about what it’s for and how it works. Common reasons for the confusion are:

1. Unfamiliar. Unlike the [core action API](https://docs.dagger.io/1222/core-actions-reference) which works by applying action definitions, the client API works by setting values at a certain path under the `client` key.
2. Inconsistent. Read and writes work very differently. Writes (eg. filesystem write) reference inputs from other values. Reads create a “vacuum” output field which the engine then fills at runtime with the output value.
3. Unintuitive. The runtime behavior of client actions is sometimes surprising and hard to guess. (FIXME: need to dig up specific issues to illustrate). 
4. Complicated. The client API and core action API are actually implemented the same internally: everything is a cueflow task in the end. But that fact is obscured by an abstraction which hides the regular definition-based invocation with the a special case path-based invocation. That abstraction makes the codebase more complicated and makes bugs or user errors more likely.

## Solution

Design a v2 client API that 1) solves these problems and 2) offers compatibility or seamless migration for existing developers, resulting in 3) a better developer experience :)

## Design proposal

FIXME / Coming soon / suggestions welcome :)

**Comment by dolanor** [comment]
I think that already the name is confusing. `client`, but it's actually to interact with the host.

I see it as a gateway to the host, as a way to do IO with the host. Maybe `io` or `Host` could already be a better name? It also makes me think of the Docker build context as well.
On the actual API, I don't have a suggestion except that the FS abstraction is, in fact, confusing and hard to get right. It's the part I struggle the most each time.

As it is, I think it should be responsible for defining everything that would go in or out.
For me, mounts should also be included. Mounts could only be mounted from packages if they are predefined under some `mounts` key in the `io`. The `mount` would only define the source, and possibly its mount type (`ro`, `rw`). The actual mount destination can be up to each action.
I got bitten by an issue where I thought the source code was copied inside an action when it was actually mounted, which made me have wrong assumption on what would happen. Only digging deeper in the package definitions made me understand that it was mounted in the end.

**Comment by shykes** [comment]
> I think that already the name is confusing. `client`, but it's actually to interact with the host.

Which host? The one running `dagger`, the one running `buildkitd`, or the one running containers? Keeping in mind there can multiple buildkit nodes in a cluster, and hopefully one day multiple nodes running each dag.

**Comment by sipsma** [comment]
@jlongtine mentioned today that changing the way `client` filesystem writes work might help us work around some of the cue issues we are currently facing. Seems worth capturing here, but I'll let him explain the details.

---

In general, +100 to this. I think just changing the client stuff to be actions with the same general model as our other `core` actions (i.e. `client.#ReadDir`, `client.#WriteDir`, `client.#ReadEnv`, etc.) would be much more intuitive.

It could also open the door to making `client` be importable like any other package (i.e. `dagger.io/dagger/client`) and usable directly from actions rather than a field under `dagger.#Plan` that has to be "pushed" to actions. I don't know if we want to do that immediately though because it creates a lot of hard problems. For instance:
* On one hand it would be great if a re-usable action could specify client resources that should be used by default (i.e. a github api action could load credentials from `~/.config/gh.hosts.yml` on the client by default).
* On the other hand, I think it would be a strong anti-pattern to allow re-usable actions to hardcode that something ***must*** be read from the client. IMO default might be fine, but not allowing that to be overridden would be bad.
* This is in addition to the profound security implications, especially in the context of hypothetical support for remote actions. As mentioned in the discussion last week, we could come up with trust models, but that's a big project probably.

So if we want to make these improvements quicker and avoid those hard problems for now, maybe we could leave `client` as a field under `dagger.#Plan` and just change the api to be definitions you use under that key?

**Comment by shykes** [comment]
Assigning myself because I think this is important and I don't want to lose track of it. cc @mircubed

**Comment by mircubed** [comment]
@shykes are you currently working on the design or do you need me to re-assign to someone else to focus on?

**Comment by jpadams** [comment]
Case in point:

User intended to invoke `actions.two` through `dagger do two` and was surprised that `actions.one` was triggered by the fact that a `client: filesystem: write:` used `actions.one`'s output.

They figured anything not related to the requested action would not run. In other words, they felt that anything related to `actions.one` would only execute if they asked for `dagger do one`.

https://discord.com/channels/707636530424053791/709803368318632038/1005489427797266516

```
package main

import (
	"dagger.io/dagger"
	"universe.dagger.io/docker"
	"dagger.io/dagger/core"
)

_#def
_#def: dagger.#Plan & {
	client: {
		filesystem: {
			folders: {
				read: {
					contents: dagger.#FS
				}
				write: {
					contents: actions.one.folders.output
				}
			}
		}
	}
	actions: {
		one: {
			build: docker.#Build & {
				steps: [docker.#Pull & {
					source: "alpine"
				}, docker.#Copy & {
					dest:     "/tmp/folders"
					contents: client.filesystem.folders.read.contents
				}, docker.#Run & {
					command: {
						name: "touch"
						args: ["/tmp/folders/test"]
					}
				}]
			}
			folders: core.#Subdir & {
				input: build.output.rootfs
				path:  "/tmp/folders"
			}
		}
		two: {
			build: docker.#Build & {
				steps: [docker.#Pull & {
					source: "alpine"
				}, docker.#Copy & {
					dest:     "/tmp/folders"
					contents: client.filesystem.folders.read.contents
				}]
			}
		}
	}
}
```

**Comment by helderco** [comment]
Commented in #2909
