### ISSUE TITLE
Spike to diagnose issues with documentation search so we can create a fix

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#2557]
## Problem

The [Dagger documentation](https://docs.dagger.io) has broken search. This makes it difficult for developers to find the information they're looking for.

## Solution

Fix the search feature in the Dagger documentation.

**Comment by shykes** [comment]
As suggested by @gerhard this morning. cc @jpadams

**Comment by jpadams** [comment]
https://docusaurus.io/docs/search#using-algolia-docsearch

**Comment by gerhard** [comment]
Current status: https://github.com/dagger/dagger/pull/2348#issuecomment-1167944513

**Comment by mircubed** [comment]
Since the PR was merged, could we close this? @gerhard

**Comment by mircubed** [comment]
@crjm to clarify next steps and close if needed

**Comment by crjm** [comment]
Right now we have a few results that show up as suggestions when using the search input that shouldn't be there or should have a different hierarchy.
For example, when searching "dagger cloud", some pages that shouldn't be rendered appear:

![image](https://user-images.githubusercontent.com/70334844/178363544-6fb3a2a7-d940-417c-90fe-f4b7da9b00ac.png)

**This particular search is addressed in #2764**

---
Another case is "buildkit", as Algolia takes "building" as a synonym.

![image](https://user-images.githubusercontent.com/70334844/178364730-b3634a76-5689-4f20-9194-668c9ee11b0e.png)

---
However, there are searches that show the results perfectly, such as "cache"

![image](https://user-images.githubusercontent.com/70334844/178364242-06139f73-b3a8-443c-ad4d-e5ce27f73b28.png)

---
Because of this, I should see which other searches are broken/not optimized and fix them.

**Comment by slumbering** [comment]
Weird 🤔 ! @crjm I don't get the same result as you... Maybe something as been updated ?



![Image](https://user-images.githubusercontent.com/1186424/178678494-5ad8bc09-5a65-47ce-9cd4-e6ec2d3651a1.png)




![Image](https://user-images.githubusercontent.com/1186424/178678518-893261cf-ac83-44d4-a45f-48b2383a0d87.png)

**Comment by crjm** [comment]
Dagger Cloud search [has been fixed](https://github.com/dagger/dagger/pull/2764).
As for Buildkit search, I don't know what happened, it's working for me too. 
I'll look into it.

**Comment by jpadams** [comment]
@crjm Maybe we can close this issue for now?

We can open another one after new docs are out, if needed.

**Comment by crjm** [comment]
@jpadams SGTM!
