### ISSUE TITLE
Design and execution of guided onboarding web experience

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#2628]
Landing page with type-ahead search/tags-driven navigation of guides, starter templates, universe actions catalog (stretch).

@slumbering @Camille-Elairin @crjm 

related: #2557 #1912 #2472 #2585

**Comment by slumbering** [comment]
Inspiration: 
https://www.apollographql.com/tutorials/

**Comment by crjm** [comment]
Inspiration:
https://marketplace.digitalocean.com/
https://fullstackopen.com/en/about

**Comment by mircubed** [comment]
@crjm and @slumbering working on initial draft

**Comment by crjm** [comment]
I researched a bit more and found about a site that does tear-downs of popular apps and how they onboard new users. [The latest one is with SavvyCal](https://www.useronboard.com/how-savvycal-onboards-new-users/?slide=4) (there are others a bit outdated but we can take some UX ideas from those as well).
What's interesting about the site is that **they consider Google Search to be a part of the onboarding too**.

There's a service called Appcue that focuses on onboarding and they have [good content explaining core concepts](https://www.appcues.com/user-onboarding).
I think we should word what we want to achieve with our users as **"aha" moment**, the moment where they find Dagger is valuable to them.

I'll keep searching for specific elements such as modals, pulsing buttons, tags, etc, that make sense to implement in a documentation, because most of these examples are from the apps themselves.

**Comment by crjm** [comment]
After browsing the docs a bit, I have three observations.

* We are currently using "Next" and "Previous" buttons in the documentation.
We should either exploit this idea or remove them, as the docs order does not seem to follow a certain pattern and may generate confusion in new users. 
For example, the last doc in Getting Started is "Install Dagger" even though the first doc will make you install Dagger already.
![image](https://user-images.githubusercontent.com/70334844/175696030-811e6df7-99c6-4442-b0f6-8fa199c25f5a.png)

* Maybe what we are missing are other resources, like tutorials or how-tos. I think that "Build & run locally...then in CI" is great material for a tutorial, even though it's inside the Getting Started section. React for example, [has a section dedicated to the tutorial, outside the docs](https://reactjs.org/tutorial/tutorial.html).

* Instead of presenting a tutorial or a specific doc page when arriving in the docs, we could ask the user _how_ do they want to get started instead of getting them started [like in Github](https://docs.github.com/en). We can present different options and guide them instead of taking them to a certain place. I'll try to consolidate this in a Miro board or Figma to clarify the idea.

**Comment by mircubed** [comment]
@crjm should I close this issue and create another issue to show that we are working on implementation and adding content now?

**Comment by jpadams** [comment]
@jpadams working on templates content and copy in this re-design
