### ISSUE TITLE
Support http/https proxy for core.#GitPull, core.#HTTPFetch, core.#Pull

### ISSUE THREAD

**Issue by samalba** [dagger/dagger#2756]
PR #2748 added support for HTTP and HTTPS proxy from environment variables inside actions tasks. However it actually supports proxies for anything using `core.#Exec`. The proxy env vars will be ignored for other ops involving network connections: `core.#GitPull`, `core.#HTTPFetch`, `core.#Pull`.

It's not critical as most packages are built on top of `core.#Exec`. Also, not sure if there is a proper way to support proxies outside of a llb Exec.

Related issues: #2053 #1369 

cc @dolanor @aluzzardi

**Comment by spacedub** [comment]
@dolanor AFAIK buildkitd does honor the usual env vars for pull and push:

`docker run --rm --env HTTPS_PROXY=1.2.3.4 --env HTTP_PROXY=1.2.3.4 --privileged --name buildkitd -ti moby/buildkit`

Will end with:

`error="failed to do request: Head \"https://registry-1.docker.io/v2/library/debian/manifests/latest\": proxyconnect tcp: dial tcp 1.2.3.4:80: i/o timeout" host=registry-1.docker.io`

The code responsible for that seems to be here: https://github.com/moby/buildkit/blob/a45b7698dcc14aea3b42ea8bbba39a39381e18f1/util/resolver/resolver.go#L187

Of course that's not enough to be able to set a proxy *per-op* - but then I'm wondering if that's really a use-case worth addressing?

eg: having to use a proxy seems to me like something you want globally, all the time - so in that case it seems to make more sense to just start buildkitd manually with the appropriate env rather than having to somehow stuff that into plans / actions.

2 cents.

Hope that helps.

**Comment by spacedub** [comment]
Interestingly `buildkitd` does properly honor the proxy env vars it was started with when using `buildctl` (seen above in the logs) - but not when using `dagger` as a client... weird?

**Comment by samalba** [comment]
Interesting, this did not work when I tried it on dagger-buildkitd (the buildkitd that dagger starts automatically). Maybe it was due to my dev env. Either way, if this is true, it's trivial to fix by optionally add the env vars on the `docker run` cli if they are present on the host: https://github.com/dagger/dagger/blob/0a2445d7d8719f38ce55fde1c78d2d2b3a9ddc66/util/buildkitd/buildkitd.go#L230

**Comment by dolanor** [comment]
> Interesting, this did not work when I tried it on dagger-buildkitd (the buildkitd that dagger starts automatically). Maybe it was due to my dev env. Either way, if this is true, it's trivial to fix by optionally add the env vars on the `docker run` cli if they are present on the host

That's what I tried in my experimentations, and even that didn't work, which made me think it was more of an upstream issue.
