### ISSUE TITLE
✨ Clarify what the intended way to use the `yarn` action is

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#2791]
### What are you trying to do?

In a `dagger` plan, if you include two `Yarn` actions and you don't specify a `project` field (which is optional), that will cause undesired effect in caching since both actions will share the same cache `id` as the `project` field is used here https://github.com/dagger/dagger/blob/main/pkg/universe.dagger.io/yarn/yarn.cue#L134 and here https://github.com/dagger/dagger/blob/main/pkg/universe.dagger.io/yarn/yarn.cue#L141 respectively. 

An evident proposal to  improve this would be to make the `project` field required **and** add  proper documentation on the action module to clarify this behavior. 

cc @shykes @rawkode @helderco  

thoughts?

### Why is this important to you?

Avoid surprises when using the `Yarn` action without specifying a project nam.

### How are you currently working around this?

Intentionally setting different project ID's for both actions

**Comment by rawkode** [comment]
I notice that each dagger.#FS has an ID. Would this be unique enough to use as a default value for the yarn project name?

**Comment by helderco** [comment]
No, that's a hidden value only accessible to the engine.

**Comment by shykes** [comment]
I think it's fine to make it mandatory. Making the field optional is less friction for getting started, but given the absence of API reference and proper package documentation in general, there's no guard rails when you add a second yarn build and caching starts to break. So, adding a little friction upfront seems acceptable.

Questions & notes:

1. I'm assuming that the caching issue caused by sharing an ID is actually bad? Like possible data corruption, deadlocks etc? I'm asking because, if the symptom is a slightly less efficient build for example, then that would change the nature of the tradeoff. This depends on how yarn implements its caching. cc @marcosnils 

2. From first-hand experience, this ID-based model for managing cache directories is confusing and a common source of problems. The issue is that it's a completely different model than for other directories. To share a regular directory for copy or mount, you use a special type `dagger.#FS`, but to share a cache directory you use an ID string? I have seen several users thoroughly confused by that, and I don't blame them. I know it maps directly to how buildkit handles cache dirs... But I think we need to rethink this part of the API for hypothetical future API redesigns... cc @aluzzardi @sipsma @helderco 😇

**Comment by marcosnils** [comment]
> 1. I'm assuming that the caching issue caused by sharing an ID is actually bad? Like possible data corruption, deadlocks etc?

On David's case the issue is that he has multiple projects using the same `Yarn` definition and dagger would cache the initial run and then it will re-use the same cache incorrectly for the second project since he wasn't changing any inputs on the action. 

@rawkode  mind sharing how you were defining your actions so Solomon has a better idea of what I'm trying to achieve? I don't have the Dagger Cloud URL's with me now :pray:

**Comment by shykes** [comment]
> On David's case the issue is that he has multiple projects using the same `Yarn` definition and dagger would cache the initial run and then it will re-use the same cache incorrectly for the second project since he wasn't changing any inputs on the action.

By "re-use the same cache", do you mean "cache the operation", or "mount the same cache directory"?

**Comment by marcosnils** [comment]
closing until universe decisions are clear here: https://github.com/dagger/dagger/issues/3206
