### ISSUE TITLE
✨ Allow tag with #Dockerfile

### ISSUE THREAD

**Issue by troncoso** [dagger/dagger#2907]
### What are you trying to do?

When I build my docker image using a dockerfile, I pass a name and tag using the -t flag. However, I can't find any options to set this using docker.#Dockerfile or even core.#Dockerfile.

### Why is this important to you?

I need to be able to properly name and tag my docker images to push them to Elastic Container Registry.

### How are you currently working around this?

I'm not. I can't see anyway to tag my image

**Comment by bluebrown** [comment]
You can have a look at this example: https://docs.dagger.io/1205/container-images#automation. 

Currently, the tag is part of `dest`.  I think in the future in may be its own field or similar and allow providing multiple tags in a list in order so save the user from implementing logic like shown in the linked docs.

Docker engine also handles all parts of the image fqdn together under the term *tag*. That is you provide registry, repository and tag with the `tag` flag or command.

**Comment by troncoso** [comment]
Thank you @bluebrown. Should we leave this issue open to track adding this new field at some point, or is that already being tracked?

**Comment by bluebrown** [comment]
If something like this field is added, it's added to the Push actions, I think. I don't think Dockerfile will get a tag field or any way of naming them apart from the name of the action, so you can reference it in other actions.

If you want to use the result of the Dockerfile action you will always combine it with something else, that's why it doesn't make a lot of sense to have the ability to tag it in this place, I guess.

I personally would close the issue, but I am not a maintainer, so I can't really tell. There is an open issue for multiple tags though https://github.com/dagger/dagger/issues/2774.

**Comment by troncoso** [comment]
I think you make a good point and it solves my issue, so I'll close this myself as I know longer want/need this feature
