### ISSUE TITLE
website: Review of onboardingv2

### ISSUE THREAD

**Issue by slumbering** [dagger/dagger#2964]
Hey 👋 !

I've spent some time on the new version of our docs. That's an awesome work 👍 🚀 !! I'm sure this will help our users to find the appropriate path.

After using it, I saw minor issues + some suggestions.
## Overview page
- It should be titled **Overview** instead of Welcome.  Every other pages are titled regarding their label in the sidebar (Install Dagger, How it works...).
- The image in the overview page (Where does Dagger fit?) looks wrong comparing to the original one. Colors looks purple instead of blue
- Paddings should be like in the mockup
## Quickstart Templates
- Sidebar label should be bold when page is selected
- The title of this section should be **Quickstart Templates** or the other way around, it should be **Explore our templates** in the sidebar.

## How It works
- Titles Core Concepts, References.... are smaller than mockups.

## Header

- We could improve the way we're displaying cta. Currently, we have an input style, a label (blog), two icons and one real button. Visually it looks a bit confusing. Grouping Github icon and toggle light/dark could be a first improvment (link in materialUI, https://mui.com/material-ui/). No need verticals bars if common components are grouped. The search input (which is a button in reality) looks lost in the middle. Like in material-ui, it should be align to the right and smaller.

cc @Camille-Elairin  @crjm

**Comment by crjm** [comment]
Hey! Thanks for the feedback, I'm glad you liked the work we made.

I agree with all the suggestions, and have a couple of comments for some of them: 
* Header: Agree that the search bar is a bit lost. We should mock-up a new approach. 
* How it works: Sidebar label should be bold when page is selected. This is an issue because that button is actually referencing a section inside the Install page, so the Install page is the one getting focused in the sidebar instead of the Templates one. We discussed this with @jpadams, so we have a way to make the templates more visible. In the near future we should have a standalone page for the templates; as we already have the components, it should be straightforward. LMK if I should create an issue on this.

I'll work on the rest!

**Comment by slumbering** [comment]
> Hey! Thanks for the feedback, I'm glad you like the work we made.
> 
> I agree with all the suggestions, and have a couple of comments for some of them:
> 
> * Header: Agree that the search bar is a bit lost. We should mock-up a new approach.
> * How it works: Sidebar label should be bold when page is selected. This is an issue because that button is actually referencing a section inside the Install page, so the Install page is the one getting focused in the sidebar instead of the Templates one. We discussed this with @jpadams, and we decided to to make the templates more visible. In the near future we should have a standalone page for the templates; as we already have the components, it should be straightforward. LMK if I should create an issue on this.
> 
> I'll work on the rest!

💯 for the templates standalone page

**Comment by slumbering** [comment]
@Camille-Elairin is now part of dagger repo :).
