### ISSUE TITLE
Embed buildkit

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#3058]
Currently the setup instructions start with "make sure dagger-buildkit is running". We should remove this dependency on an external buildkit daemon, by embedding buildkit into the cloak binary.

**Comment by gerhard** [comment]
One of the features that everyone I worked with **loved** about Concourse CI was the single binary approach. It was just shy of 300MB (so almost as big as Windows '98), but it had absolutely everything built-in, including the CLI. It had Windows, Mac & Linux variants, and it was trivial to run it on any platform. The vast majority of people would run it on Linux because it had proper support for containers. Windows & Mac were storing state in dirs and were not as mature, but they worked and people used them.

This is the experience that I imagine us having for the new Dagger:

<img width="1413" alt="image" src="https://user-images.githubusercontent.com/3342/192519850-3bd646e6-33ee-4cc8-b5e2-98d9a74e4c11.png">

WDYT @vito?

---

If certain features are not supported on a particular platform today, it's OK to return `not implemented` errors. In terms of the platforms that BuildKit supports, this suggests to me that everything we care about is supported: https://github.com/moby/buildkit/releases/tag/v0.10.4

**Comment by grouville** [comment]
To keep you all in touch, the second option seems very promising -> embedding the go distributed binary with `//go:embed binary`. Using below test script:
```
package main

import (
	_ "embed"
	"fmt"
	"os"
	"os/exec"
)

//go:embed binary
var f []byte

func main() {
	_ = os.WriteFile("foobar", f, 0755)
	defer os.Remove("foobar")
	out, err := exec.Command("./foobar", "version").CombinedOutput()
	if err != nil {
		fmt.Print("ok", err)
		return
	}
	fmt.Printf("Output: %s\n", out)
}
```
I am able to play with "foobar", which is the go binary. It would require to have different "embed" go binary for each distribution (in our pipeline), but it seems manageable. Next step today: auto-build my fork of cloak using that very script.

- Next challenge around that: we currently only build on linux, so managing windows + mac will then become more important

**Comment by sipsma** [comment]
> To keep you all in touch, the second option seems very promising -> embedding the go distributed binary with //go:embed binary. 

I think it will be more than this. Once we actually want to build something with the embedded binary we will also need to have access to a `GOROOT` (i.e. all the stdlib source code), so that will need to be embedded too I believe. 

Overall, my thinking is that no matter what we will need a provisioner (docker, lima, etc.), right? And so it seems simplest to me to just re-use what we support for provisioners as builders too. So we can embed our source code into our binary but then just use `docker build` or `lima whatever` to actually build it. That means that we have no new dependencies or complications on top of the dependencies and complications we need for provisioning/executing daggerd.

Another option here would be to either A) embed the full `golang` container image into our binary (which we can then unpack and use locally) or B) import a container image pulling library that allows us to pull and unpack it locally when needed. I'm not sure, but we *might* be able to get away with a rootless approach here through use of `LD_LIBRARY_PATH` (that's the safe one, not to be confused with the evil `LD_PRELOAD`) and thus avoid the need to `chroot` or setup namespaces, etc.. But this would be more advanced, probably not the right starting place.

I agree that if we go the route of embedding the go binary and GOROOT it's not the absolute end of the world, but I am quite confident it will eventually be a pretty huge gotcha for anyone building or packaging dagger. One of go's touted benefits is that if you give it the right build arguments it will create a statically linked binary for you. If we go this route, that's just not possible anymore as there will always be this secret link against libc.

**Comment by grouville** [comment]
Ok, so (2) seems doable BUT isn't the easiest to implement. As seen with @sipsma today I'll implement, for tomorrow, the pluggable provisioner approach to merge the current Buildkit integration into cloak (to avoid parallel work for too long).

We'll then be able to explore all the other options from there
Another source of reference: https://github.com/k0sproject/k0s, which has 3 approches (using provisioners), with and without provisioners.

**Comment by vito** [comment]
Quick side-note: one weakness to our approach was we left the user responsible for managing the `sudo concourse worker` command lifecycle. Maybe we could have a "systemd unit" provisioner to make it easier to daemonize. This would only be relevant to a Linux host though.

**Comment by sipsma** [comment]
@vito 

Thanks for the context there, super interesting and the matryoshka doll idea was particularly delightful :-) 

One thing to clarify, part of what we are doing here is to wrap buildkitd. We aren't considering this a fork because we are still using the same buildkitd codebase, we just are recreating their main func and making it a subcommand of cloak. We're doing the same for `buildctl` too.

The main problems we need to solve are:
1. cloak may need to provision itself on platforms that are different than what it was built for (i.e. cloak on a macbook needs to deploy itself to a linux vm running in docker desktop/lima/etc.).
2. Like you mentioned, there are more binaries to buildkitd than just buildkitd (runc, emulators, etc.)

> Is there a reason I missed to avoid embedding pre-built binaries?

For the use case here this would entail embedding `cloak` and any other required binaries (`runc`, emulators) for each target platform we may want to support. I suppose `runc` and emulators could also become subcommands of `cloak` too, so then that simplifies the problem to `cloak` embedding `cloak` binaries for all other platforms.

My main concern there was the enormous bloat in the binary size, which was one reason why I liked the approach of embedding source code only as much as possible and then re-using our provisioners (docker, lima, etc.) to also do the building. However, I'm realizing that might be a personal bias worth reassessing (I did a lot of IoT stuff in previous jobs where huge binary generally == bad). The fact that @gerhard and other concourse users did not consider 300 MB to be a deal breaker probably indicates that it's not the mortal sin I thought it was.

If we assume big binary is fine, then yeah it's by far the simplest approach in terms of runtime behavior (build time is a bit complicated, but that's fine obviously).

---

I do think that no matter what we need to make all of this pluggable and behind interfaces like:
1. Builder - give me a cloak binary (or rootfs with binaries) targeting a given platform, hypothetical example implementations:
   * Retrieve an embedded binary/rootfs
   * Download a corresponding binary/rootfs from the internet somewhere (check its hash and all that)
   * Use embedded source code to build cloak using `docker build` (or various equivalents)
   * Use embedded source code to build cloak using cloak (once we've bootstrapped ourselves sufficiently)
2. Provisioner - run cloak somewhere, example implementations:
   * `docker`
   * `lima`
   * fork/exec (need sudo)
   * embedded rootless container engine
   * k8s
   * `CLOAK_HOST` env (connect to existing one)

The thing is today we do already have 2 Provisioner implementations (`docker run` and `BUILDKIT_HOST` env), so what we're trying to do now is add our first Builder implementation. I think given that we already have a dependency on `docker run` in our main current Provisioner, the absolute simplest route is to add a Builder that just uses `docker build`. No new dependencies.

I think this is the shortest route to something usable. It may also be desirable in that until we have sufficiently stabilized cloak, it may not be good to bootstrap and use cloak to build cloak (my instinct anyways, low confidence). So even when we want to start embedding binaries in binaries, we will need to build those binaries somehow.`docker build` is probably an okay solution for enabling that until we've reached the point of being able to use cloak.

That's why I suggest starting here with `docker build`+embedded source code, but in such a way that its behind an interface that can have more implementation in the future.

**Comment by vito** [comment]
Oops, a correction now that I've checked how Concourse is actually packaged these days: it doesn't do an all-in-one binary anymore, instead it's a big (1.4GB!!!) `.tgz` that you unpack to `/usr/local/concourse` that just includes all of its dependencies under `bin/` and other dirs. They aren't embedded anymore. The approach is similar in spirit; it's still bundling binaries, but the user manages where they're placed instead of having a self-extracting binary.

I think we opted to do this because we had a ton of assets to unpack and it was faster to just have the user do it at installation time rather than pay a penalty at runtime.

> One thing to clarify, part of what we are doing here is to wrap buildkitd. We aren't considering this a fork because we are still using the same buildkitd codebase, we just are recreating their main func and making it a subcommand of cloak. We're doing the same for buildctl too.

Similar for us - `concourse worker` was just glue for running `gdn` and registering it as a Concourse worker. But instead of re-implementing `main` we just ran `gdn` as a sub-process.

We originally tried using its code directly, the same as you're proposing, but it was nontrivial to integrate its build into ours. Just shelling out ended up being less of a hassle and meant we could very quickly just bump an asset when it came time for security updates without worrying if any part of the build process or dependencies (`replace` rules in `go.mod` etc) had changed.

> My main concern there was the enormous bloat in the binary size, which was one reason why I liked the approach of embedding source code only as much as possible and then re-using our provisioners (docker, lima, etc.) to also do the building. However, I'm realizing that might be a personal bias worth reassessing (I did a lot of IoT stuff in previous jobs where huge binary generally == bad). The fact that @gerhard and other concourse users did not consider 300 MB to be a deal breaker probably indicates that it's not the mortal sin I thought it was.

Totally fair. We did get a snarky tweet about it. :laughing: But yeah it didn't seem to cause any actual issues.

If we're considering embedding Go itself though, it's not exactly tiny:

File name | Kind | OS | Arch | Size | SHA256 Checksum
-- | -- | -- | -- | -- | --
go1.19.1.linux-amd64.tar.gz | Archive | Linux | x86-64 | 142MB | acc512fbab4f716a8f97a8b3fbaa9ddd39606a28be6c2515ef7c6c6311acffde

Maybe parts of it could be stripped out?

The sum of all binaries in buildkit's `.tgz` is 111.5MB, which is definitely heftier than I had hoped but it's around the same ballpark. If we remove `buildctl` (I don't think we need it?) that would save 25M.

```
❯ ls -lh
total 111M
-rwxr-xr-x 1 vito users  25M Oct 20  2015 buildctl
-rwxr-xr-x 1 vito users  38M Oct 20  2015 buildkitd
-rwxr-xr-x 1 vito users 5.2M Oct 20  2015 buildkit-qemu-aarch64
-rwxr-xr-x 1 vito users 3.8M Oct 20  2015 buildkit-qemu-arm
-rwxr-xr-x 1 vito users 2.9M Oct 20  2015 buildkit-qemu-i386
-rwxr-xr-x 1 vito users 3.3M Oct 20  2015 buildkit-qemu-mips64
-rwxr-xr-x 1 vito users 3.2M Oct 20  2015 buildkit-qemu-mips64el
-rwxr-xr-x 1 vito users 3.8M Oct 20  2015 buildkit-qemu-ppc64le
-rwxr-xr-x 1 vito users 3.4M Oct 20  2015 buildkit-qemu-riscv64
-rwxr-xr-x 1 vito users 2.9M Oct 20  2015 buildkit-qemu-s390x
-rwxr-xr-x 1 vito users  20M Oct 20  2015 buildkit-runc
```

This would definitely start to add up if we start bundling each supported platform/architecture. Maybe we could have a "netboot" version that lazily downloads the appropriate package as needed? We'd still want a batteries-included version for behind-the-firewall though...

---

+1 to the builder/provisioner ideas. I think those are important primitives to have around so we can stay nimble and adjust as we encounter new deployment schemes.

**Comment by shykes** [comment]
I am closing this issue because, although the need to bundle buildkit still exists, our preferred solution is no longer to bundle everything in the same binary. Rather, we should aim to make the Dagger Engine a fully server-side component (instead of the current mix of client-side API router and server-side solver (aka buildkit) - then bundle it all into an OCI image. We should start fresh and discuss this new approach in a new issue.
