### ISSUE TITLE
Fix providing list and other more complex args to cloak CLI 

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#3082]
Right now you can't provide a list of strings using the `--set` flag to cloak, it doesn't get parsed correctly. It really only works for simple string input types at the moment. We need to use introspection to know what type to anticipate and enable the correct parsing (or we can accept json like format for complex args and be okay with some dumb corner cases like not distinguishing `[1,2]` from `"[1,2]"`)

This will also setup more nice potential features like possibly not having to explicitly provide `--local-dir` (instead it can just be inferred that the string you provide is path, maybe...)

**Comment by marcosnils** [comment]
@sipsma took a very basic and straightforward shot here https://github.com/dagger/dagger/pull/3748/files#diff-b3e3532203640cd8749d2a8e1e4530113971a9e1370b7622d826524fdd226c60R126-R168. Instead of introspecting the grapql schema, I've decided to go for the simpler route of trying to parse the possible graphql basic types. 

Seems like this works for the most common cases and I'd assume it should be able to unblock us until we can work on this further. WDYT?

**Comment by sipsma** [comment]
Ancient issue, addressed in modules implementation
