### ISSUE TITLE
Discontinue "cloak dev"

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#3188]
`cloak dev` is a fun way to run the interactive GraphiQL playground against the dagger/cloak engine. But it doesn't have to be embedded in the core engine.

There are many graphql tools that could potentially be used in this way, and this can easily be done without embedding any of them in the core engine binary.

Meanwhile, the other use of `cloak dev` (spawn the engine for the purpose of embedding it in a script or tool) should remain in the core, but under its own sub-command (perhaps `cloak engine`?) and with some modifications: no graphiql of course, but also no listening on `http://0.0.0.0:8080` by default.

**Comment by shykes** [comment]
This came up in a live discussion with @marcosnils .

**Comment by marcosnils** [comment]
> no graphiql of course, but also no listening on `http://0.0.0.0:8080` by default.

shall we aim for socket-first transport and enable tcp as an option?

**Comment by shykes** [comment]
> > no graphiql of course, but also no listening on `http://0.0.0.0:8080` by default.
> 
> shall we aim for socket-first transport and enable tcp as an option?

That's a question for @aluzzardi @sipsma .

Personally I think communication should happen over stdin/stdout, and not be configurable. That will make it very clear how you're supposed to use the engine: embed in your tool or script, add wrapping logic at your leisure.

**Comment by sipsma** [comment]
Yeah the slight variations of options are:
1. stdin/stdout
2. Additional pipe fds passed to engine (i.e. 3+4), in case we want stdin/stdout for some reason
3. `socketpair(2)` fd passed to engine

Can just see what ends up being easiest when trying in each language sdk. Probably should also put this behind some sort of pluggable interface (i.e. something in the spirit of `CLIENT_IN=fd://0`, `CLIENT_OUT=fd://1`, but with better names).

**Comment by aluzzardi** [comment]
> Can just see what ends up being easiest when trying in each language sdk. Probably should also put this behind some sort of pluggable interface (i.e. something in the spirit of CLIENT_IN=fd://0, CLIENT_OUT=fd://1, but with better names).

+1 pluggable

Perhaps, since the SDK needs to launch the cloak engine anyway, could be `cmd://path/to/cloak` (implies exec + stdin/stdout comm)

> If people complain about a missing feature that cannot be easily done in a wrapper (I don't see one right now) then we can always change our minds later and add more.

All the graphql tooling that's not built on top of our SDK. Docs generators, vscode extensions, ...

I think clients should be able to connect over "cmd" (spawn an engine and talk), "http" (from outside) and "unix" (inside the container)

**Comment by marcosnils** [comment]
> I think clients should be able to connect over "cmd" (spawn an engine and talk), "http" (from outside) and "unix" (inside the container)

+1 here.. removing the `tcp` / `unix` ability out of the box will limit a good part of the possible tooling that could grow around the API. Also, I'm not sure how that would impact on the current internal graphql code generation process since my guess is that it's quite entangled with the transport?
