### ISSUE TITLE
cloak.yaml should be optional

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#3275]
Sometimes you want to run dagger pipelines without loading extensions. At the moment that requires creating an empty `cloak.yaml`.

As reported by @kpenfound

**Comment by sipsma** [comment]
> Should there also be an option to pass a *core.Project to engine.Start( Config{ ... } ) instead of a path to a project yaml?

Yeah I can't think of any reason why not. For other language SDKs that have to invoke the engine as a subprocess I guess the equivalent might be the ability to pass a json string for `dagger.json` rather than a path to it.

Or if we want to be really fancy, you could pass a uri to the engine as an arg:
* `local://path/to/dagger.json`
* `json://{"literal":"json"}`
* `git://https://github.com/....`
URI might be way overkill for now, but maybe in time.

**Comment by shykes** [comment]
This makes sense, keeping in mind we’ll want to support fetching a project file from Dagger Cloud as well.

**Comment by sipsma** [comment]
This will be closed by https://github.com/dagger/dagger/pull/3281

Without making dagger.json optional it started polluting tons of directories, so just threw it in there.

**Comment by sipsma** [comment]
Merged https://github.com/dagger/dagger/pull/3281
