### ISSUE TITLE
Decide if we should package generated `core` SDK with Dagger or rely on user-run codegen

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#3320]
One possibility: we package the core sdk for now. In the future we transitioned to codegen but provide some light tooling to ease the transition. There are already tools for rewriting go imports automatically so I don't think this would require great effort on our part (🤞)

**Comment by shykes** [comment]
Based on today's live discussion (link?) the consensus seems to be:

* Drop user-run codegen for now
* Plan on re-introducing it later as part of the Extensions feature
* In the meantime, look for opportunities to "nudge" the DX in the right direction, so that switching to extensions is easier. For example, the Go SDK could be structured to encourage creating the equivalent of an operations document, but in Go. Basically a named collection of reusable functions, which could later be moved into an extension with minimal effort

**Comment by sipsma** [comment]
> Based on today's live discussion (link?) the consensus seems to be:

Yeah I opened this in case I or anyone came up with any better ideas but this is the route we're going. Closing now

**Comment by helderco** [comment]
The core api is already powerful. I like the idea of being able to start writing a script without having to generate first. Generate only if having other dependencies. I'm not just talking about Go, Python and Typescript can be the same.

> Drop user-run codegen for now

I don't have context. What's the reason? Was there a difficulty getting this to user? Or is it just for easier adoption?

> Plan on re-introducing it later as part of the Extensions feature

What's the plan? Do we intend to eventually "user-run" codegen even for core? Just trying to understand if this is temporary.

**Comment by shykes** [comment]
> > Drop user-run codegen for now
> 
> I don't have context. What's the reason? Was there a difficulty getting this to user? Or is it just for easier adoption?

It’s a consequence of cutting extensions from first tech preview, to buy us time to finish the extensions design. Codegen is part of that design, so we’re cutting it too.

> > Plan on re-introducing it later as part of the Extensions feature
> 
> What's the plan? Do we intend to eventually "user-run" codegen even for core? Just trying to understand if this is temporary.

We don’t know exactly how we’ll reintroduce it, since that’s part of the unfinished extensions design. We’re taking a leap of faith that we’ll figure it out, and that having actual usage on the tech preview will make it easier.
