### ISSUE TITLE
Calling a resolver from the same extension

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#3328]
I've discussed a bit with @aluzzardi on this. No clear winner but we settled on nr. 1, at least for now since there's other priorities. 

👉 **Just something to think about** in the meantime.

⚠️ I'm just brain dumping things, some of which I know shouldn't work, just because it can help fuel other ideas.

## Use case

Imagine you have an extension with a resolver that depends on another resolver from the same extension. For example, in a company's abstraction for an app's _deployment_, it could call _build_, _test_ and _push_. Don't get hung up on this particular example, let's just assume hypothetically that you need/want to do this.

## 1. Don't support it

Maybe it won't be an issue. Scripts can call those granularly.

### Tradeoff

I think this need will surface, but not sure how common. There's an easy workaround though.

## 2. Call resolver directly

Since resolvers are just functions you can just call them directly. Either by going through the GraphQL library or by reusing a normal function for defining the resolver and for being called directly.

### Tradeoff

Doesn't take advantage of buildkit caching. In some resolvers it may not make much difference if you're just querying the dagger API. Those queries would be cached. But you could be doing something more expensive with an external library which is one of the strengths of our multi-language design.

Still, it's better than not being able to and it's already possible to do it.

## 3. Sub-extensions

An extension within an extension. So you could extend a parent extension's type with a resolver that's technically in another extension.

### Tradeoff

Impossible. Besides more fragmentation, higher maintenance and complicated, there would be circular dependencies right?

Even then, how does this help referencing that directly? You'd have to make up a query (see next one) but you can already do that in the same extension.

## 4. Make up a query

Maybe make up a simple query (hidden by higher level api).

### Tradeoff

Maybe not realistic, haven't thought deeply about it. You may need the parent's chain. May work for some cases. If so, it's available today.

## 5. Query the engine for a specific resolver

Crazy idea, just something that popped in my mind.

What if the extension has a function from the SDK library to specifically call a resolver? Underneath it would query the core engine not with a GraphQL query but with something compatible with `/inputs/dagger.json`. The engine could then just get the correct resolver from the type and execute it with provided inputs.

### Tradeoff

Farfetched and crazy 😛

1. For one it would require some communication channel from extension to engine. Not through GraphQL endpoint, unless there's a supported way to do it without using a query. Haven't looked.
2. Even then, the extension's resolver would need the parent result for the other resolver and you may not have it.
3. What would the API for it look like? Will it be confusing that you have a way to make API queries and another for calling sibling/cousin resolvers directly?

**Comment by sipsma** [comment]
We actually used to support this on accident because the old client codegen was including an extension's own schema when generating code for that extension.

That approach is appealing in some ways in that it just re-uses our existing mechanisms to enable self-calls. The most annoying part of that approach though, at least in languages like Go+TS, would be that you couldn't get a client for yourself until your own code compiled (since your code needs to compile to derive the schema).

This leads to situation like e.g., in the middle of writing a function (doesn't yet compile), realize you need to update your codegen, try running it, it fails because you were still writing out code, thus have to delete/comment-out code just to get it to compile, re-run codegen, uncomment code, etc.

I think there's probably ways to alleviate that, e.g. in Go if we changed code-first schemas to rely fully on AST parsing (rather than the combination of AST+reflection), then we can derive the schema without every line of code necessarily being compilable (same reason that IDEs can type check code that has compilation errors). TS may already be that (the difference between AST and reflection in TS is more blurry).

But that's a big change with lots of implications, not really worth pursuing unless no other options.

---

> 2. Call resolver directly

This is the path I've gone down when thinking about it in the past.

In languages with more "magic" like TS/JS and Python, I wonder if we could make it so when you call `this` or `self` it actually ends up being a client call that goes back to the router and then calls the extension separately, so you end up with the nice caching behavior but in a seamless way. TS/JS lets you do weird stuff with rebinding `this`, maybe there's some other approach that could accomplish the same end effect in Python.

The problem is that Go will be a hell of a lot more complicated. I can't think of any way of doing that that wouldn't end up being something like doing AST parsing to find calls to the receiver of a method and then rewriting them to be client calls and compiling that code instead of what the user wrote. Maybe possible, but really complicated and sort of terrifying. The other options would involve boilerplate for the user, which is maybe okay but sad to have to accept.

So yeah, it's a good open question! :-)

**Comment by helderco** [comment]
With #5060 this should be simple. We can revisit when we come to full extensions support.
