### ISSUE TITLE
Test suite across SDKs (moulinette)

### ISSUE THREAD

**Issue by grouville** [dagger/dagger#3404]
# Problem
In cloak (0.3), SDKs will improve the DX when developing extensions / plans on Dagger.
As it eases the DX, it also adds challenges around the maintainability of the codebase.

We need to ensure that:
1. SDKs don't break when updating our `core` api
2. SDKs don't differ too much from each other
3. a centralized test suite with all the expected behaviors is easily available to our community (to implement a new SDK, for example)
4. The docs are up-to-date with SDKs/core API

# Solution
Implement a moulinette (program) that runs the same test suite on each SDK, and diffs inputs/outputs

cc @aluzzardi

**Comment by vikram-dagger** [comment]
> /cc @vikram-dagger do you think this is a good idea?

It's definitely a good idea for the product. However I'm not sure if docs can benefit from it, because docs code examples will not be uniform across the different SDKs so a common test suite would not fit well there. Also, code in docs is embedded within markdown files, so if we want to run tests on that code, we probably need to separate the code from the text around it before testing.

**Comment by grouville** [comment]
> docs code examples will not be uniform across the different SDKs so a common test suite would not fit well there
So, according to you, anticipating a way to cross-test our docs is too much engineering, as our use-cases will not overlap ?

> we probably need to separate the code from the text around it before testing.
This is what we used to do, and it was an implied first baby step yes

**Comment by dolanor** [comment]
related: https://github.com/dagger/dagger/issues/3404
