### ISSUE TITLE
rename `examples` directory to more appropriate name 

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#3446]
When new users arrive they often look for tutorials, readmes, samples, and examples.

We have an `examples` directory that came from the merge of the `cloak` codebase into `main`.
It contains examples of extensions.
We're not emphasizing extensions right now as we perfect the messaging and DX.
So we should rename this directory for now so new users are not confused into thinking these are relevant examples for Go SDK etc.

I propose renaming the directory to 1. `experimental` or  2. `extensions`. Or nested as 3. `experimental/extensions`.
Since we want to talk about extensions later on, I'd think option 1 or 3 is best.

@shykes @mircubed

**Comment by jpadams** [comment]
@aluzzardi

**Comment by shykes** [comment]
Let's make it private for now, to optimize for absence of confusion. From there we can figure out what to do and when.

**Comment by aluzzardi** [comment]
👍 

> I propose renaming the directory to 1. experimental or 2. extensions. Or nested as 3. experimental/extensions.
> Since we want to talk about extensions later on, I'd think option 1 or 3 is best.

Any option sounds good to me (/cc @sipsma)

There's two directories in `examples/` that are not extensions:
- `python`: @helderco @kpenfound any idea of where that should be moved into?
- `queries`: that's just a collection of GraphQL queries. Thoughts on where those should go?

**Comment by sipsma** [comment]
Agree, the name `examples` is leftover from ancient times. We could also just move the extensions to be under `core/integration/testdata` for now since there's some tests for them in there anyways. Basically, keep testing that they work but don't make them importable yet.

> queries: that's just a collection of GraphQL queries. Thoughts on where those should go?

I don't know if we need those anymore, I think docs, examples and test cases cover that now. I'd be okay with removing them now; they served us well :-)

**Comment by helderco** [comment]
We can put the python examples on `sdk/python/examples` or in `dagger/examples` repo. I'm going to maintain my own `helderco/dagger-examples`.

The tests can also work as documentation and there'll be more examples in docs.

**Comment by kpenfound** [comment]
Currently the `dagger/examples` repo is organized by use case rather than by sdk, but that's a remnant of before multi-language. I'd be in favor of moving the python example to `dagger/examples:python/<example name>/` and we can reorganize the go examples separately.

I think the argument against putting the examples in `dagger/dagger:sdk/<language>/examples` was bloating the sdks with unnecessary code and dependencies. That sounded like a good enough reason to me to have them in a separate repo

**Comment by mircubed** [comment]
@jpadams @kpenfound do you need anything else to move forward with this?

**Comment by helderco** [comment]
I moved python's:
- https://github.com/dagger/dagger/pull/3769

**Comment by jpadams** [comment]
decided to remove the outdated `examples` directory for now. Planning to get our SDK-specific and use-case-specific examples together in the `dagger/examples` repo. Can move them into `dagger/dagger` in the future, if that is better.
