### ISSUE TITLE
Allow code snippets to be fully copyable

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#3562]
### What is the issue?

There are some code snippets in the getting started docs page here (https://docs.dagger.io/sdk/go/959738/get-started) that require manually copying and pasting certain sections of the snippet which is a bit confusing. I understand that this is done to avoid having huge snippets in the docs, but maybe there's a way where we can display a small snippet but have the copy button in the component to be able to copy the whole executable code.

**Comment by mircubed** [comment]
@vikram-dagger let me know if you need engineering support on this, so I can find the best person to help you.

**Comment by vikram-dagger** [comment]
@marcosnils I'm slightly confused about the behaviour required. 

Option 1: Do you mean that in each intermediate step, you would like to display the entire script (which would also get copied in entirety when the user clicks copy) and highlight the changes from the previous step? 

Option 2: Or, do you mean that you would like to display a smaller segment of code but, when the user clicks copy, the entire script is copied?

The challenges are:
Option 1: AFAIK Markdown doesn't let you highlight specific lines in code blocks. Docusaurus offers a way to do this https://docusaurus.io/docs/markdown-features/code-blocks#line-highlighting so I will check if it works. 

Option 2: AFAIK the copy button simply copies what's displayed in the code block. To change this behaviour so that we have a large copy-able code block of which only a small snippet is displayed, I believe we would need to customize the prism renderer component which Docusaurus uses.

**Comment by vikram-dagger** [comment]
@marcosnils I reviewed the page you linked to. I agree with you that the current approach of manually interpolating modified snippets is too much work and also likely to lead to user errors on account of the snippets being inserted at incorrect positions in the user's working copy of the code. 

However I am not sure if the answer is to modify the code block component such that only a segment is visible but the copy button copies the entire block because:
- it's unexpected behaviour, the user is receiving data via copy that is different from what he/she sees on screen
- it would require customization of the existing code block component, for example to support and understand tags within each code block which indicate which segments of the block should be made visible; this will require engineering time and effort

Perhaps a simpler solution is to have the entire script in the code block, but highlight the changed segments. This way, the user can visually see what has changed but also copy the entire block into the working copy and have it immediately functional. 

I have made this change in https://github.com/dagger/dagger/pull/3578. Please have a look and lmk your thoughts. If this works, I think it would save some time and effort on re-engineering the code block component.

**Comment by marcosnils** [comment]
> Perhaps a simpler solution is to have the entire script in the code block, but highlight the changed segments. This way, the user can visually see what has changed but also copy the entire block into the working copy and have it immediately functional.

yes, we can certainly do this as well. My idea came up as an alternative so we don't have to display the full snippet for each step since the page might feel a bit heavy to read if that's the case.
