### ISSUE TITLE
Directory: add `withNewDirectory` for creating an empty dir

### ISSUE THREAD

**Issue by vito** [dagger/dagger#3567]
New naming scheme for copying files/dirs vs creating files/dirs: https://github.com/dagger/dagger/issues/3567#issuecomment-1294368392

> * `withDirectory`, `withFile`: copy a directory/file (source always required)
> 
> * `withNewDirectory`, `withNewFile`: create a new directory/file

This issue is for adding `withNewDirectory` since `withNewFile` already exists.

**Comment by shykes** [comment]
I understand the consistency part, but do we still want to keep the `source` argument optional, to use the call as a mkdir? If so the new name might be confusing as a mkdir.

**Comment by vito** [comment]
@shykes That's a good point. Should we do the opposite instead? (rename `withCopiedFile` to `withFile`)

**Comment by shykes** [comment]
> @shykes That's a good point. Should we do the opposite instead? (rename `withCopiedFile` to `withFile`)

The reason it’s not `withFile` to begin with is to distinguish “copy” from “new”. So I guess it would be `withFile` and `withNewFile` which would also be weird.

Sorry I don’t mean to be a PITA…

**Comment by vito** [comment]
How about:

* `withDirectory`, `withFile`: copy a directory/file (source always required)
* `withNewDirectory`, `withNewFile`: create a new directory/file

**Comment by shykes** [comment]
I say ship it :)

**Comment by codethief** [comment]
@vito @shykes Hey guys, I'm somewhat late to the party but I just noticed that in the Python SDK v0.18.9 `dagger.Directory` comes with a method `with_new_file()` but not `with_new_directory()`. DuckDuckGo led me here. Did the above changes at the schema level¹ not make it into the Python SDK?

¹) I.e. the PR from above: https://github.com/dagger/dagger/pull/3590 , nowadays https://github.com/dagger/dagger/blob/main/core/schema/directory.go#L118 . Interestingly, this only covers `Directory`, while the `Container` GraphQL type [does not provide](https://github.com/dagger/dagger/blob/main/core/schema/container.go) a `withNewDirectory` field to begin with, even though it does offer `withNewFile`. Was this asymmetry intentional?

**Comment by vito** [comment]
Hi @codethief - it's been a while (3 years) so we probably deprecated this in favor of just calling Directory.withDirectory with an empty dir (dag.Directory)

**Comment by codethief** [comment]
@vito I see.

> in favor of just calling Directory.withDirectory with an empty dir (dag.Directory)

Thanks, this was the pointer that I (= Dagger newbie) needed – I was wondering why I couldn't create an instance of `dagger.Directory` to get an empty directory. 🤦‍♂
