### ISSUE TITLE
Guide: building a docker container

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#3614]
There should be a guide specifically about building a docker container with Dagger. NOTE: this is different from building a eg. Go binary.

**Comment by mircubed** [comment]
@kpenfound can you help provide more context to @vikram-dagger on how this isn't the same as the #3426 guide?

**Comment by kpenfound** [comment]
#3426 is an _onboarding_ story of taking an existing Dockerfile and replacing it piece by piece with a dagger pipeline. It might have steps like:
- build the dockerfile as-is in dagger
- remove build steps from Dockerfile and do them in dagger
- finally delete Dockerfile completely

This is more focused on creating a docker container, probably from scratch and should focus on the things we can do with containers with dagger. [Cover lots of these](https://pkg.go.dev/dagger.io/dagger#Container)

@shykes did you have an idea of what the container should do in this guide since we don't want it to distract from the point by building/compiling?

**Comment by kpenfound** [comment]
@vikram-dagger I think you're right that it's probably covered quite a bit at this point in other guides
