### ISSUE TITLE
Testing the Python SDK before launch

### ISSUE THREAD

**Issue by mircubed** [dagger/dagger#3642]
We should test Python SDK E2E before launching. 

**E2E experience to test:** 
Look at @helderco 's guidance in his comment below 

**Docs to follow while testing:** 
@helderco FIXME

External Users - 
Please comment on this [Discord thread](https://discord.com/channels/707636530424053791/1037447693926150256) if you would like to help test the latest version and give feedback this week. I will add you to a private chat to give feedback. Please make issues for anything that you run into (big or small) and label it sdk/python 

Maintainers to test - 
Please check the box below when you've completed your test. 
- [ ] @samalba 
- [ ] @TomChv 
- [x] @grouville

**Comment by mircubed** [comment]
@helderco assigning to you for now to help me fill in the gaps on the testing guidance. I will share this with users who are helping us test.

**Comment by helderco** [comment]
I'm going to put this in a separate repo that people can clone/fork. But for now, here's the instructions.

## 1. Run the engine

Note: The SDK isn't provisioning at the moment. I left it for later because you can run it manually while there's still an open issue around this:
- https://github.com/dagger/dagger/issues/3653

Clone the [dagger/dagger](https://github.com/dagger/dagger) repo and run cloak: 
```shell
$ git clone https://github.com/dagger/dagger
$ cd dagger
$ go run ./cmd/cloak dev
```
Note: If port 8080 is not available you can chose another, but you'll also have to provide it when instantiating `dagger.Connection()` later.

## 2. Run `client-simple` example

In another terminal tab, go to the [examples/python/client-simple](https://github.com/dagger/dagger/tree/main/examples/python/client-simple) directory and follow instructions to run the provided example.

## 3. About async

Only _async_ is supported at the moment. It's simple enough for basic usage like in the example, I suggest this simple guide for those who are not familiar with it:
- [First Steps with AnyIO](https://asyncer.tiangolo.com/tutorial/first-steps/)

## 4. Few conventions to understand

These tips may be helpful:

- The underlying API is the same as with the Go SDK, so if you understand the few differences you can easily port from to another and reuse some of that documentation as well;
- The Go SDK [no longer needs to pass IDs around](https://github.com/dagger/dagger/issues/3558) but in Python you still do for now;
- If a method returns a `Result` then you know it will execute a query and store the value in `result.value`;
- In async, the result is wrapped in a coroutine so you need to `await` it;
- Any function with an `await` needs to be defined with a `async def`;
- If you don't need to `await` or get a `Result` then you're just building a query;
- Notice that when you use an `.id()` field, it'll execute a query but nothing will actually be run on the runner (it's lazy, see issue in second bullet);
- Notice the type hints in the IDE, they help document what you can do. See next screenshot.

<img width="848" alt="say-wat" src="https://user-images.githubusercontent.com/174525/199725506-e0082a1b-9d55-4e78-bc6c-d8aef7d1f004.png">


## 5. Hack

Hack away at the example or create other files to try different things. 

Your feedback will influence what's going to be ready for next release.

Thank you!

**Comment by mircubed** [comment]
@samalba @TomChv @grouville I believe all of you already tested, but can you confirm here? Thanks!

**Comment by helderco** [comment]
I should add here that there's a repo with examples: https://github.com/helderco/dagger-examples

**Comment by grouville** [comment]
> @samalba @TomChv @grouville I believe all of you already tested, but can you confirm here? Thanks!

Yes, no issue encountered until now. Pretty neat
