### ISSUE TITLE
Generate DAG visualization

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#3663]
It would be amazing if the engine could produce a Mermaid or Graphviz file representing the DAG that it just ran.

**Comment by sipsma** [comment]
There are utils in buildkit for converting LLB -> graphviz: https://github.com/moby/buildkit/blob/ac4f39aaad34da48855d0beb2785a0666c68b895/cmd/buildctl/debug/dumpllb.go#L83-L104

Maybe useful for us (or maybe just inspirational if not reused directly)

**Comment by marcosnils** [comment]
My exchabge with @shykes in Discord about this: 

@shykes:

my guess is that it will make more sense to generate from the graphql layer but I could be wrong
in general it might be time soon to bring back the “run viewer”, first without dag diagram, then we can add it on top
would be a great complement to the playground (but also usable outside of the playground)

@marcosnils:

I was thinking about this and I'm not sure, since buildkit is the one that actually knows the final structure of the DAG. 

In graphql since we're not using aliases, all the graphs that we send to the engine have a single path: clone > mount > exec> export. There are no "parallel" nodes multiple execution paths since we're not allowing the use of aliases.

i.e SDK's will never produce something like this:

{
  container {
    from(address: "alpine") {
      exec(args: ["apk", "add", "curl"]) {
        dagger: exec(args: ["curl", "https://dagger.io/"]) {
          stdout {
            
            contents
          }
        }
        google: exec(args: ["curl", "https://google.com/"]) {
          stdout {
            contents
          }
        }
      }
    }
  }
}


dagger and google would be different paths in the GraphQL graph 

@shykes: 

So it makes sense to start simple and bring back the centralized run viewer first
that will be the foundation on top of which we can bring visualization right
would be sool to see runs magically appear as you run your CI, dev commands, and playground 🙂


@sipsma @aluzzardi @vito any thoughts?

**Comment by shykes** [comment]
Solved by Dagger Cloud 💪  https://dagger.io/cloud
