### ISSUE TITLE
[follow-up] - MacOS provision test

### ISSUE THREAD

**Issue by grouville** [dagger/dagger#4038]
Follow-up of #3225 

Current automatic MacOS `provision`(https://github.com/dagger/dagger/blob/main/.github/workflows/provision.yml) pipeline gets triggered after an engine release.

This can lead to failures getting caught AFTER the bump of the engine. It is the least painful implementation, that is better than nothing, but non optimal.

We've just found one bug today, not directly related to the engine but linked to one of the test of the engine provisioning on Python [introduced by dependabots](https://github.com/dagger/dagger/pull/4037).

_It hasn't been caught by the current pipeline because:_
1. Pipeline gets triggered only on engine bump
2. SDKs aren't updated yet when testing against (shall test against `main` or local engine). The corresponding PRs need to get accepted (to have a full `1:1` version check)

_Other points_
1. We may want to run these tests periodically (once a day), to ensure a consistent state of the engine / SDK compatibility
2.  We want to test the `remote` provisioner, not the local `docker-container`. People will mostly rely on the first provisioning method to retrieve the engine, not the second one, linked to `dev`.

As a more stable solution, @helderco proposed to:
- Spawn a local private registry
- Push the engine in it
- Pull from this registry
- Run tests against this engine

Once Alex's PR regarding [sockets](https://github.com/dagger/dagger/pull/4025) gets merged, a full E2E test in Dagger will be implementable

cc @gerhard @helderco

**Comment by sipsma** [comment]
> As a more stable solution, @helderco proposed to:

Agree with this approach

> Once Alex's PR regarding https://github.com/dagger/dagger/pull/4025 gets merged, a full E2E test in Dagger will be implementable

That will enable us to test provisioning e2e inside dagger, but only for Linux. For MacOS (and windows eventually) we need to run the provisioning tests outside of dagger (due to the fact that containers in dagger are always Linux-based, even when clients are running on other platforms).

**Comment by grouville** [comment]
> g on other platforms).

You're right, my use of the word `E2E` is bad. What I meant is that these steps could be directly set from Dagger:
```
Spawn a local private registry
Push the engine in it
```

Then, we would, from the workflow, pull from the newly pushed image and run the tests against it (as we currently do)

**Comment by sipsma** [comment]
Some aspects of the session interface and provisioning are in the process of changing right now: https://github.com/dagger/dagger/issues/3830

The most relevant to this issue is that the CLI will be downloaded by the SDKs and used instead of the existing engine-session binary (which is pulled from the engine image).

I think as a mvp starting place, it would actually make sense to just use these tests as a blocker on an SDK publish: don't publish an SDK if it can't provision the engine it defaults to.

In that case, we actually wouldn't need to do very much special test setup at all. We can just run these provision tests in `publish-sdk-<sdk>.yml` and not actually run the publish if they fail. In that test, they SDKs don't need to use a dev CLI or dev engine even, they should just execute against their actual defaults, which will be already released engine+cli.

That seems like a really simple place to start. Then, as follow ups in the future we can consider expanding this by running the provisioning tests on every push to main (or maybe once a day).

**Comment by grouville** [comment]
> In that case, we actually wouldn't need to do very much special test setup at all. We can just run these provision tests in publish-sdk-<sdk>.yml and not actually run the publish if they fail.

Thanks for the insight. So; the tests would still need to run on MacOS though ? To be 100% sure. It would be a job running on a MacOS runner, and directly running the SDKs

**Comment by grouville** [comment]
changing owner to reflect reality: #4208
