### ISSUE TITLE
Test+Lint workflows don't run automatically in engine bump PRs

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#4050]
See for example here: https://github.com/dagger/dagger/pull/4049#issuecomment-1332689127

Really not sure why this is. The yamls seem to configure the workflows such that they should run. cc @gerhard in case you have any ideas what would cause this

**Comment by sipsma** [comment]
I had to push an additional commit to fix a nodejs linting error, which for some reason caused the workflows to then actually run? https://github.com/dagger/dagger/pull/4049#issuecomment-1332696061

Still not sure why, but seems like a clue.

**Comment by sipsma** [comment]
> Has this been fixed?

Not to my knowledge no, it was still the case last time we did an engine release

**Comment by marcosnils** [comment]
That's an intentional behavior of the `pull_request` action that we're using: https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs

There are workarounds for this. I'll fix it after the release as part of my boy scout contribs. I'll assign this to myself.
