### ISSUE TITLE
🐞 ./cmd/client-gen doesn't work out of the box

### ISSUE THREAD

**Issue by dolanor** [dagger/dagger#4131]
### What is the issue?

I wanted to regenerate locally some SDK code.
It failed inside the engine of a `./hack/make sdk:nodejs:generate` and I couldn't get more details.
I wanted to see on my host FS what was failing, so I decided to do a:
```
$ go run ./cmd/client-gen/ --lang nodejs -o sdk/nodejs/api/client.gen.ts
```

### Log output

```
Error: failed to start engine session bin: EOF: Error: unknown engine provider: 

Please visit https://dagger.io/help#go for troubleshooting guidance.
Usage:
  client-gen [flags]

Flags:
  -h, --help             help for client-gen
      --lang string      language to generate in
  -o, --output string    output file
      --package string   package name
  -p, --project string   project config file
      --workdir string   The host workdir loaded into dagger

Error: failed to start engine session bin: EOF: Error: unknown engine provider: 

Please visit https://dagger.io/help#go for troubleshooting guidance.
exit status 1
```

### Steps to reproduce

get the latest main (5219a37e)
and run
```
go run ./cmd/client-gen/ --lang nodejs -o sdk/nodejs/api/client.gen.ts
```

### Dagger version

5219a37e

### OS version

Ubuntu 20.04

**Comment by sipsma** [comment]
@dolanor workaround atm is to run `./hack/dev go run ./cmd/client-gen/ --lang nodejs -o sdk/nodejs/api/client.gen.ts`.

`./hack/dev` will bootstrap the dev engine from local code and then execute whatever command you provide in the rest of the args in the context of that dev engine. That fixes the incompatibility which is causing this error.

However, in general that _should_ only be needed when you have local changes to the engine that you need to run against, it's not expected that it's needed when pulling `main` down unchanged. The problem is that `client-gen` is still using the Go SDK, it should be updated to use engine.Start directly (same as the `dagger` CLI does now). I'll see if I can make that update quickly.

**Comment by sipsma** [comment]
This should fix it https://github.com/dagger/dagger/pull/4143
