### ISSUE TITLE
need for explicit dagger.Connect()?

### ISSUE THREAD

**Issue by dolanor** [dagger/dagger#4209]
I'm forwarding a user request I had while helping them

The question was: do we really need `dagger.Connect()`?
As nothing is send to the server until a context is passed to a **solving** function, why not initialize the connection at that time?
What if the connection was done lazily at the first query that is actually sent? (with some `sync.Once`, etc)

(@tiramiseb: If I forgot any other idea behind that, don't hesitate to add a comment )

**Comment by dolanor** [comment]
My answer to that was that we have some options we can pass to the `dagger.Connect()` (`LogOutput` being one of the most useful), and it wouldn't make sense to have those connection options spread all over the API on **solving** function.

Though we could pass them by using `context.Context` key/value store, but I find it too subtle for a clear API.

**Comment by tiramiseb** [comment]
The main problem I had was that I need to initialise the client in the "main" function and then pass it to other functions when trying to make some generic wrapper lib, in order to be able to prepare some queries (simply creating a container), but the client connection itself does not seem to be needed for this.

Maybe we can simply create the different containers, volumes, etc, by simple calls that could be `dagger.NewContainer` or `dagger.NewCacheVolume`, etc. And then, at then end, `dagger.ConnectAndExecute(XXX)`...

**Comment by helderco** [comment]
This has been addressed in:
- #6326
