### ISSUE TITLE
Using search in docs could take you to an old version of docs

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#4211]
### What is the issue?

1 - Go to docs.dagger.io
2 - Search for the term "socket" and select the second result
3- This will take you to https://docs.dagger.io/1203/client/#using-a-local-socket which is the old CUE documentation that changes the sidebar navigation which results very confusing.

not sure how many other search terms could also trigger the bug.

**Comment by slumbering** [comment]
Good catch Marcos ! We're using caution "abdonition" to tell users about documentation version:
![Capture d’écran 2022-12-19 à 10 01 52](https://user-images.githubusercontent.com/1186424/208387734-214c4695-bbd5-4d90-ba3b-d8ed095d02ea.png)

The problem with that is users can miss it because on top of the page. 
So we can see two approach here:
- Tweak Algolia to not parse deprecated documentation
- Instead of having an "abdonition" we could display a sticky banner that is always visible to users and tell them when the current page is about deprecated docs.

**Comment by marcosnils** [comment]
> The problem with that is users can miss it because on top of the page.

this. It's exactly what happened to me. I didn't realize I was looking at old docs until I saw the sidebar completely changed.

> * Tweak Algolia to not parse deprecated documentation

Maybe instead of removing it altogether put it in a different section under `cue sdk`? 

![image](https://user-images.githubusercontent.com/1578458/208465766-fbf7947e-1039-42cc-b2c1-0c431731b104.png)

> * Instead of having an "abdonition" we could display a sticky banner that is always visible to users and tell them when the current page is about deprecated docs.

Yep, this could work.

**Comment by gerhard** [comment]
Yes, that is a good idea. Our Docsearch integration is only basic, there is a lot that we can do to improve it. Want to look into it @vikram-dagger?

**Comment by samalba** [comment]
Assigning this to Vikram. No priority yet. Feel free to set a priority if it fits your short term backlog @vikram-dagger

**Comment by vikram-dagger** [comment]
Resolved in https://github.com/dagger/dagger/issues/4304
