### ISSUE TITLE
Single-track docs

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#4291]
Following up on https://github.com/dagger/dagger/discussions/4213, the goal is to come up with a unified multi-language "getting started" single-track flow that can be consumed by all Dagger developers regardless of language and SDK. Ideally across all guides, and API reference too.

References: 

- [NextJS learn experience](https://nextjs.org/learn/foundations/about-nextjs?utm_source=next-site&utm_medium=homepage-cta&utm_campaign=next-website).
- [GraphQL learn](https://graphql.org/learn/queries/) interactive queries.
- [Twilio docs](https://www.twilio.com/docs/sms/quickstart/go)
 
List of topics, ideas and objectives to explore: 

- A "flow" which covers the basic operations like build, push, export, etc and understand where the user drops in it
- A place where we can highlight patterns and recommended examples on how to accomplish generally repeated questions in Discord. i.e: how to run `docker-compose` services in my Dagger pipelines?
- Avoid having duplicated information in multiple places (examples)
- Make sure our examples and guides are always compliant with the latest released engine

I think this is a good place to start. @shykes @samalba @jpadams @vikram-dagger anything to add here?

Tasks

```[tasklist]
### Quickstart MVP
- [x] #4324
- [x] #4325
- [x] https://github.com/dagger/dagger.io/pull/1423
- [x] #4354
- [x] #4355
- [x] #4356
- [x] #4357
- [x] #4358
- [x] https://github.com/dagger/dagger.io/issues/1454
- [x] #4453
- [ ] #4479
```

```[tasklist]
### Follow-up on Quickstart MVP
- [ ] #4419 
- [ ] https://github.com/dagger/dagger/issues/4504
- [ ] https://github.com/dagger/dagger.io/issues/1686
```
```[tasklist]
### Guides Centralization
- [ ] https://github.com/dagger/dagger/issues/4571
```

```[tasklist]
### Curated API Reference
```

**Comment by shykes** [comment]
Sounds great to me 👍

Follow-up questions:

- What happens to the current set of guides? Can they be converted to be single-track too? Or would they co-exist with new single-track guides?

- This overlaps with https://github.com/dagger/dagger/issues/3909, can we close one?

**Comment by marcosnils** [comment]
> * What happens to the current set of guides? Can they be converted to be single-track too? Or would they co-exist with new single-track guides?
> *

We'll try to convert them to single track as well. We'll see how it goes from there.

**Comment by vikram-dagger** [comment]
We can either follow the Twilio approach where they have one guide for each language  or something like the stripe docs where they have a language selector (https://stripe.com/docs/checkout/quickstart). 

I was thinking about this today. Here's my initial proposal:

1. Create a common quickstart like Stripe has at https://stripe.com/docs/checkout/quickstart, with a language selector.
- Currently all the quickstarts are different, so we need to identify a common example that we want to use and then build the code for each language. Any input on this @jpadams @kpenfound?
- This common quickstart will live as a top level menu item in the docs nav tree.

2. Transition the existing "get started" guides to regular guides - two options here.

2a. They stay language-specific.
- They are listed in the `Guides` page for each SDK eg. https://docs.dagger.io/sdk/nodejs/947203/guides
- The "get started" menu item for each SDK section now points to the top level quickstart with the correct language preselected.

2b. They become multi-language.
- The language-specific tutorials now change to have tabs and code for each language SDK: `Go`, `Python`, `Javascript (ESM)`, `Javascript (CJS)`, `Typescript`, `CLI`. Some tutorials may get merged as a result of this eg. https://docs.dagger.io/560223/private-repositories and https://docs.dagger.io/sdk/go/710884/private-repositories
- We add a new `Tutorials` page in the docs. This page becomes a rolling index of all tutorials.
- We remove the language-specific SDK `Guides` page and add redirects (if needed).
- To some extent, this imposes a requirement that all new tutorials are multi-language. 

I also think we need to do this sequentially - complete (1) first to test the hypothesis that multi-language is actually the preferred choice for users and then consider whether or not to proceed with (2).

**Comment by marcosnils** [comment]
> 1. Create a common quickstart like Stripe has at https://stripe.com/docs/checkout/quickstart, with a language selector.

+1. Aligned to what we spoke


> 3\. Transition the existing "get started" guides to regular guides - two options here.

I'd go with 2b if we like the out come of 1.

> I also think we need to do this sequentially - complete (1) first to test the hypothesis that multi-language is actually the preferred choice for users and then consider whether or not to proceed with (2).

Agree. Let's iterate first with 1 to see how it feels and then go to 2.

**Comment by helderco** [comment]
At first I felt we needed to have both: general multi-language guides, but also guides that are specific to an SDK's community like building a Go binary or publishing a Python package.

However, it's entirely possible that the pipeline author is not the same as the code's owner. So in fact there's value in having a Go SDK example publishing a Python package (like in our own dogfood!), or a NodeJS SDK example building a Go binary.

**Comment by kpenfound** [comment]
> Currently all the quickstarts are different, so we need to identify a common example that we want to use and then build the code for each language

I think for this kind of catch-all multilanguage guide, we should optimize for simple and relatable. We could clone, test, and build the dagger repo for example

**Comment by helderco** [comment]
Or replacing a Dockerfile like we did in [Building Container Images](https://docs.dagger.io/sdk/cue/457544/container-images#specifying-a-build-in-cue) 😁

**Comment by marcosnils** [comment]
> However, it's entirely possible that the pipeline author is not the same as the code's owner. So in fact there's value in having a Go SDK example publishing a Python package (like in our own dogfood!), or a NodeJS SDK example building a Go binary.

exactly.. :wink:.

**Comment by vikram-dagger** [comment]
> > Currently all the quickstarts are different, so we need to identify a common example that we want to use and then build the code for each language
> 
> I think for this kind of catch-all multilanguage guide, we should optimize for simple and relatable. We could clone, test, and build the dagger repo for example

I agree we should clone, test and build a repo (I'm not sure if it's the dagger repo or something else) but we should also add turning that build into a container and publishing it to a registry.

**Comment by marcosnils** [comment]
> I agree we should clone, test and build a repo (I'm not sure if it's the dagger repo or something else) but we should also add turning that build into a container and publishing it to a registry.

Yes, we can use https://ttl.sh/ as a test registry for that

**Comment by crjm** [comment]
>     1. Create a common quickstart like Stripe has at https://stripe.com/docs/checkout/quickstart, with a language selector.
 
Besides Stripe's model (a global lang selector), we can also use a per-snippet lang selector that modifies the state globally (all examples would inherit that lang as well). This is a matter of UX and opinions, as we don't have any evidence on which alternative is best. **[Example here](https://www.pulumi.com/docs/get-started/azure/deploy-stack/)**.
One downside of the Stripe implementation is that, after scrolling, the lang selection stays on top.

>     2. Transition the existing "get started" guides to regular guides - two options here.
>     * 2a. They stay language-specific.
>     * 2b. They become multi-language.

The problem with 2b is that centralizing guides (multi-lang) makes them less flexible. Maybe there will be SDK specific content that's not compatible with another SDK. Guide centralization is broader in scope than snippet centralization, so it will take longer to ship new iterations (content for all langs will have to be ready in order to ship a guide). I prefer 2a for now, and in case we decide to go for a 2b, the implementation should be different from 1, by making the whole guide a new page with SDK specific content, and not just the snippets.

At the same time, with 2b we make sure: 
- To avoid guide content duplication (big chunks of a guide written twice or more just because they are different languages).
- That all SDKs will have the same amount of coverage. By fragmenting guides, one SDK will have more content than the others, or cover different tasks that other SDKs don't cover.

**Comment by marcosnils** [comment]
> Besides Stripe's model (a global lang selector), we can also use a per-snippet lang selector that modifies the state globally (all examples would inherit that lang as well). This is a matter of UX and opinions, as we don't have any evidence on which alternative is best.

+1. As we spoke today Julián, whatever is simpler to implement so we can ship and iterate.

**Comment by vikram-dagger** [comment]
While working on the content for #4354 , and knowing that @marcosnils has a plan to allow SDK code snippets to be run interactively via the API Playground, I was wondering about switching the structure from:
- a single-page guide to a multi-step guide
- static code snippets to an interactive console (building further on the existing idea of embedding a code-driven API Playground into the docs)

I’ve described the idea I was experimenting with as a mockup in https://docs.google.com/document/d/1UH0xHjPgOg4aqU9o5KLBmXM56hQE_xP0Q6K_MZq8ilI/edit?usp=sharing and am interested in getting feedback on the following: 

- The idea in general, plus any refinements or improvements.
- This would be almost like a standalone Web app/code lab that we launch from docs (“Learn Dagger”). The effort required to implement on the browser/UX side is non-trivial, so team bandwidth will be an issue. Maybe this is a reason to implement it later as quickstart v2?
- The later examples may include cloning a repository and publishing to a registry. How do we manage the security risks associated with allowing this functionality, considering this will be an interactive console?

Of course, if the general consensus is that this is not feasible for various reasons right now, the same content can be easily repurposed to a single-page quickstart guide (similar to others already present in the docs).

**Comment by marcosnils** [comment]
> * This would be almost like a standalone Web app/code lab that we launch from docs (“Learn Dagger”). The effort required to implement on the browser/UX side is non-trivial, so team bandwidth will be an issue. Maybe this is a reason to implement it later as quickstart v2?

^^ this. @shykes particularly highlighted to do this as incremental as possible. Doing this multi-step approach is something like it'll surely require more effort. I'd like to see if we can approach it in an iterative fashion eventually, but I wouldn't change the approach now.

**Comment by crjm** [comment]
After discussing with @samalba and @marcosnils, the next step is to research and implement a better layout for the Quickstart page, instead of using the default Docusaurus one. For this I'll create an issue to keep track of benchmarked sites and decisions regarding the new layout.
cc @vikram-dagger

**Comment by vikram-dagger** [comment]
@marcosnils there are 4 pages in the quickstart containing embeds which, on page load, automatically build and publish the app to ttl.sh. I'm concerned that there is a risk ttl.sh will blacklist us for abuse if they see a high volume of uploads being generated from our docs. Do you think this is a valid concern?

I've checked ttl.sh docs, there is no mention of a limit but I'm sure that once people start using our quickstart, the load will become increasingly visible to the ttl.sh operator. If you agree this could be an issue, I feel like we should get ahead of this problem, by adjusting the design of our embeds to only run the code if a user clicks a button and/or reaching out to ttl.sh to check if this will create an issue and how we can work with them to mitigate it.

**Comment by marcosnils** [comment]
> @marcosnils there are 4 pages in the quickstart containing embeds which, on page load, automatically build and publish the app to ttl.sh. I

@vikram-dagger embeds don't execute the code upon load. Output is cached and retrieved from the API. Output is only re-computer if the user presses the play buttom.

**Comment by shykes** [comment]
Checking in, what's the status on this overall?

* What are steps left to ship the first step "single-track quickstart"
* What are the steps after that to get to a complete "single track docs"?

**Comment by marcosnils** [comment]
> * What are steps left to ship the first step "single-track quickstart"

Shipped already. Told @mircubed about it yesterday.

> * What are the steps after that to get to a complete "single track docs"?

Basically the ones described here: https://github.com/dagger/dagger/discussions/4213. Next on the list would be "Move all the guides into a centralized "blogpost" like format that can be filtered by tags and ordered by publish date". We need to sync with @vikram-dagger about it.

**Comment by marcosnils** [comment]
I'm assigning this to @vikram-dagger as we spoke with @samalba

**Comment by crjm** [comment]
As discussed with @vikram-dagger today: after the layout is finished, we are going to focus primarily on the guide centralization aspect and discuss it here. We agreed on making a new issue, but this one seems to fit our needs, as the guides were also mentioned here.
@vikram-dagger Feel free to create a new one if you think otherwise!

**Comment by shykes** [comment]
Have you looked at how to unify the API reference too? It would be really nice... The famous Stripe docs are fundamentally a reference doc, but in a narrative format grouped by topic, with examples. Note: their examples are not directly runnable... but still useful :)

**Comment by shykes** [comment]
Let's talk about this more. From the very beginning, when I talked about "single-track docs" it was specifically in reference to [this Stripe documentation](https://stripe.com/docs/api). I bring up that particular doc literally in every live conversation about this topic. Until just now, I assumed you guys were working on a way to build that, and the quickstart guide was just a first step in your master plan. It looks like I completely misunderstood what the plan is?

> it would involve a lot of engineering time as all the references are generated with different tools. At the top of my head, it would involve exporting all different SDKs types to a common format that can be consumed by Docusarus. I will create an issue to research a possible way to do it (Dagger maybe).

I see what you mean, but perhaps there is another way? That Stripe doc is indeed a "reference", but is quite different from a standard generated API reference, like the ones we have. Its structure follows a narrative flow, that seems to be manually created. It's almost like a concepts guide, but much more thorough, and organized around a systematic exploration of all the things the API can do. We could really use one of those...

wdyt @vikram-dagger ?

**Comment by shykes** [comment]
By the way I fully support the plan of merging our existing collection of guides into a single-track collection. That is also much needed. Hopefully I understood that part of the plan correctly?

**Comment by crjm** [comment]
> Let's talk about this more. From the very beginning, when I talked about "single-track docs" it was specifically in reference to [this Stripe documentation](https://stripe.com/docs/api). I bring up that particular doc literally in every live conversation about this topic. Until just now, I assumed you guys were working on a way to build that, and the quickstart guide was just a first step in your master plan. It looks like I completely misunderstood what the plan is?

My bad, as soon as I read "reference" I automatically thought of a generated reference with no explanatory content at all and started thinking of an implementation.

For the single-track **quickstart**, we were referring to [this quickstart format](https://stripe.com/docs/checkout/quickstart), to ship something fast and impactful that does not require moving outside Docusaurus. The discussion for this took place [here](#4419).

As for the implementation of the single-track **docs** (bigger in scope and content than the quickstart), I think we still have a long way to go, although we did gain something after implementing the new Quickstart layout as the implementation is somewhat similar. 
What we discussed today with @vikram-dagger is to keep producing content in order to have enough material to implement a documentation like the Strapi API or even other ideas that we brainstormed. Please, correct me if I'm wrong @vikram-dagger.

> By the way I fully support the plan of merging our existing collection of guides into a single-track collection. That is also much needed. Hopefully I understood that part of the plan correctly?

Yes. The main focus here is to keep all guides together in the same index page, with the option to filter them by tags or another attribute and, instead of having guides separated by SDK, reuse content by making them single-track. Of course, some guides (such as deploying to X service) will not benefit from the embedded Playground as they need sensitive information to be executed, and instead, they will have static snippets like they do now.

**Comment by shykes** [comment]
> Of course, some guides (such as deploying to X service) will not benefit from the embedded Playground as they need sensitive information to be executed, and instead, they will have static snippets like they do now.

Can those static snippets be made multi-language too, like in the Stripe docs? "Multi-language" and "runnable in playground" ideally would be orthogonal.

**Comment by crjm** [comment]
> Can those static snippets be made multi-language too, like in the Stripe docs? "Multi-language" and "runnable in playground" ideally would be orthogonal.

Yep, that's the idea. We want to make the snippets multi-language so each guide can be single-track like the Strapi API docs. You can think of the current Quickstart as "the first single-track guide". We want to extrapolate that same format to the guides we think are worth having in all SDKs.
What we are missing for this is basically the content and some tweaks in the front-end implementation. For example, we already have the content in [Go](https://docs.dagger.io/sdk/go/710884/private-repositories/), [JS](https://docs.dagger.io/560223/private-repositories) and [Python](https://docs.dagger.io/683293/private-repositories) to make a single track guide of "Use Dagger with Private Git Repositories", but we don't have the content to make one about "Work with the Host Filesystem", as it's [only been written in Go](https://docs.dagger.io/421437/work-with-host-filesystem).

**Comment by vikram-dagger** [comment]
> I see what you mean, but perhaps there is another way? That Stripe doc is indeed a "reference", but is quite different from a standard generated API reference, like the ones we have. Its structure follows a narrative flow, that seems to be manually created. It's almost like a concepts guide, but much more thorough, and organized around a systematic exploration of all the things the API can do. We could really use one of those...
> 
> wdyt @vikram-dagger ?

I believe we attempted a similar narrative style with https://docs.dagger.io/api/975146/concepts. We could definitely extend that to cover more of the API in a sequential format, accompanied with multi-language code embeds. 

> Can those static snippets be made multi-language too, like in the Stripe docs? "Multi-language" and "runnable in playground" ideally would be orthogonal.

Yes. The idea would be to default to all guides having multi-language snippets, except in cases where it obviously doesn't make sense due to the specific topic or example. We would need to create the code for many of them, since most of them are single-language right now. In some cases, the snippets would be static and in others, interactive playground embeds, depending on whether or not the code can run successfully without external deps (like user credentials or third-party services).

**Comment by marcindulak** [comment]
Quoting the initial issue:

> Make sure our examples and guides are always compliant with the latest released engine

How will this be achieved? Will the examples/guides be always latest-only https://github.com/dagger/dagger/issues/4573?

**Comment by vikram-dagger** [comment]
> How will this be achieved? Will the examples/guides be always latest-only #4573?

Yes, that's the current plan.

**Comment by marcindulak** [comment]
> Quoting the initial issue:
> 
> > Make sure our examples and guides are always compliant with the latest released engine
> 
Are there already plans how will the guides be technically kept in sync with the releases?

**Comment by vikram-dagger** [comment]
> Are there already plans how will the guides be technically kept in sync with the releases?

Code examples used in the docs are tested by the CI as part of the normal PR tests.

**Comment by gerhard** [comment]
These looks like an epic which would be better suited for Linear. Sub-issues sound great!

Do you think that we can close this @vikram-dagger? Most of the tasks are done (13/15) and it's been **In Progress** for many months now.

**Comment by vikram-dagger** [comment]
In summary:
- The quickstart has multi-language code snippets.
- All guides have multi-language code snippets
- We do not yet have a "single-track" or "unified" API/SDK reference (https://github.com/dagger/dagger/issues/4291#issuecomment-1424950766)
- Quickstart snippets are embedded and runnable via the Playground
- Most guide snippets are not embedded or runnable via the Playground, typically because they have external dependencies/configuration/setup requirements.

https://github.com/dagger/dagger/issues/4504 is IMHO not required any longer, as we do not regenerate the quickstart embeds frequently enough to justify investing time in an automation script.

https://github.com/dagger/dagger/issues/4571 has been closed separately with reasons for the individual sub-tasks.

I am fine with closing this parent but would like to retain an issue for the requirement of having "single track" API/SDK docs so that we don't lose track of it.

The discussion regarding 

Considering the above points, we can close this, with the option to reopen in future if needed.

**Comment by helderco** [comment]
> I am fine with closing this parent issue but would like to retain an issue for the requirement of having "single track" API/SDK docs so that we don't lose track of it.

Does it need to be on GH or can you track it in Linear?

**Comment by vikram-dagger** [comment]
> > I am fine with closing this parent issue but would like to retain an issue for the requirement of having "single track" API/SDK docs so that we don't lose track of it.
> 
> Does it need to be on GH or can you track it in Linear?

Linear is fine.

**Comment by gerhard** [comment]
Closing this here, and moving the remainder in Linear sounds great to me!

**Comment by gerhard** [comment]
Closing this now, please move to Linear if necessary @vikram-dagger.
