### ISSUE TITLE
Docs search sometimes sends to old docs

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#4304]
Sometimes when using the search feature in [the Dagger docs](https://docs.dagger.io), some results will send to a different, older documentation site. This is confusing because the design is similar, but the navigation bar is different; and there is no warning or explanation.

To reproduce:

1. Go to [the Dagger docs](https://docs.dagger.io)
2. Search for "platform"
3. Click the second result called "push multi-platform"

See screenshot:

## Before clicking search result

<img width="1096" alt="Screen Shot 2023-01-04 at 10 51 06 AM" src="https://user-images.githubusercontent.com/29565/210628119-0122cc62-4b0f-49bf-b8d3-f32fa0707beb.png">

## After clicking search result

<img width="967" alt="Screen Shot 2023-01-04 at 10 53 12 AM" src="https://user-images.githubusercontent.com/29565/210628457-0973dab0-6bbe-404e-bbe7-94294d614cd9.png">

**Comment by vikram-dagger** [comment]
The target page does have a warning at the top, but since the search result points to an internal heading, the warning is not visible. 

As a short term fix, I think it makes sense to change the indexing to only index the current docs.

As a longer term fix, we can check if it's possible to add a label to index entries for the older find like "deprecated" or similar and have this label appear in the search results drop down for older pages.

**Comment by slumbering** [comment]
Yes, this problem is recurrent. Regarding the short term fix that Vikram is proposing we are currently using Algolia crawler `exclusionPatterns` to remove Dagger 0.1 indexation :

![image](https://user-images.githubusercontent.com/1186424/211018830-12513989-1ad4-4a90-b380-86338729709d.png)

If we want to ignore Dagger 0.2 docs we'll need to list every url (thanks to [the sitemap.xml](https://docs.dagger.io/sitemap.xml) ?) which is:
- super tedious
- error prone

Regarding longer term fix I don't know about adding labels to index for old entries and what amount of efforts we need.
I quite like the Docusaurus approach that takes snapshot for older version : 
https://6310933e91a4590008bcd3ee--docusaurus-2.netlify.app/docs/2.0.0-rc.1
Those snapshot are not indexed by Algolia crawler and they should not be indexed from search engine (https://www.tempertemper.net/blog/stop-search-indexing-for-netlify-deploy-previews-and-branch-deploys).
Another benefit I see is to clean up our current main repo by removing old markdowns to just keep the latest docs.

**Comment by marcosnils** [comment]
Also related: #4211

**Comment by vikram-dagger** [comment]
As a short-term measure, I have excluded the 0.2 docs from the search index. 0.1 docs were already excluded earlier. Here is the list of excluded URLs:

```
    "https://docs.dagger.io/0.2",
    "https://docs.dagger.io/dgr18/overview",
    "https://docs.dagger.io/1242/install",
    "https://docs.dagger.io/f44rm/how-it-works",
    "https://docs.dagger.io/1200/local-dev",
    "https://docs.dagger.io/1201/ci-environment",
    "https://docs.dagger.io/1220/vs",
    "https://docs.dagger.io/1221/action",
    "https://docs.dagger.io/1202/plan",
    "https://docs.dagger.io/1203/client",
    "https://docs.dagger.io/1204/secrets",
    "https://docs.dagger.io/1215/what-is-cue/",
    "https://docs.dagger.io/1247/dagger-fs",
    "https://docs.dagger.io/1228/handling-outputs",
    "https://docs.dagger.io/1231/always-execute",
    "https://docs.dagger.io/1233/default-values-cue",
    "https://docs.dagger.io/1239/making-reusable-package",
    "https://docs.dagger.io/1240/core-source",
    "https://docs.dagger.io/1241/field-shadowing",
    "https://docs.dagger.io/1223/custom-buildkit/",
    "https://docs.dagger.io/1224/self-signed-certificates/",
    "https://docs.dagger.io/1229/empty-buildkit-cache",
    "https://docs.dagger.io/1237/persistent-cache-with-dagger",
    "https://docs.dagger.io/1230/better-logs",
    "https://docs.dagger.io/1243/dagger-cloud",
    "https://docs.dagger.io/1205/container-images",
    "https://docs.dagger.io/1225/pushing-plan-dependencies/",
    "https://docs.dagger.io/1232/chain-actions",
    "https://docs.dagger.io/1238/project-file-organization",
    "https://docs.dagger.io/1244/docker",
    "https://docs.dagger.io/1246/go-ci",
    "https://docs.dagger.io/4dhu9/api-customizable-image",
    "https://docs.dagger.io/1216/docker-cli-load",
    "https://docs.dagger.io/1217/docker-cli-run",
    "https://docs.dagger.io/1214/migrate-from-dagger-0.1",
    "https://docs.dagger.io/1218/cli-telemetry",
    "https://docs.dagger.io/1227/contributing",
    "https://docs.dagger.io/1226/coding-style",
    "https://docs.dagger.io/1222/core-actions-reference",
    "https://docs.dagger.io/1234/dagger-types-reference",
    "https://docs.dagger.io/13ec8/dagger-env-reference",
    "https://docs.dagger.io/category/use-cases",
    "https://docs.dagger.io/1211/go-docker-swarm",
    "https://docs.dagger.io/1219/go-docker-hub",
    "https://docs.dagger.io/1245/node-ci",
    "https://docs.dagger.io/1248/aws-sam",
```

After recrawling, Algolia notes that the index cannot be replaced automatically due to the large delta and requests confirmation:

![Image](https://user-images.githubusercontent.com/112123850/214536505-bad1cbc7-8532-4127-89fe-a9e23f08d3e0.png)

I believe this is fine, lmk if you disagree @gerhard

**Comment by vikram-dagger** [comment]
> This looks good, we are just missing a few URLs - the 3 green lines on the left-hand side:
> Is this intentional?

Not exactly. I generated my list by crawling the 0.2 docs sidebar. These links are not present in it, hence didn't make it to my list. Checking further as to why, I see that the first two are empty pages (maybe placeholders which didn't get filled?) and the third has content related to the Dagger CUE API (I'm not sure why this wasn't linked). In any case, for completeness I'm adding these to the exclusion list in the crawler. Thank you very much for picking them up!

> I am assuming that we want to exclude `/category/use-cases` from the search results (green line on the right-hand side)

Yes, I think so.

I'll go ahead and make these changes and rebuild the index. Thanks again for the double check!

**Comment by vikram-dagger** [comment]
After reindexing, the original issue does not recur. Only a single search result entry appears for "platform" and points to the current docs.

![image](https://user-images.githubusercontent.com/112123850/214593582-13a076ad-45a3-4643-a370-008ca63eb932.png)

**Comment by gerhard** [comment]
Looking great @vikram-dagger 👍
