### ISSUE TITLE
Write common quickstart guide

### ISSUE THREAD

**Issue by vikram-dagger** [dagger/dagger#4354]
Create the structure and text for the common quickstart guide.

**Comment by marcosnils** [comment]
Hey @vikram-dagger! I finally had a call with @kpenfound about this. Here's the outcome list of the things are worth taking into account for this common quickstart guide: 

- Try to use an existing codebase for the getting started flow. Picking an example from https://github.com/dagger/examples could be an option since we generally try to keep those updated.
- Avoid cloning the repo withing Dagger from scratch, since users generally need to understand the `Host` API to try Dagger in their projects. 
- Try to come up with a basic example project that involves a front-end and a back-end where users could easily re-use whatever part they need for their usecase.
- Try to show case the most asked Discord questions like: registry auth, multi-stage builds, include/exclude files, build from Docekrfile, etc. Start with the basics so users can grasp the way of doing things "the dagger" way.
- Kyle mentioned that he really liked the way Hashicorp has its "getting started" tutorials (https://developer.hashicorp.com/vault/tutorials/getting-started) where you start with the basic steps but you can easily branch-out to more comprehensive examples easily
- Assume that users already have understanding about containers. We don't need to explain everything from scratch.

LMK if we're good with this to start Vikram.

**Comment by slumbering** [comment]
> Assume that users already have understanding about containers. We don't need to explain everything from scratch.

Or at least redirect them to a source where containers are explained (docker website, etc.)

> Try to show case the most asked Discord questions like: registry auth, multi-stage builds, include/exclude files, build from Docekrfile, etc. Start with the basics so users can grasp the way of doing things "the dagger" way.

+1

**Comment by vikram-dagger** [comment]
>     * Try to use an existing codebase for the getting started flow. Picking an example from https://github.com/dagger/examples could be an option since we generally try to keep those updated.

I saw a couple of Node.js Web app examples in that repository. I think those could be good candidates. However I'm not sure if we want the codebase to be in one of our languages (Go/Node/Python) or if it's better for it to be a completely different language (Spring Framework/C++?) to showcase that the app and the Dagger pipeline need not be in the same language.

>     * Try to come up with a basic example project that involves a front-end and a back-end where users could easily re-use whatever part they need for their usecase.

Can you explain this? I assume you mean an API and a front-end app that uses it? If so, do you mean that the example Dagger pipeline would produce and publish two containers, one each for the above?

**Comment by jpadams** [comment]
> > Assume that users already have understanding about containers. We don't need to explain everything from scratch.
> 
> Or at least provide a link to a source where containers are explained (docker website, etc.)?
> 
> > Try to show case the most asked Discord questions like: registry auth, multi-stage builds, include/exclude files, build from Docekrfile, etc. Start with the basics so users can grasp the way of doing things "the dagger" way.
> 
> +1

Need to incorporate how building query vs actually getting it to run works too. Important thing that bites a lot of new Dagger users.

https://github.com/dagger/dagger/issues/3617

**Comment by marcosnils** [comment]
> I saw a couple of Node.js Web app examples in that repository. I think those could be good candidates. However I'm not sure if we want the codebase to be in one of our languages (Go/Node/Python) or if it's better for it to be a completely different language (Spring Framework/C++?) to showcase that the app and the Dagger pipeline need not be in the same language.

Even though I'd love to have an example from a different language that the ones there (maybe we can make it a guide), a good benefit of using the official examples is that we can be almost sure that they'll follow the best practices and probably incorporate the latest changes in the API spec. So it'll be very convenient for new users to start from that repo since they'll have a handful set of real cases to take inspiration or copy from.

**Comment by marcosnils** [comment]
> I assume you mean an API and a front-end app that uses it? I

Yes, correct. A pipeline that builds both an API and a front-end.

> If so, do you mean that the example Dagger pipeline would produce and publish two containers, one each for the above?

Well. Front-ends are not generally published in containers so if we have a pipeline that can depoy to netlify or vercel that'd be awesome. How are he showcasing this today @kpenfound @jpadams ?

**Comment by marcosnils** [comment]
> Need to incorporate how building query vs actually getting it to run works too. Important thing that bites a lot of new Dagger users.

:pray:

**Comment by vikram-dagger** [comment]
> Need to incorporate how building query vs actually getting it to run works too. Important thing that bites a lot of new Dagger users.
> 
> #3617

We have this: https://docs.dagger.io/api/975146/concepts#lazy-evaluation

**Comment by marcosnils** [comment]
> We have this: https://docs.dagger.io/api/975146/concepts#lazy-evaluation

Yep, it'd be a similar doc but a bit more high level so users using the SDK understand how that translates to code.

**Comment by kpenfound** [comment]
> Front-ends are not generally published in containers so if we have a pipeline that can depoy to netlify or vercel that'd be awesome. How are he showcasing this today

Here's one example that I show a lot: https://github.com/kpenfound/hello-nomad/blob/main/ci/utility/deploy.go#L100-L119

**Comment by marcosnils** [comment]
> Here's one example that I show a lot: https://github.com/kpenfound/hello-nomad/blob/main/ci/utility/deploy.go#L100-L119

Great! thx Kyle! cc @vikram-dagger

**Comment by vikram-dagger** [comment]
@marcosnils following up on our call yesterday, I propose the following structure and flow:

- Use a standard react app as the base example: I have created one at https://github.com/vikram-dagger/hello-dagger which can be later moved to a repo under dagger/*
- Step 1: install sdk
- Step 2: simple "hello" client
- Step 3: create test pipeline -> clone the git repo above, npm install, npm run test
- Step 4: create build pipeline -> above steps + npm run build, export build/ directory to host
- Step 5: create publish pipeline -> use nginx:alpine container, copy build directory from previous container to nginx root (opportunity to demo multi-stage build), publish to temp registry -> user can now test with docker run 

Please let me know your feedback.

**Comment by marcosnils** [comment]
> Please let me know your feedback.

Awesome Vikram, looking good. Yesterday we spoke about adding a Dockerfile to the repo so we can also showcase the alternative way of using the Dockerifle with Dagger. Are we still on track here?

---

@jpadams @kpenfound what do you think about this getting started flow? Are we missing anything?

**Comment by vikram-dagger** [comment]
> > Please let me know your feedback.
> 
> Awesome Vikram, looking good. Yesterday we spoke about adding a Dockerfile to the repo so we can also showcase the alternative way of using the Dockerifle with Dagger. Are we still on track here?

I thought about this a lot, but I'm slightly concerned it (1) breaks the flow above. Also, (2) we already have a separate guide on replacing a Dockerfile with Go and (3) the default React app skeleton doesn't include a Dockerfile so we will need to create our own. 

I would like to think about/discuss this one a bit more and work on it last, after the PR is almost complete.

**Comment by marcosnils** [comment]
> I thought about this a lot, but I'm slightly concerned it (1) breaks the flow above. Also, (2) we already have a separate guide on replacing a Dockerfile with Go and (3) the default React app skeleton doesn't include a Dockerfile so we will need to create our own.

Agree as we talked yesterday. Let's start without it and see how it flows from there

**Comment by jpadams** [comment]
> > Please let me know your feedback.
> 
> Awesome Vikram, looking good. Yesterday we spoke about adding a Dockerfile to the repo so we can also showcase the alternative way of using the Dockerifle with Dagger. Are we still on track here?
> 
> @jpadams @kpenfound what do you think about this getting started flow? Are we missing anything?

The simple approach to start makes sense, but I agree, it would be cool to add a Dockerfile at some point. The reason is that lots of teams have Dockerfiles and if we can show them an easy way to both write something from scratch as well as seamlessly incorporate the Dockerfiles they already have, I think that would be seen as a win. Alternatively, you could make this a "side quest" in the main flow. Love what y'all are doing! <3

**Comment by vikram-dagger** [comment]
> > Awesome Vikram, looking good. Yesterday we spoke about adding a Dockerfile to the repo so we can also showcase the alternative way of using the Dockerifle with Dagger. Are we still on track here?
> 
> The simple approach to start makes sense, but I agree, it would be cool to add a Dockerfile at some point. The reason is that lots of teams have Dockerfiles and if we can show them an easy way to both write something from scratch as well as seamlessly incorporate the Dockerfiles they already have, I think that would be seen as a win.

OK, so I've now added this at a different point in the sequence. LMK what you think!

**Comment by vikram-dagger** [comment]
>     * Avoid cloning the repo withing Dagger from scratch, since users generally need to understand the `Host` API to try Dagger in their projects. We think it might be better cloning the repo outside dagger.

Done
 
>     * Try to come up with a basic example project that involves a front-end and a back-end where users could easily re-use whatever part they need for their usecase.

We are using a front-end app only. I don't know if adding one more variable (back-end app) is a good idea for a starter tutorial. 
 
>     * Try to show case the most asked Discord questions like: registry auth, multi-stage builds, include/exclude files, build from Docekrfile, etc. Start with the basics so users can grasp the way of doing things "the dagger" way.

All the above topics are now covered in the quickstart!

**Comment by marcosnils** [comment]
this is finally done :tada: 

Awesome work Vikram!
