### ISSUE TITLE
✨ GraphQL API: Enable tabs in Dagger Playground

### ISSUE THREAD

**Issue by d3rp3tt3** [dagger/dagger#4457]
### What are you trying to do?

GraphiQL supports tabs: https://github.com/graphql/graphiql/releases/tag/graphiql%401.8.0. 

[Here's a tabs demo in action](https://graphql.org/swapi-graphql?).

### Why is this important to you?

Enabling tabs would provide a great user experience for testing the GraphQL API. Rather than putting multiple operations into one tab and then clicking the Play button to select the operation to run, you could enter each operation on its distinct tab.

### How are you currently working around this?

I put multiple operations in a single tab today.

**Comment by shykes** [comment]
We had tabs enabled originally, but there was confusion on how it interacted with 1) our sharing feature, and 2) persistence in the browser

Let's say you create 4 tabs, each with their own queries. Tabs are persisted in local storage, so every time you open a browser tab, you see all 4. Now you click the "share" button and get a URL. Should that URL contain all 4 tabs also? Or did you mean to share the current tab? Since the tabs are persisted in your browser, acting as your personal "collection", presumably you want to share only one tab - unfortunately that requires deeper integration with GraphiQL, and instead the URL will share all 4 tabs. Hence the confusion.

When we faced this dilemma, we decided to ship a "good enough" version in the short term, and later take the time to engineer a deeper integration with GraphiQL, to further refine the UX.

Let me know if I missed anything @marcosnils @crjm @Camile-Elairin

**Comment by marcosnils** [comment]
> Let me know if I missed anything @marcosnils @crjm @Camille-Elairin @slumbering

nope, that's pretty much it. TBH I personally don't see a huge  advantage over having multiple vs multiple queries at this moment. Sure, you have the queries organized differently, but since you can do query folding in the editor, we're not particularly missing any great valuable feature.

**Comment by d3rp3tt3** [comment]
Apollo Studio handles this by permitting sharing of each tab distinctly. It is very useful for creating documentation collections, too.

<img width="500" alt="Screen Shot 2023-01-26 at 3 34 16 PM" src="https://user-images.githubusercontent.com/1811126/214944600-43aaa4a4-309d-4081-bd9a-8f0f99d323f7.png">

https://studio.apollographql.com/public/apollo-platform/explorer?variant=main

**Comment by marcosnils** [comment]
> Apollo Studio handles this by permitting sharing of each tab distinctly. It is very useful for creating documentation collections, too.

awesome! thx for sharing. Definitely source of inspiration. cc @crjm

**Comment by samalba** [comment]
Closing this. Belongs to internal tracker.
