### ISSUE TITLE
Duplicate log messages

### ISSUE THREAD

**Issue by dubo-dubon-duponey** [dagger/dagger#449]
This will naturally run only once ("echo LOL" one time):

```
foo: #up: [
    op.#DockerBuild & {
        dockerfile: """
            FROM dubodubonduponey/debian
            ARG TARGETPLATFORM
            RUN echo LOL $TARGETPLATFORM
        """
    },
]
```

This will run twice (echo LOL multiple times):

```
foo: #up: [
    op.#DockerBuild & {
        dockerfile: """
            FROM dubodubonduponey/debian
            ARG TARGETPLATFORM
            RUN echo LOL $TARGETPLATFORM
        """
    },
    op.#PushContainer & {
        ref: "push-registry.local/dagger/test:1"
    },
]

```

If you add DockerLogin before, it runs once more.

**Comment by shykes** [comment]
I renamed the issue to reflect your latest findings @grouville . Does this duplicate logging occur for any core actions, or only a subset?

**Comment by sipsma** [comment]
Took a look and believe I figured out what was going on. I think this is actually intentional behavior on Buildkit's part.

We open a separate session in order to Export results (as a workaround for the lack of `Export` in the Gateway API), but as far as Buildkit knows that's the same as a totally separate client connecting and requesting a build that happens to overlap with an existing on-going build. Buildkit thus tries to be helpful and "backfill" the new client on all the progress so far. That's nice of it but in this case we are actually the same client, so we just end up with a bunch of duplicate progress events.

I opened an issue w/ Buildkit that has some more details and proposed fixes [here](https://github.com/moby/buildkit/issues/2817). For now, I think the solution of tracking which vertex digests have been completed and skipping logs for those ones is probably the best bet. It's more complicated for us and less performant than the other options, but has the large advantage of not needing upstream changes (and thus waiting for a new Buildkit release).
