### ISSUE TITLE
✨withEnvVariables

### ISSUE THREAD

**Issue by RonanQuigley** [dagger/dagger#4835]
### What are you trying to do?

This came out of a convo on Discord. 

I would like to Dagger to support a `withEnvVariables` call. The syntax would like like this  

```javascript
withEnvVariables({
    ENV_VAR_1: "VALUE",
    ENV_VAR_2: "VALUE"
    ENV_VAR_3: "VALUE"
    ...
})
``` 

[I might try and put a pull request in for this one, but I've raised in case I don't get around to it. cc @jpadams @kpenfound]

### Why is this important to you?

Complex pipelines can require numerous environment vars to be configured. Writing out withEnvVariable over and over gets tedious and bloats the pipeline code. 

### How are you currently working around this?

Using `withEnvVariable` for every env var that needs set.

**Comment by helderco** [comment]
You can actually create a reusable function to help with that:

```typescript
import Client, { connect } from "@dagger.io/dagger"
import { Container } from "@dagger.io/dagger/dist/api/client.gen"


connect(async (client) => {
    const ctr = client
        .container()
        .from("alpine")
        .with(envVariables({
            ENV_VAR_1: "VALUE 1",
            ENV_VAR_2: "VALUE 2",
            ENV_VAR_3: "VALUE 3",
        }))
        .withExec(["env"])

    console.log(await ctr.stdout())
})


function envVariables(envs: Record<string, string>) {
    return (c: Container): Container => {
        Object.entries(envs).forEach(([key, value]) => {
            c = c.withEnvVariable(key, value)
        })
        return c
    }
}
```

That's using the new [`with(...)` feature](https://github.com/dagger/dagger/pull/4332), and I'm assuming you're using the NodeJS SDK. Without using `with(...)` it's easy enough with a normal function, but then you have to break the chain:

```typescript
function withEnvVariables(c: Container, envs: Record<string, string>): Container {
    Object.entries(envs).forEach(([key, value]) => {
        c = c.withEnvVariable(key, value)
    })
    return c
}
```

**Comment by grouville** [comment]
@mircubed I do not understand the actionable step on this issue ? It is currently stuck by https://github.com/dagger/dagger/issues/3885 nonetheless

**Comment by helderco** [comment]
> It is currently stuck by #3885 nonetheless

It's not stuck. I provided usage with that feature. In Node.js it has been released already.

It just requires a decision if it's worth to add to the API or not.

**Comment by grouville** [comment]
@helderco, wdyt about adding that ? I can start the implementation right away, even though the `with()` implementation can indeed avoid overcharging the API

**Comment by helderco** [comment]
OP is right that it's common to need to set multiple env vars. I haven't seen so many of them put together to justify this, but if people find a need for it, each will have to create and reuse the helper above. So I think it's alright to add it to the API, but that's just me.

**Comment by vito** [comment]
@grouville Thanks for elucidating all of the options here :pray: 

I want to throw a sneaky option out there: what if we shortened `WithEnvVariable` to `WithEnv`? It feels pretty long for something that's used nearly everywhere. I wonder if this feature would have even been requested if it were shorter. I remember we considered shortening it but decided to keep it long because it clarifies the other env-related field names, but I'm not sure it's worth the constant tax on DX. It's pretty exhausting to type and read, frankly.

The typed options above don't seem to help much TBH:

```go
WithEnvVariables([]EnvVars{
    {Name: "toto", Value: "tata"},
    {Name: "tutu", Value: "titi"},
})

// vs.
WithEnvVariable("toto", "tata").
WithEnvVariable("tutu", "titi")

// vs.
WithEnv("toto", "tata").
WithEnv("tutu", "titi")
```

Aside from `WithEnv`, I'm also partial to the `NAME=value` option because it's familiar from a Go and Unix perspective, but it might be weird in other languages that don't directly expose that underlying format. It's at least a lot shorter! If we changed `Container.EnvVariables` to return the same format you could even do this:

```go
vars, err := ctr.EnvVariables(ctx)
ctr.WithEnvVariables(vars)
```

**Comment by grouville** [comment]
> @grouville Thanks for elucidating all of the options here 🙏
> 
> I want to throw a sneaky option out there: what if we shortened `WithEnvVariable` to `WithEnv`? It feels pretty long for something that's used nearly everywhere. I wonder if this feature would have even been requested if it were shorter. I remember we considered shortening it but decided to keep it long because it clarifies the other env-related field names, but I'm not sure it's worth the constant tax on DX. It's pretty exhausting to type and read, frankly.
> 
> The typed options above don't seem to help much TBH:
> 
> ```go
> WithEnvVariables([]EnvVars{
>     {Name: "toto", Value: "tata"},
>     {Name: "tutu", Value: "titi"},
> })
> 
> // vs.
> WithEnvVariable("toto", "tata").
> WithEnvVariable("tutu", "titi")
> 
> // vs.
> WithEnv("toto", "tata").
> WithEnv("tutu", "titi")
> ```
> 
> Aside from `WithEnv`, I'm also partial to the `NAME=value` option because it's familiar from a Go and Unix perspective, but it might be weird in other languages that don't directly expose that underlying format. It's at least a lot shorter! If we changed `Container.EnvVariables` to return the same format you could even do this:
> 
> ```go
> vars, err := ctr.EnvVariables(ctx)
> ctr.WithEnvVariables(vars)
> ```

Thank you, @vito, for your addition ! 🙏

The proposed changes are a solid alternative. I agree that deprecating the previous `withEnvVariable` implementation in favor of `withEnv` makes sense. This unifies the API across all languages (option 4 above) using `[]string{}` or `string....`
datastruct.

Although this approach deviates from other implementations like `withLabel`, it is more consistent with Unix principles. To guide users, proper examples in Go, Python and Node.js could be provided, as well as a hint from linters.

This unified approach streamlines the developer experience and simplifies environment variable handling across different languages. WDYT @helderco ?

**Comment by mircubed** [comment]
@aluzzardi could you give your thoughts on this, so @grouville can move forward?

**Comment by helderco** [comment]
On *Ordered map*, in Python a simple dict preserves key order (no need for OrderedDict these days). It's the same with Node.js objects[^1]. And the Go implementation doesn’t seem correct because `NewEnvVars` receives a `map[string]string` so I don’t see how that implementation can preserve key order.

[^1]: Taking into consideration the interpreters that are supported by dagger

At first glance, the simplest DX would be to use *the simplest map structure that preserves key order*. That means **`[]dagger.EnvVar{}` for Go and simple object/dict (`{}`) for Python and Node.js**. 

The problem is that there’s no map primitive in GraphQL that we can use as input so that the SDKs would do the simplest thing for each language. You need a list of objects.

We already have an `EnvVariable` type but it’s used for outputs, not inputs. If you adapt it or create a new `EnvVar` for input (😕) then you can’t codegen differently in the SDKs with simpler map structures, so you’re stuck with the more verbose implementation.

Compared with what we have now, there’s not much gain for that, especially if we shorten the name like @vito suggests:

```js
// ❌ more verbose
.withEnvVariables([
  new EnvVar('toto', 'tata'),
  new EnvVar('tutu', 'titi'),
])

// ✅ simpler
.withEnv('toto', 'tata')
.withEnv('tutu', 'titi')
```

We can instead create a custom input type that is generic:

```graphql
input KeyPair {
    key: String!
    value: String!
}

type Container {
    withEnvVariables(input: [KeyPair!])
}
```

That would allow codegen to do the simplest thing in each SDK, but the simplest thing in Go here is actually more verbose than what we already have, and we’re adding drift between the SDKs to keep things idiomatic.

**Go**
```go
WithEnvVariables([]dagger.KeyPair{
    {Key: "toto", Value: "tata"},
    {Key: "tutu", Value: "titi"},
})
```

**Python**
```python
with_env_variables({
    "toto": "tata",
    "tutu": "titi",
})
```

**Node.js**
```js
withEnvVariables({
  toto: 'tata',
  tutu: 'titi',
})
```

I’ve been thinking for a while that SDKs could provide helpers (compatible with `.with()`, for example) to abstract patterns that users keep reinventing, but it’s not clear how much that can become obsolete with extensions in the future.

```js
// implementation by the SDK
with(dagger.envVariables({
    ENV_VAR_1: "VALUE 1",
    ENV_VAR_2: "VALUE 2",
    ENV_VAR_3: "VALUE 3",
})
```

Simpler rename to `withEnv` sounds good to me.

**Comment by vito** [comment]
If we rename to `withEnv` we'll also want to figure out what the names for all the env-related things should be:

```graphql
type Container {
  envVariables: [EnvVariable!]!
  envVariable(name: String!): String
  withEnvVariable(name: String!, value: String!): Container!
  withoutEnvVariable(name: String!): Container!
  withSecretVariable(name: String!, secret: SecretID!): Container!
}
```

I remember this being the hard part. :)

Strawman:

```graphql
type Container {
  envs: [EnvVariable!]!
  env(name: String!): String
  withEnv(name: String!, value: String!): Container!
  withoutEnv(name: String!): Container!
  # consistent with withMountedSecret, + tab-complete discoverability
  withEnvSecret(name: String!, secret: SecretID!): Container!
}
```

**Comment by grouville** [comment]
> On _Ordered map_, in Python a simple dict preserves key order (no need for OrderedDict these days). It's the same with Node.js objects[1](#user-content-fn-1-c1b9e3ffb8e3238a806a4f962b0cebf9). And the Go implementation doesn’t seem correct because `NewEnvVars` receives a `map[string]string` so I don’t see how that implementation can preserve key order.

Thanks for the precision on Node && Python. Regarding the implementation of the ordered map in Go, I was thinking about settling on an ordering, not necessarily the ordering in which it was inputted in the map. (but you're right, the corresponding struct was created on top of my head, maybe not best implementation).

> I’ve been thinking for a while that SDKs could provide helpers (compatible with .with(), for example) to abstract patterns that users keep reinventing, but it’s not clear how much that can become obsolete with extensions in the future.

I totally agree, and the more I explore the backlog, the more I feel this is needed. For example, I am currently writing docs for https://github.com/dagger/dagger/issues/4896 (as, after discussion with @vito, it seems to be the best way to fix this issue: creating a helper function that people can reuse, client-side).

For that, I took the `with()` compatible approach:
```go
func mountSecretsFromDirectory(client *dagger.Client, sourceDir, targetDir string) func(*dagger.Container) *dagger.Container {
	return func(c *dagger.Container) *dagger.Container {
		err := filepath.Walk(sourceDir, func(path string, info fs.FileInfo, err error) error {
			if err != nil {
				return err
			}

			if !info.IsDir() {
				relativePath, _ := filepath.Rel(sourceDir, path)
				targetPath := filepath.Join(targetDir, relativePath)

				// Read file
				content, err := ioutil.ReadFile(path)
				if err != nil {
					return err
				}

				// Set secret to file content
				secret := client.SetSecret("ghConfig-"+relativePath, string(content))

				// Mount secret as file in container
				c = c.WithMountedSecret(targetPath, secret)
			}

			return nil
		})

		if err != nil {
			panic(err)
		}

		return c
	}
}
```

This could be the solution here too, and I wonder if we're not starting to fight against the stream.
Most of DX issues at the moment are due to the root cause Helder exposed right above, and if _SDKs could provide helpers_ , in a unified manner (a new section on the docs page, where community could contribute on 
their helpers (like a universe sections) ?

I'm ok with going to the `withEnv` solution ☑️

**Comment by helderco** [comment]
Just to summarize:

- Doesn't seem worth it to add to the API;
- Better suited for `.with()`;

Two improvements we can make:
- Decide if we want to add it to the SDKs
  - Trade-off: more work for each SDK to maintain, possible source of drift in supported features.
- Decide if it's worth it to rename [env related fields](https://github.com/dagger/dagger/issues/4835#issuecomment-1522520017) to something shorter (with deprecation, like [`Exec` → `WithExec`](https://pkg.go.dev/dagger.io/dagger#Container.Exec));

**Comment by mircubed** [comment]
Next steps as suggested by @samalba - We should take user input on this since this will impact all users.

**Comment by samalba** [comment]
@mircubed flagged this issue to make sure we don't lose the momentum towards a resolution, and I agree.

>     * Decide if it's worth it to rename [env related fields](https://github.com/dagger/dagger/issues/4835#issuecomment-1522520017) to something shorter (with deprecation, like [`Exec` → `WithExec`](https://pkg.go.dev/dagger.io/dagger#Container.Exec));

Seems like we have consensus on this one (from @vito @grouville @helderco)? @RonanQuigley, given you opened the issue, any opinion?

**Comment by grouville** [comment]
> @mircubed flagged this issue to make sure we don't lose the momentum towards a resolution, and I agree.
> 
> > * Decide if it's worth it to rename [env related fields](https://github.com/dagger/dagger/issues/4835#issuecomment-1522520017) to something shorter (with deprecation, like [`Exec` → `WithExec`](https://pkg.go.dev/dagger.io/dagger#Container.Exec));
> 
> Seems like we have consensus on this one (from @vito @grouville @helderco)? @RonanQuigley, given you opened the issue, any opinion?

Above PR (#5139) extends the docs, so that other users can learn about this `with()` pattern

**Comment by grouville** [comment]
> @mircubed flagged this issue to make sure we don't lose the momentum towards a resolution, and I agree.
> 
> > * Decide if it's worth it to rename [env related fields](https://github.com/dagger/dagger/issues/4835#issuecomment-1522520017) to something shorter (with deprecation, like [`Exec` → `WithExec`](https://pkg.go.dev/dagger.io/dagger#Container.Exec));
> 
> Seems like we have consensus on this one (from @vito @grouville @helderco)? @RonanQuigley, given you opened the issue, any opinion?

I think the PR #5139 closes this issue
