### ISSUE TITLE
Docs: standardize on using stderr for log output

### ISSUE THREAD

**Issue by helderco** [dagger/dagger#4858]
There's a lot of inconsistencies in the documentation when choosing either `stdout` or `stderr` on streaming the engine logs. In NodeJS it's almost always `stdout`, while in Go it's sometimes one or the other. I've always pushed for `stderr` in Python.

All SDKs should standardize to using `stderr` for that. It's not just for errors, it's for logs, **keeping `stdout` for the script's own output**.

Reference: [CLI Guidelines](https://clig.dev/#the-basics)
> **Send output to `stdout`.** The primary output for your command should go to `stdout`. Anything that is machine readable should also go to stdout—this is where piping sends things by default.
> 
> **Send messaging to `stderr`**. Log messages, errors, and so on should all be sent to `stderr`. This means that when commands are piped together, these messages are displayed to the user and not fed into the next command.

**Comment by mircubed** [comment]
@aluzzardi could you help me understand who should make a decision on this, so we can move forward with a standard approach?

**Comment by vikram-dagger** [comment]
Considering the comments in #5030, I have proposed a slight change: follow the suggestions in this issue for all snippets except for the get started guides, where all output should go to stdout by default. My reasoning (open to discussion) is that this is the user's first experience with Dagger, so it's useful for them to "see something happening", instead of wondering about a blank screen while images are downloaded in the background.

Note: this could also be handled differently, eg. mentioning in the text that "this will take a while as images are being downloaded". Interested in knowing your thoughts on this @helderco @mircubed @gerhard @jpadams @slumbering @crjm @kpenfound

**Comment by slumbering** [comment]
@vikram-dagger : With `LogOutput: process.stderr` users will still see something happening. Using `stderr` instead of `stdout` primarily maintains consistency and does not affect the SDK's behavior in any significant way.

**Comment by helderco** [comment]
@vikram-dagger, like @slumbering says, changing to `stderr` won't change anything visually for the user. You can see for yourself.
