### ISSUE TITLE
Allow string parameter for `withSecretVariable`

### ISSUE THREAD

**Issue by kpenfound** [dagger/dagger#5000]
Currently, `withSecretVariable` takes a `dagger.Secret`. The dx for this looks like:

```go
mysecret := client.SetSecret('my-var', 'secret value')

mycontainer := client.Container().From('alpine').WithSecretVariable('SECRET_ENV', mysecret)
```

I'm proposing we _also_ have an option to pass a `string` instead of a `dagger.Secret` and skip the first step, like:

```go
mycontainer := client.Container().From('alpine').WithSecretVariable('SECRET_ENV', 'secret value')
```

Thoughts?

**Comment by helderco** [comment]
Sounds good, but that would be the first case of a union. How would Go handle the value being `string | Secret`?

**Comment by helderco** [comment]
I know you can use `interface{}`, just wondering about the reference docs and IDE autocomplete.

**Comment by kpenfound** [comment]
Yeah good question. I'm not familiar enough with the current workarounds with `interface{ string | Secret}` for Go. Maybe a good DX docs-wise would be a separate function with different parameters

**Comment by helderco** [comment]
Oops, you can only use unions in return values, not in inputs. You'd need a struct/type with different fields for either string or `Secret`:

```go
type SecretValue struct {
    plain string
    secret *Secret
}
```

To do the logic in codegen instead is also a bit tricky:
- You need custom code in each SDK to handle this specific case (and hardcoded to this specific `Container.withSecretVariable` field), if it's not coming from the API;
- In Go, you could provide a variable that's neither type (since you'd have a `secret interface{}` argument) so how would you handle that error? `WithSecretVariable` doesn't return an error and we can't assume a panic, can we?

So best solution is adding a variation of `withSecretVariable` but can't think of a good name.

In any case, you also need to assume the secret name is the env variable name.

**Comment by helderco** [comment]
As I said in my last comment, the only viable way to do this is to create another field as a convenience. However, as discussed in https://github.com/dagger/dagger/pull/5445#issuecomment-1636852883, this doesn't seem worth it mainly for the following reasons:
- Not much gain from the alternative convenience function.
- Best to decouple secret creation from its usage.

**Example:**
```go
ctr.WithSecretVariable("FOO", client.SetSecret("FOO", "bar"))

// vs

ctr.WithPlainSecretVariable("FOO", "bar")
```

**Comment by TomChv** [comment]
@helderco Should I write a guide about it then? I closed the PR because it does not make sens anymore to work on it.

**Comment by helderco** [comment]
I also don't think it's worth a guide. Maybe adding a `With` util in the "using secrets" guide next to the example for getting a value from a host env var as a suggestion for "if you do this often" kind of thing, just as a reminder that you can make your own abstractions. 

Or as an optimization cookbook like https://docs.dagger.io/7442989/cookbook#add-multiple-environment-variables-to-a-container.

**Comment by TomChv** [comment]
So should we close this PR @helderco ?
