### ISSUE TITLE
How to use secrets with Dockerfiles

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#5242]
### What is the issue?

Question from a user in Discord https://discord.com/channels/707636530424053791/1113785258731638784 on how to access secrets in Dockerfiles while using the `secrets` argument in the `Build` operation.

**Comment by MikaelElkiaer** [comment]
I think I have run into the same issue, so I will just piggy-back here.

I have made a small example: https://github.com/MikaelElkiaer/dagger-examples/tree/main/dockerfile-secrets.

I am trying to make the transition to Dagger, while initially keeping my Dockerfiles - I like Dockerfile for the most part, right now I am just hoping to get rid of my `yaml` and `sh` glue.
However, I am utilizing [Docker Build secrets](https://docs.docker.com/build/building/secrets/) which I cannot get to work with Dagger.
I believed that https://github.com/dagger/dagger/pull/6924 would fix my issue, but it did not.
No matter what I try, I cannot locate any secrets within `/run/secrets/` as advertised.

@levlaz I moved this from our chat to here, sorry for going directly to you.

**Comment by helderco** [comment]
@MikaelElkiaer, thanks for making the repro!

The problem here is that when you set a secret through the CLI, you only set it's value, not the name. The secret's name is set to a sha256 checksum of the value, as you can see in `--debug`:

```
✔ setSecret(name: "fe878d18e3dd734bdf54f429947e73eb9956064fb1fabb103a6403c8777649ff"): Secret!
```

So, in your Dockerfile, you're trying to mount a secret with the name `secret-file`, but that doesn't exist. You could create a new secret with that name and the value from the function argument. Or, get the secret's id in the Dockerfile via a build argument:

```diff
 FROM alpine:3.19.1
-RUN --mount=type=secret,id=secret-file,target=/run/secrets/secret.txt cat /run/secrets/secret.txt
+ARG SECRET_ID
+RUN --mount=type=secret,id=$SECRET_ID,target=/run/secrets/secret.txt cat /run/secrets/secret.txt
```
And pass the name from the function:
```go
func (m *DockerfileSecrets) Build(
	ctx context.Context,
	// Build context
	buildContext *Directory,
	// Dockerfile path
	dockerfile *File,
	// Secret file path
	secretFile *Secret,
) (*Container, error) {
	secretName, err := secretFile.Name(ctx)
	if err != nil {
		return nil, err
	}
	return buildContext.
		WithFile("Dockerfile", dockerfile).
		DockerBuild(dagger.DirectoryDockerBuildOpts{
			BuildArgs: []BuildArg{
				{Name: "SECRET_ID", Value: secretName},
			},
			Secrets: []*Secret{secretFile},
		}), nil
}
```

This way you can see that the Dockerfile pulls in the right id:

```
[stage-0 2/2] RUN --mount=type=secret,id=fe878d18e3dd734bdf54f429947e73eb9956064fb1fabb103a6403c8777649ff,target=/run/secrets/secret.txt cat /run/secrets/secret.txt
```

Admitedly, this could be better! Either:
- Allowing to set the name via the CLI
  - Requires expanding the current custom syntax for loading secrets from multiple sources
- Have secrets be a list of `[]struct{Name string, *Secret Secret}`
  - Name only for referencing in the Dockerfile, equivalent to `docker build --secret id=aws,src=/root/.aws/credentials .`
  - An empty name would use the one in the `Secret` instance
  - Breaking change unless we use another `DirectoryDockerBuildOpts` field this!

**Comment by helderco** [comment]
cc @vikram-dagger

**Comment by MikaelElkiaer** [comment]
I have given up on this for now, but will just leave my thoughts in case anyone picks it up.

Basically, I am trying to utilize my already existing, very generic,
<details><summary>Dockerfile</summary>
<p>

```Dockerfile
# syntax=docker/dockerfile-upstream:master-labs
# Needed for experimental `--parents` flag

ARG BUILD_CONFIGURATION=Release
ARG PROJECT_NAME

FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS base
RUN apk add bash
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
RUN apk add bash
ARG BUILD_CONFIGURATION
WORKDIR /src
COPY *.sln .
COPY --parents */*.csproj .
RUN --mount=type=secret,id=nuget,target=NuGet.Config dotnet restore
COPY . .
RUN dotnet build --configuration $BUILD_CONFIGURATION

FROM build AS publish
ARG BUILD_CONFIGURATION
ARG PROJECT_NAME
RUN dotnet publish "$PROJECT_NAME" -c "$BUILD_CONFIGURATION" -o /app/publish /p:UseAppHost=false

FROM build AS test
ARG BUILD_CONFIGURATION
ENV BUILD_CONFIGURATION=$BUILD_CONFIGURATION
ENTRYPOINT dotnet test -c "$BUILD_CONFIGURATION"

FROM build AS watch
ARG BUILD_CONFIGURATION
ENV BUILD_CONFIGURATION=$BUILD_CONFIGURATION
ARG PROJECT_NAME
ENV PROJECT_NAME=$PROJECT_NAME
HEALTHCHECK --interval=1s --timeout=500ms --start-period=10s --retries=30 CMD wget --no-verbose --tries=1 --spider http://127.0.0.1/healthz || exit 1
USER $APP_UID
ENTRYPOINT dotnet watch --project "$PROJECT_NAME" -- run --configuration "$BUILD_CONFIGURATION" --no-launch-profile

FROM scratch AS final-scratch
WORKDIR /app
COPY --from=publish /app/publish .

FROM base AS final
ARG PROJECT_NAME
ENV PROJECT_NAME=$PROJECT_NAME
COPY --from=final-scratch /app .
RUN chown -R $APP_UID:$APP_UID /app
HEALTHCHECK --interval=1s --timeout=500ms --start-period=500ms --retries=30 CMD wget --no-verbose --tries=1 --spider http://127.0.0.1/healthz || exit 1
USER $APP_UID
ENTRYPOINT dotnet "${PROJECT_NAME}.dll"
```

</p>
</details> 

in order to do a gradual migration.
But even with all the suggestions in the issue comments here, I have not been able to do so.
I also started rewriting my Dockerfile into Dagger functions, but also hit a few other blockers - e.g. having to re-implement `COPY --parents`, extra work related to globs, and being forced to use absolute paths.

All of this sounds a bit harsh, but I do mean for it to be constructive.
I have not completely given up on Dagger, but am prioritizing other things while Dagger is still maturing.

**Comment by marcosnils** [comment]
hey @MikaelElkiaer! we're sorry that you're running into all these issues. We'll revisit the Dockerfile support and work to address them. 

Are  you still having issues with secrets? what's the step in the Dockerfile that you shared above besides the experimental `COPY --parents` that's not working for you?  I'd live to mention @jedevc here given this vast experience in Buildkit :pray:

**Comment by marcosnils** [comment]
@MikaelElkiaer I also ran quick test and seems like the `--parents` capability already works as expected in Dagger unless I'm missing something. Here's what I did:

```
tree ./src/
./src/
├── bar
│   └── bar.txt
└── foo
    └── foo.txt
```

```go
// Returns a container that echoes whatever string argument is provided
func (m *TmpKnphdbyLnl) Test(src *Directory) (string, error) {
	return dag.Container().From("alpine").
		WithDirectory("/app", src, dagger.ContainerWithDirectoryOpts{
			Include: []string{"*/*.txt"},
		}).WithExec([]string{"find", "/app"}).Stdout(context.Background())
}
```
dagger call test --src ./src/

/app
/app/foo
/app/foo/foo.txt
/app/bar
/app/bar/bar.txt
```

IIUC that's the same behavior as `--parents`, correct?

**Comment by MikaelElkiaer** [comment]
@marcosnils `WithDirectory` and `ContainerWithDirectoryOpts` definitely did the trick to replace `--parents`.
I had only looked at `WithFile` and `ContainerWithFileOpts` and concluded that it had nothing in regard to globs.

The other step I am having a hard time re-creating is

```Dockerfile
RUN --mount=type=secret,id=nuget,target=NuGet.Config dotnet restore
```

I did figure out how to do it with `WithMountedSecret` though.
Took a while, as I keep stumbling on how to set paths - I had assumed I could give the function a directory in which to mount the secret file, but it seems it needs an exact file. Otherwise I presume it overwrites the entire directory, resulting in strange behaviour.
The following example results in an error, but even with `-vvv` I can't readily determine the underlying problem.

<details><summary>Details</summary>
<p>

```go
func (m *MyModule) Test(
  ctx context.Context,
	nugetConfig *Secret,
) *Container {
  return dag.Container().
    From("mcr.microsoft.com/dotnet/sdk:8.0-alpine").
    WithWorkdir("/src").
    WithMountedSecret(".", nugetConfig). // WRONG - path should be "./NuGet.Config"
    WithExec([]string{"ls", "-al"})
}
```

</p>
</details>

**Comment by helderco** [comment]
The secret's name (in [`SetSecret`](https://pkg.go.dev/dagger.io/dagger#Client.SetSecret)) affects the path only when used in a dockerfile build. It's the `id=nuget` in:

```dockerfile
RUN --mount=type=secret,id=nuget,target=NuGet.Config dotnet restore
```

But if you're building with dagger, you control that path irregardless of the secret's name, with the first argument to [`WithMountedSecret`](https://pkg.go.dev/dagger.io/dagger#Container.WithMountedSecret). It's the path to the file where the secret is saved, not the directory to create it in.

The Go reference doesn't show the arguments' descriptions, so let's look at the API's: https://docs.dagger.io/api/reference/#Container-withMountedSecret

Example:

```diff
func (m *MyModule) Test(
	ctx context.Context,
	nugetConfig *Secret,
) *Container {
	return dag.Container().
		From("mcr.microsoft.com/dotnet/sdk:8.0-alpine").
		WithWorkdir("/src").
-		WithMountedSecret(".", nugetConfig). // WRONG - path should be "./NuGet.Config"
+		WithMountedSecret("NuGet.Config", nugetConfig).
		WithExec([]string{"ls", "-al"})
}
```

As for creating a secret, **if you're using modules**, you need to replace `client := dagger.Connect()` with the already available `dag`

Example:

```go
// note: name is not the path
secret := dag.SetSecret("secret-name", "secret-contents")
```

@vikram-dagger, we should add this use case to https://docs.dagger.io/manuals/developer/go/203021/secrets.

**Comment by MikaelElkiaer** [comment]
@helderco Great answer, thanks a lot.

**Comment by vikram-dagger** [comment]
> @vikram-dagger, we should add this use case to https://docs.dagger.io/manuals/developer/go/203021/secrets.

I've created an internal issue to add this to the docs.

**Comment by helderco** [comment]
This has already been added to the cookbook a while ago, even though there's a fix for it:
- https://github.com/dagger/dagger/pull/8058
- https://github.com/dagger/dagger/pull/8049

Can we close this one then?
