### ISSUE TITLE
copying files to/from host takes too long.

### ISSUE THREAD

**Issue by itaischwartz** [dagger/dagger#5285]
### What happened? What did you expect to happen?

Hey,

I'm using the following code to sync a large (~800MB) tar file between a container and the host.
```go
    ctr.WithMountedFile(tarFile, d.Host().File(hostFile)) // import
    ....
    create new tar
    ....
    ctr.File(tarFile).Export(ctx, exportDir); // export
```
On GitHub actions, using dagger v0.7.1,
It takes almost 90 seconds to import the file and 4 minutes to export it.

Any way to export a file faster?

**Comment by itaischwartz** [comment]
Any thoughts?

**Comment by grouville** [comment]
@itaischwartz, did you manage to reproduce with @kpenfound's examples ? Interested to have a repro from your side to dig into that 🙏

**Comment by TomChv** [comment]
Alright, we need a repro, I'm pretty sure it comes from buildkit and not directly Dagger, I might be able to repro the same issue with a simple Dockerfile if we could have an actual repro case

**Comment by gerhard** [comment]
@TomChv let's try to generate 10k small files and see how the latest version - `v0.8.4` handles it. Remember that there was a big change in `v0.8` which should have addressed this:
- https://github.com/dagger/dagger/pull/5415

**Comment by TomChv** [comment]
I do not see any issue with 10K files, it's really fast!

My repro code:

```go
	ctx := context.Background()
	c, err := dagger.Connect(ctx)
	if err != nil {
		log.Fatalln(err)
	}
	defer c.Close()

	ctr := c.Host().Directory("files-5285")

	_, err = ctr.Export(ctx, "cpy-files-5285")
	if err != nil {
		log.Fatalln(err)
	}
```

And the following shell script to generate 10K random files

```bash
#! /bin/bash
for n in {1..10000}; do
    dd if=/dev/urandom of=file$( printf %03d "$n" ).bin bs=1 count=$(( RANDOM + 1024 ))
done
```

Here's the output using `dagger run`

```
▽ │ host.directory files-5285
█ │ [3.85s] upload files-5285
┣ │ [3.74s] transferring eyJvd25lcl9jbGllbnRfaWQiOiJ1Yjk1b2Fqemhpc2VwYWpsNDMybGRhdnd6IiwicGF0aCI6ImZpbGVzLTUyODUiLCJpbmNsdWRlX3BhdHRlcm5zIjpudWxsLCJleGNsdWRlX3BhdHRlcm5zIjpudWxsLCJmb2xsb3dfcGF0aHMiOm51bGwsInJlYWRfc2luZ2xlX2ZpbGVfb25seSI6ZmFsc2UsIm1heF9maWxlX3NpemUiOjB9:
█ │ [0.66s] copy files-5285
┻ │ 
  █ [2.26s] export directory to host cpy-files-5285
```

**Comment by TomChv** [comment]
@gerhard Should we close this issue until we can have a repro case?

**Comment by helderco** [comment]
Maybe I'm missing context here but this operation became much faster with the v0.8.0 release when the API server moved from the CLI to the engine container. I see the issue was created 3 months ago so that can be why you can't repro it now.

**Comment by TomChv** [comment]
We were thinking the same with @gerhard

**Comment by gerhard** [comment]
Thank you @TomChv for confirming that with 10k files this takes `~3s` to upload & `~2s` to download. I used your repro.

> **Note**
> My Engine is remote, I connect via WiFi (sync-inc at 175Mbps - `lastTxRate`):
> <img width="665" alt="image" src="https://github.com/dagger/dagger/assets/3342/836cf8a1-af67-4567-a219-e45b88b39c18">

In my case it took `13s` to upload & `10s` to download `10k` files with random sizes, 185MB in total:
<img width="672" alt="image" src="https://github.com/dagger/dagger/assets/3342/783ff575-53eb-407d-b0b1-73f9c6cfe882">

I am seeing a similar throughput with Go SDK `v0.7.1` (Engine `v0.6.1`), same versions that @itaischwartz was using - the difference is WiFi signal fluctuation:
<img width="560" alt="image" src="https://github.com/dagger/dagger/assets/3342/94d4ac95-604c-403b-b6a1-35fbec096ad1">

I went a step further and ran the same directly on the host that runs Dagger, so that there is no network involved:
- Go SDK `v0.8.4` - `1s` to upload & `0.5s` to copy 10k files
- Go SDK `v0.7.1` - `1s` to upload & `0.5s` to copy 10k files

<img width="559" alt="image" src="https://github.com/dagger/dagger/assets/3342/ce885268-ef25-4b59-9493-e7f3be837cbe">

**I don't see any improvement** for 10k files between Go SDK `v0.7.1` & `v0.8.4`.

After both repros - thank you @TomChv & @kpenfound - this one is OK to close.
