### ISSUE TITLE
🐞 Using Dagger-in-Dagger busts caches due to unstable Progrock socket ID

### ISSUE THREAD

**Issue by vito** [dagger/dagger#5373]
### What is the issue?

When you use Dagger-in-Dagger, part of it mounts the Progrock socket in so that progress can be forwarded to the outer TUI:

https://github.com/dagger/dagger/blob/0c8da0a136047f58930ba69d0b5779cfcffb93b7/core/container.go#L1056

However the socket on the other side of this has a path that changes on every run:

https://github.com/dagger/dagger/blob/0c8da0a136047f58930ba69d0b5779cfcffb93b7/engine/engine.go#L423

Suggestion: we can add the ability to set a fixed name or ID to sockets and use that as the ID in LLB instead of using the path. Defaulting to the path is fine; the name/ID should be optional.

### Log output

Discord thread:

https://discord.com/channels/707636530424053791/1123261502208626688

### Steps to reproduce

1. Write a pipeline that uses `ExperimentalPrivilegedNesting: true`
2. Observe that the `WithExec` runs every time

### SDK version

any SDK, engine v0.6.2

### OS version

any

**Comment by gerhard** [comment]
Great find! Thank you @marcosnils for the link 💪

I now know what makes our Dagger-in-Dagger runs not use the cache: https://github.com/dagger/dagger/blob/221255079b80bf1e2c45ac481219d170e0a954f9/internal/mage/util/engine.go#L150-L180

**Comment by sipsma** [comment]
In theory, this problem should no longer exist after https://github.com/dagger/dagger/pull/5415 due to the fact that the progsock is setup ([here](https://github.com/sipsma/dagger/blob/8d5fd2bbc5ba4dae3160648fcf7455ad250e66ac/engine/server/server.go#L71-L71)) and then passed through to the exec w/out busting the cache ([here](https://github.com/sipsma/dagger/blob/8d5fd2bbc5ba4dae3160648fcf7455ad250e66ac/core/container.go#L1958-L1958)).

However, I don't want to close the issue until we have an integ test verifying that. We are adding integ tests as part of Zenith that will implicitly test this (since they verify module execution is cached, which requires that nested exec caching works in general).

**Comment by vito** [comment]
Progrock is long gone
