### ISSUE TITLE
✨ `EnvVariable` should return `nil` if variable does not exist

### ISSUE THREAD

**Issue by TomChv** [dagger/dagger#5449]
### What are you trying to do?

Context on https://github.com/dagger/dagger/pull/5445#discussion_r1262868539

Currently if an environment variable does not exist, it will either return `""` in Go, an error in Node SDK (bug) and `None` in Python.

The API correctly returns `null` so SDKs should follow suit because an empty value (`""`) is valid for existing env variables.

This is not only for `EnvVariable` though, it should be for any field that returns an optional string (i.e., `String`, not `String!`).

**Comment by helderco** [comment]
No, not an error. Go SDK just needs to return `nil` on responses with `null`, like Python does returning `None`.

This happens on optional strings, so:
- `String!` → `(string, error)`
- `String` → `(*string, error)`

**Comment by helderco** [comment]
Quickly tested in Node.js and there's a bug:
```
file:///Users/helder/Projects/dagger/sdk/nodejs/dist/api/utils.js:155
                throw new GraphQLRequestError(msg, {
                      ^

GraphQLRequestError: API Error
    at file:///Users/helder/Projects/dagger/sdk/nodejs/dist/api/utils.js:155:23
    at Generator.throw (<anonymous>)
    at rejected (file:///Users/helder/Projects/dagger/sdk/nodejs/dist/api/utils.js:5:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  cause: ClientError: GraphQL Error (Code: 200): {"response":{"error":"{\"data\":{\"container\":{\"from\":{\"envVariable\":null}}}}","status":200,"headers":{}},"request":{"query":"\n        { container  { from (address: \"alpine\") { envVariable (name: \"FOO\") }} }\n      "}}
      at makeRequest (file:///Users/helder/Projects/dagger/sdk/nodejs/node_modules/graphql-request/build/esm/index.js:282:15)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    response: {
      error: '{"data":{"container":{"from":{"envVariable":null}}}}',
      status: 200,
      headers: Headers {
        [Symbol(map)]: [Object: null prototype] {
          date: [ 'Tue, 18 Jul 2023 17:17:15 GMT' ],
          'content-length': [ '52' ],
          'content-type': [ 'text/plain; charset=utf-8' ],
          connection: [ 'close' ]
        }
      }
    },
    request: {
      query: '\n' +
        '        { container  { from (address: "alpine") { envVariable (name: "FOO") }} }\n' +
        '      ',
      variables: undefined
    }
  },
  code: 'D100',
  requestContext: {
    query: '\n' +
      '        { container  { from (address: "alpine") { envVariable (name: "FOO") }} }\n' +
      '      ',
    variables: undefined
  },
  response: {
    error: '{"data":{"container":{"from":{"envVariable":null}}}}',
    status: 200,
    headers: Headers {
      [Symbol(map)]: [Object: null prototype] {
        date: [ 'Tue, 18 Jul 2023 17:17:15 GMT' ],
        'content-length': [ '52' ],
        'content-type': [ 'text/plain; charset=utf-8' ],
        connection: [ 'close' ]
      }
    }
  }
}
```

**Comment by helderco** [comment]
I updated the description.

**Comment by JammUtkarsh** [comment]
Hey @TomChv

If this issue is not yet fixed, I want to help out!

From what I have understood, the API needs to return `nil` instead of `""` string. Correct?

And what is `String!` which you both have mentioned?

Since I want to solve for Go SDK first, where can I find this code?

**Comment by helderco** [comment]
## API

> And what is `String!` which you both have mentioned?

That's from our API (GraphQL):

https://github.com/dagger/dagger/blob/9c38a76c2a28a52180a10ef64b03d5ea0d2e1f0b/core/schema/container.graphqls#L144-L149

It means `envVariable` returns a nullable string (i.e., can be a string or `null`). 

From the spec in [GraphQL - Non-Null](http://spec.graphql.org/October2021/#sec-Non-Null):

> By default, all types in GraphQL are nullable; the **null** value is a valid response for all of the above types. To declare a type that disallows null, the GraphQL Non-Null type can be used. This type wraps an underlying type, and this type acts identically to that wrapped type, with the exception that **null** is not a valid response for the wrapping type. A trailing exclamation mark is used to denote a field that uses a Non-Null type like this: `name: String!`.


## Go SDK

> From what I have understood, the API needs to return `nil` instead of `""` string. Correct?

The API is correct, it's only the Go SDK that needs fixing. Node.js has a different issue with #5482, only after that's fixed can we know if this issue also applies there.

> Since I want to solve for Go SDK first, where can I find this code?

Codegen is producing this signature:

https://github.com/dagger/dagger/blob/9c38a76c2a28a52180a10ef64b03d5ea0d2e1f0b/sdk/go/api.gen.go#L243

So returning `string` marshals a `null` into `""`. However that doesn't allow us to distinguish, using the Go SDK, if the variable didn't exist or was just empty. So I think that should be turned into: 
```diff
-func (r *Container) EnvVariable(ctx context.Context, name string) (string, error) {
+func (r *Container) EnvVariable(ctx context.Context, name string) (*string, error) {
```
This way a `null` API value (JSON) can be marshaled into a `nil` value in Go. 

## Codegen

That signature is being generated in:

https://github.com/dagger/dagger/blob/9c38a76c2a28a52180a10ef64b03d5ea0d2e1f0b/codegen/generator/go/templates/functions.go#L207-L211

So we also need to check for non-null there.

For comparison with the Python SDK, on non-leafs we always force non-null (to allow chaining):

https://github.com/dagger/dagger/blob/9c38a76c2a28a52180a10ef64b03d5ea0d2e1f0b/sdk/python/src/dagger/codegen.py#L455-L461

Otherwise, any nullable leaf values allow `None` (`Optional[str]` == `str | None`):

https://github.com/dagger/dagger/blob/9c38a76c2a28a52180a10ef64b03d5ea0d2e1f0b/sdk/python/src/dagger/codegen.py#L440-L444

**Comment by helderco** [comment]
Sorry @JammUtkarsh, I'm also going to close this issue. Going after the necessary changes to orient you, it made me think about what else would be affected by this change:

- `Container.EnvVariable`
- `Container.ImageRef`
- `Container.Label`
- `Container.User`
- `Container.Workdir`
- `Port.Description`
- _(other Zenith fields, e.g., command's description...)_

Apart from `EnvVariable` and `Label` I'd rather keep the empty value instead of turning into pointers. However, you can always use `EnvVariables` and `Labels` to check existence if you really need it.

For more context, I brought it up to https://github.com/dagger/dagger/discussions/5374#discussioncomment-6582671 for a second opinion and now I'm quite convinced it's better to leave this as-is.
