### ISSUE TITLE
🐞 `dagger run` is reporting an incorrect Engine version

### ISSUE THREAD

**Issue by gerhard** [dagger/dagger#5572]
### What is the issue?

When running `dagger run` with `v0.8.0`, the Engine version is reported incorrectly:

<img width="607" alt="image" src="https://github.com/dagger/dagger/assets/3342/4c6fcc9e-985b-4032-95e7-ebeed03f94b2">

For comparison, this is what the output looks like for `v0.6.4`:

<img width="509" alt="image" src="https://github.com/dagger/dagger/assets/3342/1f94f12c-a46b-4c2a-8cf4-cd078d446ebd">
<img width="587" alt="image" src="https://github.com/dagger/dagger/assets/3342/b27d01d7-c137-4485-9006-6deb7fa01574">

---

I suspect that this is related to https://github.com/dagger/dagger/pull/5315, but I did not spend time digging into it. cc @TomChv @vito 

### SDK version

Go SDK v0.8.0

### OS version

SDK / CLI on macOS 12.6 & Engine on NixOS 22.11 (Linux 5.15)

**Comment by sipsma** [comment]
I think I know the problem here, the version number is now being set in the engine image (that's where the graphql server lives now) and then sent to the cli client when it connects, but that image isn't being stamped with `-X`, so it is defaulting to the devel string. If so should be an easy fix. I'll see if I can get test coverage too, which doesn't exist yet afaik.
