### ISSUE TITLE
Zenith: fix papercut around module workdir and need to load ".."

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#5914]
The workdir of Module Functions is currently set to be the directory containing `dagger.json` (and thus your module code). This is fine, but in the exceptional cases where a module needs to use a separate root dir (e.g. there's a `go.mod`, `pyproject.toml` or other resources required from a parent dir), you hit a papercut.

Example in the Python SDK module here: https://github.com/sipsma/dagger/blob/c847458d6df1e184487e3a29f6d00a86ef67e661/sdk/python/runtime/main.go#L82-L82

You want to be able to just call `dag.Host().Directory("..")`, but can't due to restrictions in place at this time on that API. So instead you have to workaround by getting the current workdir and appending `..`, so that it's an absolute path.

I think we should fix this by just removing the `..` restriction in that API, which no longer serves any purpose, but we should verify others are onboard with that.

---

Related PR where this arose: https://github.com/dagger/dagger/pull/5900

Related discord discussion: https://discord.com/channels/707636530424053791/1162509681126809710/1162509683593072711

**Comment by jedevc** [comment]
I think this makes sense - I think we can easily remove the restriction (since it's so easy to workaround).

However, I do think we should do it with an additional check that the requested `Directory` is a sub-dir of the `root` in `dagger.json`. https://github.com/dagger/dagger/pull/6086 adds this check for dependencies (so you can't load `../foo` when root is `.`), it would be good to enforce this globally. (note, this is mostly just a user-convenience, it doesn't actually protect against loading specific files).

**Comment by helderco** [comment]
@sipsma, I think this has been addressed in https://github.com/dagger/dagger/pull/6535. Good to close?
