### ISSUE TITLE
Services V2 (Rust SDK): Graphql syntax error with port forward

### ISSUE THREAD

**Issue by brprkr** [dagger/dagger#5928]
### What is the issue?

Expect service on host port.

```toml
# Cargo.toml
# ...
[dependencies]
color-eyre = "0.6.2"
dagger-sdk = { git="https://github.com/dagger/dagger"}
# ...
```
```rust
// main.rs
use dagger_sdk::PortForward;


#[tokio::main]
async fn main() -> color_eyre::eyre::Result<()> {

    let client = dagger_sdk::connect().await?;

    let service = client.host().service(vec![PortForward {
        protocol: dagger_sdk::NetworkProtocol::TCP,
        frontend: 80,
        backend: 44317
    }]);

    let container = client.container().from("ubuntu:latest")
        .with_exec(vec!["apt-get", "-y", "update"])
        .with_exec(vec!["apt-get", "-y", "install", "curl"])
        .with_service_binding("kind_service", service)
        .with_exec(vec!["curl", "-k", "https://127.0.0.1:80"]);

    let _stdout = container.stdout().await?;

    Ok(())
}
```

### Log output

```
┃ thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Query(DomainError { message: "Look at json field for more details", fields: GraphqlErrorMessages(["Syntax Error GraphQL request (1
┃ :28) Expected Name, found String \"backend\"\n\n1: query{host{service(ports:[{\"backend\":44317,\"frontend\":80,\"protocol\":\"TCP\"}]){id}}}\n                              ^\n"]) })', /home/XXX/.carg
┃ o/git/checkouts/dagger-b5eab31788856551/eb39165/sdk/rust/crates/dagger-sdk/src/gen.rs:1691:58
┃ note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Steps to reproduce

Service created on port 44137 on host machine prior to running

### SDK version

Rust (main ba401f4)

### OS version

Ubuntu 18 lts

**Comment by kjuulh** [comment]
@brprkr I will have a look =D

**Comment by kjuulh** [comment]
I've reproduced the error and found the bug. When using input objects, we use serialize on the type, which we shouldn't as keys cannot be strings. I'll see how easy it is to fix.

**Comment by kjuulh** [comment]
I forgot to give an update here. As it turns out we need an entirely separate serde_graph_input package. I haven't forgotten the issue. I will get it sorted. 

The graphql used to communicate with the dagger-engine has parts of it that requires more complex input objects, I'd made it work previously by hacking together all the graphql input stuff that deviates from normal json. However, it isn't recursive like this feature requires. For that we need an actual proper serde package. I have started on it, but haven't had the time yet.
