### ISSUE TITLE
🐞 Zenith: `WithFocus()` only prints `WithExec` statements and not `Pipeline()` labels for `dagger call`

### ISSUE THREAD

**Issue by nipuna-perera** [dagger/dagger#5994]
### What is the issue?

If I add `WithFocus()` to a container it prints all the `WithExec()` commands but does not show the `Pipeline()` labels.

### SDK version

Go SDK 0.9.1

### OS version

MacOS

**Comment by nipuna-perera** [comment]
@sipsma as requested :)

**Comment by jedevc** [comment]
Both `WithFocus` and `Pipeline` have now been deprecated as part of https://github.com/dagger/dagger/pull/6835.

The new TUI shouldn't need these, which has completely overhauled to use spans as the main progress primitive :tada:

Going to close this one out, since the components in this issue no longer exist!
