### ISSUE TITLE
Zenith: Unify `dag` and `dagger` in Go and Python sdks

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#6127]
Today, users writing modules need to use

`dag.Foo()` in the Go SDK

and 

`dagger.foo()` in the Python SDK

Can we make either
1) both `dag` and `dagger` work everywhere
2) we decide on one thing that can work everywhere

@shykes @helderco @sipsma

**Comment by sipsma** [comment]
While I'm sure we could do this specifically, in general I'm not sure that it's really a goal for the SDKs to be aligned in this sort of way. There's so many differences between languages that I think we more need to accept that names, syntax, etc. are going to be different and just rely on good documentation existing for all the official SDKs so authors always know how to write modules in each one.

E.g. even if we are consistent in `dagger` vs. `dag` we can't be consistent in other things like casing (`.WithExec` vs. `.with_exec`), how options are provided, etc. And at that point does `dagger` vs `dag` really matter that much?

That being said, I do like `dag` more just because it's shorter to type 🙂, so if @helderco thinks this is a very easy modification to make then I'd say lets do it, but as a one-off improvement to Python rather than an effort to keep SDKs perfectly aligned around issues like this.

**Comment by helderco** [comment]
I actually like the simplicity of having the global import for everything:
```python
import dagger

dagger.container()....
```
With `dag`, another import would be needed:
```
import dagger
from dagger import dag
from dagger.mod import function
```
But I do see two advantages by adopting `dag`:
- Avoids namespace collisions especially with modules since the snake cased version of a module gets created on the `dagger` namespace;
- Avoids confusion with `dagger.Container` vs `dagger.container`. The former would stay the same while the latter would become `dag.container()`.

Maybe since there's no longer a collision on `dagger.function` (`Query.function`), we could bring mod to `dagger`:

```python
import dagger
from dagger import dag, function

@function
def hello() -> dagger.Container:
    return dag.container()....
```

\cc @TomChv

**Comment by jpadams** [comment]
> While I'm sure we could do this specifically, in general I'm not sure that it's really a goal for the SDKs to be aligned in this sort of way. There's so many differences between languages that I think we more need to accept that names, syntax, etc. are going to be different and just rely on good documentation existing for all the official SDKs so authors always know how to write modules in each one.
> 
> E.g. even if we are consistent in `dagger` vs. `dag` we can't be consistent in other things like casing (`.WithExec` vs. `.with_exec`), how options are provided, etc. And at that point does `dagger` vs `dag` really matter that much?
> 
> That being said, I do like `dag` more just because it's shorter to type 🙂, so if @helderco thinks this is a very easy modification to make then I'd say lets do it, but as a one-off improvement to Python rather than an effort to keep SDKs perfectly aligned around issues like this.

Yep, I'm aware that we can't make everything the same and we're going with a "when in Rome" approach to keeping things language-idiomatic, but as the title of the issue hopefully suggests, I just meant choosing one of `dag` or `dagger` if possible to avoid user confusion. If it's not possible or advantageous, then yes we can document it, but I prefer it when certain anchor items like this feel like they are part of one DX.

**Comment by sipsma** [comment]
> Yep, I'm aware that we can't make everything the same and we're going with a "when in Rome" approach to keeping things language-idiomatic, but as the title of the issue hopefully suggests, I just meant choosing one of `dag` or `dagger` if possible to avoid user confusion. If it's not possible or advantageous, then yes we can document it, but I prefer it when certain anchor items like this feel like they are part of one DX.

Totally, I think we're on the same page 👍 I just wanted to be very explicit that, going forward for SDKs in general, I don't personally want something like this to be a *requirement* or something that's worth jumping through hoops for. But I agree that if use of `dag` as the name of the client variable is "free" (in terms of dev effort, DX for the particular SDK, etc.) then yeah let's do it.

**Comment by helderco** [comment]
@TomChv has already adopted `dag` as part of https://github.com/dagger/dagger/pull/6118. Python coming soon. It's a breaking change but I haven't seen anyone using the default client since it's not in any docs.
