### ISSUE TITLE
Improve error messages from “embarrassing” to “bearable”

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#613]
## Problem

The `dagger` runtime produces errors that are confusing and difficult to act on. This makes the developer experience considerably worse.

## Solution

Make `dagger` runtime errors clear and easy to act on. This will make the developer experience considerably better.

Please *AVOID SILVER BULLETS*.

As engineers it is tempting to prioritize our own satisfaction, by looking for a silver bullet: a neat, technically challenging fix that will solve the problem while keeping the code clean and elegant.

Don't do this. Your satisfaction as an engineer does not matter. Instead, prioritize reducing the suffering of our users. This means looking for *real world data* on errors *actually experienced by users*, and making those errors less painful. If that means manually detecting each individual error, with a long switch-case statement that makes you feel dirty inside... so be it. If it reduces user suffering, it's worth it. Of course, over time we will find opportunities to generalize solutions, refactor, etc. But don't worry about that for now. Our users are suffering! Find the shortest path to reducing the pain, and the rest will work out.

## Related issues

Below is a list of related issues, documenting specific instances of a confusing errors. If you have a related issue to contribute (the more the better!) please write it in a comment.

- [x] #1572
- [ ] #1426
- [ ] #1478
- [x] #402
- [x] #2044
- [x] #2056
- [x] #2146
- [x] #2079 
- [ ] #2303
- [ ] #2304
- [x] #2279
- [x] #493
- [ ] #2180

**Comment by aluzzardi** [comment]
@helderco catalogues a few of those here https://github.com/dagger/dagger/issues/493#issuecomment-1086120601

I don't know if we should merge everything over this issue or not

**Comment by helderco** [comment]
> @helderco catalogues a few of those here [#493 (comment)](https://github.com/dagger/dagger/issues/493#issuecomment-1086120601)
> 
> I don't know if we should merge everything over this issue or not

That issue tracks side effects of an upstream issue: incomplete errors. It may be possible to solve some or all of that on our side (thanks to https://github.com/dagger/dagger/pull/2266, for example), especially since we don't know if there'll be a fix upstream (_NeedsInvestigation_ in https://github.com/cue-lang/cue/issues/629).

For that reason, I think it's a good idea to merge here anything we can solve ourselves, spliting the list into categories. And keep another which require a solution from upstream (maybe https://github.com/dagger/dagger/discussions/857). As for #493 itself, maybe rename to the more specific side-effect of importing non-existent definitions from a package.

**Comment by sdboyer** [comment]
Just want to note here, since this popped up in my feed - i've begun the process of improving errors in Thema. Tracking it in grafana/thema#44, and took a first whack at it (very hacky sketchy) in #grafana/thema#45.

Thema's use case is plausibly easier than Dagger's because the additional constraints we impose on user input allow us to make assumptions that don't hold in more general CUE error handling. But...wasn't as bad as i was expecting :)

**Comment by ivorscott** [comment]
https://github.com/dagger/dagger/issues/2180

**Comment by mircubed** [comment]
@dolanor removing you as assignee since you are working on another issue. Once we have a new assignee, we can scope this issue down into clear actionable tasks.
