### ISSUE TITLE
Need equiv of include / exclude for directories with `dagger call` CLI

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#6155]
An idea that has been looked at (and rejected) in the past are a `dagger.ignore` file.

Other approach could be to use some sort of include / exclude patterns on CLI, though it may be verbose/complex DX.

Another approach could be a top-level "main" module that had host filesystem access and include/excludes could be used there. cc @vito

Could also be a "filter" that could be applied at any point on a loaded directory. `filtered_dir = dir.with_exclude_filter("*.json")`

**Comment by jpadams** [comment]
From @cirocosta:
on ignoring/excluding, reminds me of how sometimes taking the "we'll default to following .gitignore" ends up annoying some users: https://github.com/ggreer/the_silver_searcher/issues/1189

**Comment by jedevc** [comment]
> ignoring/excluding, reminds me of how sometimes taking the "we'll default to following .gitignore" ends up annoying some users

As a quick and easy idea, we could potentially re-use `.dockerignore`/`.containerignore` if it's present? It's a bit more standardized around the container ecosystem.

But I'm a little hesitant about that, `.dockerignore` is kind of a bit of a mess, I don't really want to propagate it's usage any more than we have to.

> Could also be a "filter" that could be applied at any point on a loaded directory. `filtered_dir = dir.with_exclude_filter("*.json")`

I think this approach makes the most sense. We could actually just re-purpose `.WithoutFile`/`.WithoutDirectory`, which means we can avoid having to add any extra APIs, or any extra files across a filesystem.

However, as-is, these files will still be uploaded, and then removed.

What we could do though, is allow optimizing the produced LLB from a local `SourceOp` + `FileOp` into a single local `SourceOp`, by detecting if the `FileOp` is attempting to just remove files, then we can add those into the `ExcludePatterns` of the `SourceOp`. This might be easier to implement at the Dagger level instead of directly at the LLB level (but if we could do it at the LLB level, it would also affect other places as well, like in `.DockerBuild`).

I don't think there's any tooling in buildkit to allow easily mutating LLB for optimization passes at the moment though, so this would probably be a bit of an effort if we were to take that approach.

**Comment by sagikazarmark** [comment]
This just became a lot more pressing given `dag.Host().Directory()` is gone. There is no way now to exclude directories/files from being uploaded to buildkit. This adds to build time anywhere between 1 minute to 3-5 minutes in my case.

**Comment by jedevc** [comment]
Gonna chuck this onto the v0.10.0 milestone, since agreed, this now there's no workaround at all!

**Comment by helderco** [comment]
I want to see this at multiple levels, not just one option.

## 1. Global exclude

Similar to git global excludes:

```
dagger config --global add exclude "**/.direnv"
```

Saved in `$HOME/.config/dagger/dagger.json`. `add` instead of `set` for lists, and this command would support other global configs, like passing through proxy env vars, for example.

## 2. (Maybe) “project” specific excludes

I also wonder about using `.gitignore`, `.dockerignore` or `.daggerignore`. Similarly to how the engine loads modules by finding all `dagger.json` files first to get the `"exclude"` configs before loading the rest, it could also find `.<dagger™>ignore` and do the same in `dag.Host()` (perhaps with an option to trigger this behavior). Or in this case, do it in the CLI and pass explicitly to `HostDirectoryOpts()`.

The CLI could also read the next-up `dagger.json` (if exists) and get the list of patterns to use in `HostDirectoryOpts`, however I’m not sure if it’ll clash with the intent that these are used for setting up the context directory (`/src`) in the runtime container, for a module. Possibly ok if a path in a `--src` flag is within the `dagger.json` tree and the patterns in there are generic enough.

For example, in a git root:
```
dagger init
dagger use <awesome module>
dagger config add exclude "./tests"  # add to ./dagger.json
dagger -m awesome call --src=. lint
```
## 3. Extra CLI flags

This is the most specific (from CLI POV), and overrides anything from before.

When a function argument is `src *Directory`, the CLI currently adds a string flag `--src` to convert a path into `dag.Host(path)`. We could add more flags (for any input where the function has options):

```
--src         string
--src.include []string
--src.exclude []string
```

Note: I considered `--src-exclude` but that could clash with a `srcExclude` argument, and is better than an extra char in `--src--exclude`. Not fond of a custom format like `--src=.,**/*.py`.

So:
```
dagger init
dagger use <python module>
dagger use <go module>
dagger -m python call lint --src=. --src.include="**/*.py`
dagger -m call go lint --src=. --src.include="**/*.go`
```

Of course this makes the CLI command bigger, but we’re already trending towards that with [explicit env vars](https://github.com/dagger/dagger/issues/6112), etc, so that’s where we benefit from a config with defaults to run a module’s commands (consume, not author), like above with `dagger config` or something similar.

## 4. Inside function

I also think there’s value in being able to exclude a bunch of files from a `Directory` instance, for example from a function argument. In the previous example, the go and python modules know which kind of files matter for what they need to do.

Even though more files may have been uploaded anyway, it still helps with cache invalidation. So if you have a dir with go and python files, the cache in go lint won’t be invalidated if python files have changed.

**Comment by vito** [comment]
Can we implement this in a way where it's all done at runtime? I was able to get away with that in Bass and the semantics felt super nice - you could basically take any path and dynamically narrow it down to include/exclude globs, and all the cache busting/file syncing semantics work as you would hope:

* [https://bass-lang.org/stdlib.html#binding-glob](https://bass-lang.org/stdlib.html#binding-glob)
* [https://bass-lang.org/stdlib.html#binding-only-globs](https://bass-lang.org/stdlib.html#binding-only-globs)
* [https://bass-lang.org/stdlib.html#binding-except-globs](https://bass-lang.org/stdlib.html#binding-except-globs)

The trick to implementing this is that you need to defer the actual file syncing to as late as possible.

The end goal would be that the user just passes in a path like `./` and the module itself narrows that path down to different glob filters when needed. This is especially useful if there are different permutations of filters that you need at different times.

(This would be different from the module source dir include/exclude which is necessary for bootstrapping without uploading everything.)

**Comment by jedevc** [comment]
> Can we implement this in a way where it's all done at runtime?

This would be my preferred place to start (point 4 above), and then work upwards (points 3, 2 and 1).

Modules should have *some* idea about what their contents are (e.g. a go module is looking for go code) - so they should have some idea of what to filter. The end-user shouldn't be required to guess what a module is doing, and so what files are safe to include/exclude.

However, it does feel a bit tricky - we need to lazify the loading. Today, we call `LocalImport` immediately on calling `Host.directory` (which gets called by the CLI when encountering a directory flag): https://github.com/dagger/dagger/blob/fca9e788f6d605ef9d256beace4656c11d7f6fe5/core/host.go#L77-L84

There's a few ways of "filtering" today:
- Copy into an empty directory using `withDirectory` with `include`/`exclude` filters
	- Potentially, we could have a new `filter` method as a shorthand for the above? We have `glob` today (but it returns a list of files).
- Manually call `withoutFile`/`withoutDirectory`
	- Just noticed, we don't have `withoutFiles` - we might want this as a follow-up to #6475.

We'd probably want both of these to "squash" onto a lazy loaded directory, and modify the filters for that operation. To do this, we could add a new `lazy` property to the `core.Directory` object, and then ensuring it's evaluated before actually accessing it, and then the above operations could instead modify the parameters.

> [!NOTE]
>
> :bulb: We could *potentially* do this using [`llb.Async`](https://github.com/moby/buildkit/blob/47d6583cdf58b952c3cb9c719f2f9b45be825c1f/client/llb/state.go#L120), which could be quite be an elegant way of resolving this (but would need to hack around to see).

**Comment by sagikazarmark** [comment]
> Modules should have some idea about what their contents are (e.g. a go module is looking for go code) - so they should have some idea of what to filter.

Wouldn't that go against the "module is a sandbox" idea?

Filtering can very much be an environment specific thing (eg. I have a tmp folder with all kinds of BS in it that could break `go test ./...`, so I want it excluded, but the module developer (eg. platform eng. team) may not expect that)

My preference would be a .daggerignore file (or something similar) as a start. It's an easy concept and easy to expand on (eg. allow other ignore files from a global dagger config, global ignores, etc)

**Comment by vito** [comment]
@sagikazarmark 

> Wouldn't that go against the "module is a sandbox" idea?

It's probably true that general-purpose modules like Go shouldn't do their own filtering unless they do it in a way that's 100% airtight for whatever hyper-specific thing they're trying to do.

What I have in mind are project-specific modules which tend to be _acutely_ aware of what files they want and can use that domain-specific knowledge to get very precise control over cache-busting, e.g.:

* https://github.com/vito/bass/blob/ddb30dd511bebfda157d91a72492fd879d2d58c3/bass/bass.bass#L25
* https://github.com/vito/bass/blob/ddb30dd511bebfda157d91a72492fd879d2d58c3/bass/bass.bass#L58-L68

```clojure
        (cd (glob src ./nix/ ./flake.nix ./flake.lock ./default.nix)
          ($ nix build ".#depsImage"))
```
```clojure
  (defn go-files [src]
    (glob src
          ./**/*.go
          ./**/go.mod
          ./**/go.sum
          ./std/*.bass
          ./pkg/bass/testdata/**/*
          ./pkg/runtimes/testdata/**/*
          ./pkg/lsp/testdata/**/*
          ./Makefile
          ! ./hack/vendor/))
```

If I had to put this in a `.daggerignore` I would probably just be too lazy. The `.daggerignore` approach would also force all consumers to ignore those files in all contexts which is not always what you want. I'm not a huge fan of `.ignore` files here for that reason. The potential use cases for including/excluding certain files are way more open-ended than with `.gitignore` ("don't commit to .git"). Even `.dockerignore` had this issue in my experience.

**Comment by shykes** [comment]
Here's my proposal: **we make include/exclude a hidden optimization of the standard Directory API**.

*(As discussed with @vito on Discord today)*

* When a host directory is created (eg. when the CLI passes a `Directory` argument to a function by loading a local directory), the engine defaults to excluding everything. This effectively makes the host directory lazy: nothing gets loaded right away.
* As that directory is used by the function, it may be narrowed down with subsequent calls to `Directory()`, `File()`, or `WithoutDirectory`. When applied to a host directory, this would lazily change the applied include/exclude filters.
* Globbing support would be either retrofit into existing directory functions (eg. a new `Glob: true` option to `WithoutDirectory()`), or implemented as new functions (eg. `Directory.Filter()`).
* In all cases, the key is that everything would be done via functions that apply to the `Directory` type, whether or not it is backed by `llb.Local()` aka `Host.Directory` or not.
* In the end, when the resulting directory is finally used (`WithExec`, `Terminal`, `AsService.Start()`...), then the include/exclude are finally applied.

Benefits of this approach:

1. No CLI changes
2. No dagger.json changes
3. No new file formats
4. Might magically optimizes a bunch of existing functions. Every time your function receives a directory from the caller's local filesystem, and doesn't use all of it, it will get faster.

Downside:

1. Maybe difficult to implement?

Thoughts @jedevc @helderco @vito ?

**Comment by jedevc** [comment]
> Here's my proposal: **we make include/exclude a hidden optimization of the standard Directory API**.

Agreed, I think this is what I was aiming at above (but maybe didn't explicitly say). I hadn't thought about *all* the ways to narrow things down though that you listed (thankfully, if we miss one, we get slightly more inefficient transfers, instead of incorrect results).

Agreed on all the benefits as well :tada:

> Maybe difficult to implement?

I actually think this might be quite doable, see my above comment for some implementation ideas.

---

I have thought about an interesting "edge" case (I don't actually think it's an edge case), that might complicate things - partially writing this down for my own benefit as well.

Suppose I get a `Directory` in my module function, and then select some files from it and force a transfer using `Sync`.

```go
// this can be optimized to only upload the contents of "foo" from the client
dag.Directory().WithDirectory("/", hostDir, DirectoryWithDirectoryOpts{
	Include: []string{"foo"},
}).Sync()
```

Now imagine, later (perhaps even in a different session), I request these files, *plus* some new files:

...
dag.Directory().WithDirectory("/", hostDir, DirectoryWithDirectoryOpts{
	Include: []string{"foo", "bar"},
}).Sync()
```

The problem is, this is now a "new" request - and so we'll end uploading "foo" *again* even though we already have it (and creating a new blob, though I guess this is actually less of a worry). Note, this request is made "new" using `SharedKeyHint` - if you leave this out, file transfers can accidentally overwrite each other, which can cause huge corruption.

Maybe this isn't that much of an issue for a first pass - but it's definitely something we'd want to resolve long term (potentially, even upstream in buildkit). Ideally we want `LocalSource` to have a concept of a "long-term store" - even if files are requested multiple times for a buildkit session (using different `SharedKeyHint`s), we should only request them once, and store them in a long-term store perhaps even using hardlinks (and manage concurrent requests using flightcontrol).

Trying to work around this is maybe possible but probably involves a lot of dancing around the fsutil protocol, and maybe even re-implementing the local source? Not a huge fan of that, since that increases the scope of this.

Is there something I'm missing here that maybe just makes all this really easy actually, and means we don't have this problem? @vito do you do anything clever here in bass?

**Comment by vito** [comment]
@shykes Sounds good, yes it would be very nice if we could get that to work. My biggest worry would be finding a case where we can't detect the need for a path filter because a required path is never actually mentioned through the API, but to the user it feels obvious that it should be included. Can't think of a concrete example that wouldn't already be broken without this optimization though.

@jedevc I didn't have to do anything clever there in Bass because it places the onus on the user to just explicitly call `(glob)` wherever you want to apply filtering, and I only ever needed to apply it in a couple of key spots (dev base image building + source code loading) which acted as high level inputs to everything. Seems like that could still be the escape hatch in awkward scenarios like that one.

**Comment by shykes** [comment]
> @shykes Sounds good, yes it would be very nice if we could get that to work. My biggest worry would be finding a case where we can't detect the need for a path filter because a required path is never actually mentioned through the API, but to the user it feels obvious that it should be included. Can't think of a concrete example that wouldn't already be broken without this optimization though.

Yeah, we should assume that will happen. I think if we default to including everything, then at least the worst case is that you upload more than you thought. Which is better than uploading less than you thought.

For a simplistic example:

```go
func ListDir(ctx context.Context, dir *Directory) (string, error) {
 return dag.
  Container().
  From("alpine").
  WithMountedDirectory("/dir", dir).
  WithExec([]string{"ls", "/dir"}).
  Stdout(ctx)
}
```

This will (obviously) upload everything:

```shell
dagger call list-dir --dir=.
```

**Comment by shykes** [comment]
Sorry @jedevc if I just repeated what you were already saying.

**Comment by sipsma** [comment]
I understand the appeal of the idea but there's at least one conundrum I'm not sure how to deal with and a longer trail of issues that could be dealt with but only with a lot of effort.

The one I don't know how to deal with is caching. We've simplified host directories to use a content-based cache key (via the `blob` source). This impacts the caching of function invocation when these directories are used as arguments.

So then say you provide a host directory as an argument to a function invocation. We haven't loaded it yet so we don't know the content based cache key. 
* We could probably calculate it, but that would require almost as much work as actually loading the entire thing.
* It also wouldn't be a cache key based on what the user actually wants to use but instead based on the entire unfiltered directory.

I really don't see any way of dealing with this other than allowing the user to specify include/exclude at invocation time. We could just always invalidate cache when any of these directories are used, but that's a surprising and unfortunate performance tradeoff of its own that does not feel worth it to me.

I think we should just support a syntax or configuration for specifying those at that time. It's only going to be needed for advanced use cases, so I don't think it's a ton to ask. And for those advanced use cases, users are going to care about getting optimal behavior in terms of performance/caching, so I think it's worth going with the approach that will get them that.

---

For the record, the various other issues that are tricky revolve around how buildkit local filesync works. 

A lot of the issues center around the fact that local imports work by storing a persistent mutable snapshot key'd with an identifier, which is supposed to be relatively stable for a given caller+path ([code](https://github.com/moby/buildkit/blob/fdd2b2ee19418f0c46e63ec01c3f827dd090e968/source/local/source.go#L178)). But the devil shows up in the details:
1. If the buildkit solver tries to use the same local import snapshot in parallel, it just creates an entirely new snapshot and reloads the entire dir ([code](https://github.com/moby/buildkit/blob/fdd2b2ee19418f0c46e63ec01c3f827dd090e968/source/local/source.go#L190-L192)). This will show up in fairly mundane situations even when the user is not explicitly using parallelism due to lazy evaluation (e.g. user builds up queries that use the local source in multiple parts of the DAG and ends up evaluating that)
2. That mutable snapshot is a single layer, so different uses of include/exclude on the same dir will overwrite each and result in repeated loading of the same files.

Those problems will result in significantly worse performance relative to just allowing the user to specify include/exclude at the time the directory is loaded. They also would show up in pretty mundane usage scenarios; not obscure at all while also hard to predict/understand.

I've talked to Tonis in the past about various ways of dealing with these issues (via more clever layering and "hardlink-farms") but they would amount to almost an entire re-write of local source imports.

**Comment by jedevc** [comment]
> The one I don't know how to deal with is caching. We've simplified host directories to use a content-based cache key (via the `blob` source). This impacts the caching of function invocation when these directories are used as arguments.

Hm, this is a good point - the function itself wouldn't be able to cache if we do this lazying.

> For the record, the various other issues that are tricky revolve around how buildkit local filesync works.

I think this is what I was alluding to in the second half of https://github.com/dagger/dagger/issues/6155#issuecomment-1945856755. I do *wonder* if maybe the chance of overlaps is low enough, that potentially we could ignore that and just have separate `SharedKeyHints` for each snapshot - with the risk that maybe some files could be uploaded twice. Undecided on whether this would be a net performance increase, or net performance decrease.

I also thought about "hardlink-farms" (love the name), and I do think that would be worth upstreaming - you can also hit this case easily enough with Dockerfile `RUN` mounts, it makes me reasonably confident that a patch would be welcome - but yes, that's probably a whole rewrite.

\<tangent>

I've also discussed a similar topic with Tonis in the past, and I remember we discussed an idea to have a client-computed content cache-key (which if done right, could avoid us needing to have a blob source at all). If we could have a client-side computed cache key (essentially, with the guarantee that when a file changed, the key changes to a new value). The problem is working out how to do this in an efficient way.

A super-naive implementation would just be a checksum over a directory (but this is very slow) - that could be made faster using a cache, or we could re-use something like `git-write-tree`. There's also some potential filesystem magic that could be used, like fs-verity for supported kernels.

\</tangent>

---

Given the timeline for v0.10.0 involved, I'm kind of convinced we don't have time to make reasonable progress on the "hard" automagic solutions above.

Maybe we could go for @helderco's point 3 as a stop-gap, then aim to come back and fix this automatically later down the line:

- `--src.include`/`--src.exclude` flags become available when `src` is a directory flag.
- `--src.ignorefile` could be used to use a `dockerignore` syntax file - that way we don't enforce our own custom `daggerignore` file, but we give users some flexibility if they want to do that.

That feels much more feasible for the v0.10.0 timeline, and should *hopefully* unblock us starting to use this with our own CI (but sadly, does mean extra CLI flags).

**Comment by sipsma** [comment]
> I do wonder if maybe the chance of overlaps is low enough, that potentially we could ignore that and just have separate SharedKeyHints for each snapshot - with the risk that maybe some files could be uploaded twice. Undecided on whether this would be a net performance increase, or net performance decrease.

I think it would depend on the case, but the main consideration for me is that all of this is meant to be a performance optimization in the first place, but if it's actually just making some cases faster and some cases slower, we're not really achieving the goal.

> I've also discussed a similar topic with Tonis in the past, and I remember we discussed an idea to have a client-computed content cache-key

Right, the other requirement besides the one you mentioned would be making it work+be fast on every platform clients can run on (linux, macos, windows), which really explodes the complexity since performance optimizations will start getting into OS specific details in all likelihood. If there was magically some existing library/tool that could do this for us, then it is much closer to the realm of practicality. `git` is tempting I agree, but this needs to work on dirs that aren't necessarily in a git repo.

> --src.include/--src.exclude flags become available when src is a directory flag.

This would be my vote of the options brought up so far.

I would also add the option of `--src=/some/dir,include=*.foo,exclude=/some/dir/bin`. It doesn't handle to outrageously obscure corner case of filepaths that actually have `,include=...` in them, which is technically not an invalid path, but it's fairly common to not handle obscure file path names like that (i.e. files/dirs with `:` break when used in `PATH`, etc.). So I kind of like that one even more since it's a bit more compact. But not so much more than `--src.include` that I'd advocate strongly for one over the other.

**Comment by helderco** [comment]
Instead of two separate include and exclude flags, we can also collapse under a single "patterns", where if it starts with a `!` it's an exclude, like @vito suggested:

```
--src=/some/dir,*.foo,!bin
```

The reason I leaned more on the separate flags is because it could be a general solution for any flags using a constructor (like `dag.Host`) with optional arguments. But we've mostly found a "special syntax" for those cases (like PortForward or Service).

**Comment by sipsma** [comment]
> Instead of two separate include and exclude flags, we can also collapse under a single "patterns", where if it starts with a ! it's an exclude

Oh yeah, makes sense, that would be my vote now 😄

**Comment by sagikazarmark** [comment]
Here is the list of directories I exclude currently from being copied:

```
	".direnv",
	".devenv",
	"api/client/node/node_modules",
	"assets",
	"ci",
	"deploy/charts/**/charts",
	"docs",
	"examples",
	"tmp",
```

With the above proposed solution it's not gonna be very convenient.

**Comment by sipsma** [comment]
@sagikazarmark I hear you, I think this is just another instance of the more general problem of too many args becoming tedious to use by hand. I made an issue collecting together the various ideas we've had around it here: https://github.com/dagger/dagger/issues/6723

Also added it to `v0.10.x` so we should get to it soon since I think it's becoming a pretty pressing issue.

**Comment by shykes** [comment]
Throwing one option out there: what if optionally `dagger.json` had an `ignore: [String]` field? To specify what to ignore by default when passing that directory as an argument. Would be cleaner than having a separate ignore file.

**Comment by shykes** [comment]
> Throwing one option out there: what if optionally `dagger.json` had an `ignore: [String]` field? To specify what to ignore by default when passing that directory as an argument. Would be cleaner than having a separate ignore file.

Since we don't plan on making it a CLI flag long term (because it can be optimized away in due time), it seems like a cleaner and easier stopgap to just have fields in dagger.json and call it a day.

**Comment by sipsma** [comment]
> Works for me, although I think it would be easy to confuse with exclude that AFAIK is still a valid option

Yeah I don't know how to square that with `include`/`exclude`. I also think it's more limiting in that you can't customize individual directory args with different includes/excludes, which seems like a fairly mundane need.

I like starting with the most flexible option and then layering conveniences on top. I think https://github.com/dagger/dagger/pull/6701 + https://github.com/dagger/dagger/issues/6723 will leave us in a pretty good place in terms of flexibility and UX.

> Since we don't plan on making it a CLI flag long term (because it can be optimized away in due time)

This is true, but I want to emphasize that the changes needed to do this are a pretty substantial project and, IMO, not 100% guaranteed to even be totally viable in terms of getting the same performance as having users specify include/exclude flags up front. It's a fairly fundamental rewrite of how buildkit local dir syncs work from the ground up. So we shouldn't assume it's something that we can just easily prioritize or do in the background iteratively. I think we should assume that the solution we go with for now is more than just a temp bandaid.
* I'd be delighted to be completely wrong about this though of course. If we can find a way to glue together off-the-shelf tools to help implement it, maybe it can be quicker.

**Comment by sagikazarmark** [comment]
> I like starting with the most flexible option and then layering conveniences on top. I think #6701 + #6723 will leave us in a pretty good place in terms of flexibility and UX.

I have to disagree. Flexibility isn't the first word that comes into mind about those two PRs. To me, the combination of those two are way too complex to solve a seemingly trivial problem in the context of monorepos.

Regardless of the counterarguments, a file like `.daggerignore` seems like a much easier solution from a user experience perspective. Arguments + some arbitrary scripting interface can hardly be called "simple" compared to that in my opinion.

It seems to me that a generic enough solution covering all cases takes priority in this conversation over UX. I'd much rather use something today that covers 80% of the use cases (AND provides a decent UX) and change it later if something better comes along.

**Comment by sipsma** [comment]
I'm not opposed to `.daggerignore` and it's not mutually exclusive with the other solutions at all. But I predict that someone will soon ask "how can I use different filters for different directory args when using `dagger call`?". As one example, in a monorepo maybe you want to provide a directory for a node project in the repo (in which case you only need `.js`/`.ts`/etc. files) and other times you want to provide a directory for a go project (only need `.go`/`go.mod`/etc.). At that point a single `.daggerignore` that applies to all directory args is not gonna cut it.

I generally like going "bottom-up" with something that would cover more like 99% of cases and then layer sugar on top that makes some other subset of cases more convenient (which is what I'd view `.daggerignore` as). I think that often results in something more cohesive once all is said and done. But you're right we could go "middle-out" and start with `.daggerignore` and fill in the rest later, which could make sense since I'm sure you and others would prefer to stop the bleeding sooner than later. I just would want to make sure we have a plan on supporting the rest of the cases mentioned above.
* It could be as simple as starting with `.daggerignore` and then adding the per-flag filtering later, with the behavior being that `.daggerignore` is not applicable when per-flag filters are set. Curious what others think. There's plenty of other variations possible too (e.g. specify separate `.daggerignore` format files per-flag).

**Comment by shykes** [comment]
@sagikazarmark @sipsma @jedevc @helderco summarizing the different options and problems.

| Idea | Problem |
| -- | -- |
| Make it all explicit in the command-line | That's a very long command-line for @sagikazarmark |
| Create a new `.daggerignore` file | 1) One more file.. 2) "how can I use different filters for different directory args"? |
| Create a new `ignore` field in `dagger.json` | "What's the difference with `include/exclude` fields?" |

How about this:

- New optional field in `dagger.json`: `views`.
- A view of a directory is simply an include/exclude filter applied to that directory
- A view has a name. It can be reference from the CLI with a simple syntax: `PATH:[VIEW]`
- If there is only one view, it is used by default

Example:

```shell
$ cat dagger.json
{
 [...]
 "views": {
  "default": {
   "exclude": [
    ".direnv",
    ".devenv",
    "api/client/node/node_modules",
    "assets",
    "ci",
    "deploy/charts/**/charts",
    "docs",
    "examples",
    "tmp"
  ]
}
```

There is only one view, so it is applied by default:

```shell
$ dagger call build --source .
```

The view can be applied explicitly also:

```shell
$ dagger call build --source .:default
```

The view is also applied when calling functions from another module (`dagger.json` is parsed when loading a local dir as argument, regardless of calling module):

```shell
$ dagger -m github.com/kpendgound/golang --project .:default
```

Things I like about this option:

- @sagikazarmark doesn't have to type super-long commands, and rely on wrappers
- No new file
- We keep the existing include/exclude logic. Less new code to implement, document and debug
- We still add special syntax to the CLI argument, but it's much simpler.

Thoughts?

**Comment by sagikazarmark** [comment]
Works for me. UX is good enough for me.

**Comment by sipsma** [comment]
Yeah `views` makes sense to me too, seems like a good middle ground 👍 (cc @jedevc, who had an initial PR for the other approach https://github.com/dagger/dagger/pull/6701).

I've also had some more thoughts on the idea of allowing users to write dagger code that runs on the host and calls out to modules ([here](https://github.com/dagger/dagger/issues/5993#issuecomment-1965307584)), which hopefully could solve the more general problem here. But not mutually exclusive with `views` at all.

**Comment by jedevc** [comment]
I think `views` makes sense, but to me, I'd like to suggest a way to improve it a bit further :tada:

Could we allow annotating (in go, using the `// +pragma`s) function inputs with a default view? For example, in my attempts to modularize our CI (https://github.com/jedevc/dagger/blob/f997c2a9d571182aa81484a76bc17112fd692adc/ci/util/sdk.go#L49-L67), I might have a directory input to generate the typescript SDK - by default I want to apply that view, but it could also work on other views.

Ideally, I want users to just be able to call the module without *needing* to know all the different views that are provided.

**Comment by sipsma** [comment]
Draft PR for the basic idea here: https://github.com/dagger/dagger/pull/6857

**Comment by sagikazarmark** [comment]
YES! 🎉
