### ISSUE TITLE
Go SDK: support pre-connected global `dag` client outside of Modules

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#6289]
In Modules using the Go SDK you get a pre-made dagger client called `dag` that's ready to use at init.

For non-module Go SDK code (i.e. SDK code that runs directly on a caller's host), you still have to explicitly create a dagger client with `dagger.Connect` and use that.

We should retain support for `dagger.Connect` since it has useful options like configuring the destination of log output that users may sometimes want to customize. However we can also add support for a pre-configured client that's ready to use. This would be generally a nice convenience and help shorten the gap between module and non-module code.

One option would be to add a subpackage to the SDK like `dagger.io/dagger/dag`, which has functions setup so that you can call e.g. `dag.Container().From(...)` and use a default pre-connected client. This would result in code that looks fairly similar to module code.

**Comment by jedevc** [comment]
One thing I noticed - the functions/variables that users write will also take some changing to adapt to modules.

For example, I might write a function today that looks like:

```go
func Foo() *dagger.Container {
```

But with modules, since the `Container` type is in the same package, it looks like:

```go
func Foo() *Container {
```

I think we should probably also look to address this at some point - we can't the SDK patterns today, but we could change how the go module SDK generates code. If we could put `dagger.gen.go` into it's own package for modules (e.g. `dagger/dagger.gen.go`, but keeping the `dag` variable in a top-level `dagger.gen.go`), then these styles become the same.

This would be quite a rework of the Go modules - we could ease transition though by using the top-level `dagger.gen.go` to alias various types though, while allowing a nice transition into modules. WDYT @sipsma @vito?

**Comment by sipsma** [comment]
@jedevc Yeah I would like to make that change for sure. Would solve all the various problems that arise when we add variables or functions to `dagger.gen.go` that conflict with other types and all that 👍
