### ISSUE TITLE
Error: unknown command "project" for "dagger"

### ISSUE THREAD

**Issue by JCzz** [dagger/dagger#6290]
Env:
dagger version
dagger v0.9.4 (registry.dagger.io/engine) darwin/arm64

From documentation
https://archive.docs.dagger.io/0.2/1200/local-dev
it says:
```
git clone https://github.com/dagger/todoapp
cd todoapp
dagger project update
dagger do build
```

But  get error:
dagger project update
Error: unknown command "project" for "dagger"
Run 'dagger --help' for usage.

**Comment by helderco** [comment]
You're seeing documentation for the archived **0\.2** version (notice URL: https://archive.docs.dagger.io/**0\.2**/1200/local-dev), but you're using version **0\.9**.4. See notice on top of page:

![Screenshot 2023-12-19 at 10.33.41.png](https://uploads.linear.app/0b2a9228-3827-45ff-bb20-ccd34f57f694/1073c396-1d72-4eea-8c36-86319f2201a1/c5f4721b-2a07-49d6-8018-23ee0d45106d)


You can find the updated getting started guide at:

[https://docs.dagger.io/quickstart/120918/setup](https://docs.dagger.io/quickstart/120918/setup)

@vikram @jf, the notice at the top should probably be in a red tone, right? At first glance my eyes skipped it, only looked more closely because I knew it was an outdated doc and *there had to be a notice somewhere*.

**Comment by helderco** [comment]
@JCzz Let us know if you have any more issues 🙂

**Comment by JCzz** [comment]
Thanks, that worked. Looking forward to play around :-)

**Comment by vikram-dagger** [comment]
> > @vikram-dagger @slumbering, the notice at the top should probably be in a red tone, right? At first glance my eyes skipped it, only looked more closely because I knew it was an outdated doc and _there had to be a notice somewhere_.
> 
> Correct, the banner should not be blue 👍 ! I would go for orange (a warning color). 

Updated on [archive.docs.dagger.io](https://archive.docs.dagger.io/0.1/) and https://archive.docs.dagger.io/0.2/
