### ISSUE TITLE
🐞 Seeing `CLI_VERSION = "0.9.5"` in python and typescript SDKs after `dagger mod init` or `sync`

### ISSUE THREAD

**Issue by jpadams** [dagger/dagger#6415]
### What is the issue?

Seeing `0.9.5` where I'd expect `0.9.6`. Functionality of Python and Typescript SDK seemed like `0.9.5`.

When creating a new module via `dagger mod init` or updating a module with `dagger mod sync`, under `dagger` CLI `0.9.6` I'm ending up with files like

python:
`sdk/src/dagger/_engine/_version.py`

```
# Code generated by dagger. DO NOT EDIT.
 
CLI_VERSION = "0.9.5"
```

typescript:
`sdk/provisioning/default.ts`

```
// Code generated by dagger. DO NOT EDIT.
export const CLI_VERSION = "0.9.5"
```

Guessing that's not expected or desired since I see `0.9.6` in GitHub:
[https://github.com/dagger/dagger/blob/main/sdk/python/src/dagger/\_engine/\_version.py](https://github.com/dagger/dagger/blob/main/sdk/python/src/dagger/\_engine/\_version.py)
[https://github.com/dagger/dagger/blob/main/sdk/typescript/provisioning/default.ts](https://github.com/dagger/dagger/blob/main/sdk/typescript/provisioning/default.ts)

I suspected something when I wasn't getting the new secrets env var behavior I expected from `0.9.6` with the Python SDK.

### Dagger version

dagger v0.9.6 darwin and windows arm64

### Steps to reproduce

`dagger mod init --name foo --sdk python`
or
`dagger mod init --name foo --sdk typescript`

```
grep -r 0.9.5
```

### Log output

python:

```
CLI_VERSION = "0.9.5"
```

or
typescript:

```
export const CLI_VERSION = "0.9.5"
```

**Comment by jpadams** [comment]
Maybe this isn't a bug, but just the way things are put together...?

<img width="1136" alt="image" src="https://github.com/dagger/dagger/assets/3187222/734b5f49-9a1f-4cab-9f9f-d374108c527d">

**Comment by helderco** [comment]
It's not a bug but I see how it can be confusing. We could do something about it but it's low priority. 🙂

What happens is that the Python and Typescript SDKs are bundled in the engine image just **before** cutting a CLI/engine release. Then right **after** that's released we bump these `CLI_VERSION` values to the new release and proceed to release the SDKs for **non-modules**.

So there should be no difference in SDK code between the `v0.9.5` that you see after `dagger mod sync`, and its next bump to `v0.9.6` since the only thing that happens in between is just the bump and SDK release (non-module).

We could try to bump them as part of the CLI/engine release, even though at that point the release hasn't been made yet, or do it as part of codegen during `dagger mod sync`, but I don't think it's worth the trouble.

You don't see it in Go (it's `CLIVersion`) because Go's codegen generates a single `dagger.gen.go` with only the necessary bits of the SDK and that doesn't include anything with `CLIVersion`. There’s no automatic provisioning code there, there’s rather a module-specific function to establish the client connection.

To save time building Python and Typescript modules support, I thought it was just easier to copy the whole SDK as is for now. Otherwise we’d have to refactor them to make sure we can split cleanly. This was actually the plan initially and it may still be desirable but hard to prioritize now.

Additionally, `CLI_VERSION` is considered part of the private API (in Python it’s under a file name starting with `_`). Users aren’t supposed to read it manually, it should only be used by the SDK itself. And it’s also only used in [automatic provisioning](https://github.com/dagger/dagger/blob/main/sdk/CONTRIBUTING.md#automatic-provisioning) (when running `python main.py`, without `dagger run`), which **doesn’t exist in modules** (to download the right CLI version and for the [`checkVersionCompatibility`](https://docs.dagger.io/api/reference/#query-checkVersionCompatibility) call).

With modules there’s no longer a mismatch between SDK and CLI versions, however if you’re using a custom runner, it’s possible that the engine version doesn’t match. So it’s good to confirm that you’re running the *registry.dagger.io/engine:v0.9.6* image.

> I suspected something when I wasn't getting the new secrets env var behavior I expected from `0.9.6` with the Python SDK.

I suppose you’re referring to https://github.com/dagger/dagger/pull/6314 which is a CLI only change, not a core change, so it doesn’t affect the SDKs. 🙂
