### ISSUE TITLE
Don't mix core API into module API

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#6444]
## Problem

When the Dagger Engine loads a module and serves its API, that API is 1) the module's functions and types, mixed with 2)  the engine's core functions and types. This makes the resulting API noisy and difficult to explore, because the core API is huge and drowns out the rest.

## Solution

1. Only expose the module's functions and types in its API.
2. If we want to support calling core functions from the CLI, expose the core API as a module that can be loaded the usual way: using dagger -m, etc.

FYI @sipsma @helderco

**Comment by sipsma** [comment]
@shykes We're planning on cleaning up the display of the core API in `dagger functions` and `--help` as part of https://github.com/dagger/dagger/issues/6358

But having the core API available for chaining is a crucial part of https://github.com/dagger/dagger/issues/6229 and something generally useful to have available by default. So I think we should tackle this as a problem of how to display the core API is a useful way rather than making it entirely unavailable by default.

**Comment by shykes** [comment]
> @shykes We're planning on cleaning up the display of the core API in `dagger functions` and `--help` as part of #6358
> 
> But having the core API available for chaining is a crucial part of #6229 and something generally useful to have available by default. So I think we should tackle this as a problem of how to display the core API is a useful way rather than making it entirely unavailable by default.

I think what I'm proposing has a much smaller scope, and is complementary to these improvements you mentioned.

- The "drowning out" I'm talking about is specific to the root Query type in the module's GraphQL API. A user would experience this when inspecting the module in a GraphQL playground.
- Technically the CLI should be affected too, since those are exposed as top-level functions alongside the module's functions, and therefore should drown out `dagger functions` and `call --help` against the root of a module. But the CLI is immune because it filters out core "functions" already.
- So, you could summarize my proposal as "make a module's GraphQL API match its the output of `dagger functions`".

**Comment by sipsma** [comment]
> I think what I'm proposing has a much smaller scope, and is complementary to these improvements you mentioned.

Ohh okay I see 👍I was actually planning on making core an explicit versioned dependency in the immediate future (https://github.com/dagger/dagger/pull/6386#issuecomment-1897897592), so I think this would probably fit in with that effort.

There's some trickiness even after that though because if you have, say, a module function that returns `Container`, then that means that `Container` *must* be in the schema alongside that module function. Otherwise the function's schema would be referencing types that don't exist in the schema. I don't see any way around that fundamentally.

However, I could definitely see it being possible to only include the types referenced by the user functions' args/return types. It would require some mildly fancy "tracing" of typedefs, but definitely do-able in general.
