### ISSUE TITLE
Potential issues introduced by `fix: skip head merge commits on pull requests`

### ISSUE THREAD

**Issue by jedevc** [dagger/dagger#6452]
A small issue potentially introduced by https://github.com/dagger/dagger/pull/6253 (cc @grouville @marcosnils)

So, prior to this PR, we didn't perform any network operations when starting a dagger session. However, after this, we start doing git operations. My worry is that this has introduced subtle bugs with how this works.

I've seen this weird message appear fairly consistently throughout our logs (failure https://github.com/dagger/dagger/actions/runs/7571487756/job/20619120120?pr=6451, success https://github.com/dagger/dagger/actions/runs/7653266578/job/20854758251?pr=6496) - not quite sure how/why we see this though: 
```
1: > in init
1: starting engine 
Error: timed out waiting for session params: Error fetching branch: error fetching branch from origin: exit status 128Error fetching branch: error getting commit: object not found1: connect
```
```
: > in init
1: starting engine 
1: starting engine [0.00s]
1: starting session 
Error fetching branch: error fetching branch from origin: exit status 128Error fetching branch: error adding fork as remote: exit status 31: [0.40s] OK!
1: starting session [0.40s]
1: connect DONE
OK!
```

This is pretty consistent - the error *doesn't* appear to be fatal (the fatal case is caused by an internal infra issue and is being investigated separately)

**Comment by grouville** [comment]
Nice one 🙏

**Comment by marcosnils** [comment]
strange that we're seeing that now since that has been merged  a while back 🤔
once thing that I've noticed is that we never added a timeout to the git fetch operation. It'd be nice to have a timeout there and probably just log the error and continue executing the pipeline?

**Comment by jedevc** [comment]
My initial assessment was wrong :tada:

There are two issues at play here:
- We see `Error fetching branch: error fetching branch from origin: exit status 128Error fetching branch: error getting commit: object not found1` on seemingly *every* run: https://github.com/dagger/dagger/actions/runs/7653266578/job/20854758251?pr=6496
	- These messages should not be printed - though the issue appears to be non-fatal.
- The `Error: timed out waiting for session params` is related to an internal infrastructure issue with our cloud caching service.

I'll update the issue description to focus instead on the first issue.

**Comment by marcosnils** [comment]
> * The `Error: timed out waiting for session params` is related to an internal infrastructure issue with our cloud caching service.

Have we validated that it's because of caching every time? For example, today I saw this issue while merging a PR here https://github.com/dagger/dagger.io/actions/runs/7659846458/job/20875876380#step:7:41 but we didn't observe any caching incidents or elevated response times. 

@gerhard @matipan let's get together when possible since it's very hard to understand what's happening here if we can't can't get the engine logs for that runner VM.

**Comment by gerhard** [comment]
A few quick solutions to not being able to get the Engine logs from the `dagger-runner`:
- Use a Dagger in Docker approach, similar to how `dev-engine` does it: https://github.com/dagger/dagger/blob/41208c41cd4e4d61eeb0ff23721bb195ddf7478d/.github/workflows/_hack_make.yml#L34-L39
- While debugging, run this temporarily in a GitHub Runner explicitly, i.e. https://github.com/dagger/dagger/blob/41208c41cd4e4d61eeb0ff23721bb195ddf7478d/.github/workflows/publish-sdk-go.yml#L9

Rather than getting Engine logs out of the current Dagger Runners setups, I am most keen on finishing the migration to the new EKS CI cluster. We've been delaying it for over a month now, I really want us to move away from this:

![image](https://github.com/dagger/dagger/assets/3342/a917a5e1-28f4-4f09-be52-51677a0e3cae)

**Comment by marcosnils** [comment]
> Rather than getting Engine logs out of the current Dagger Runners setups, I am most keen on finishing the migration to the new EKS CI cluster. We've been delaying it for over a month now, I really want us to move away from this:

yes, SGTM! It's relatively easy for us (infra access) to get the engine logs via `kubectl` for the moment, so we're good on that front. :+1:
