### ISSUE TITLE
Dagger module error message with a mistyped --sdk flag

### ISSUE THREAD

**Issue by slumbering** [dagger/dagger#6655]
When I initialize a new module with `dagger init` and I mistyped the `--sdk`, I'm getting the following error.

```
$ dagger init --name=my-module --sdk=typescrip
Error: failed to generate code: input: resolve: moduleSource: withName: withSDK: withSourceSubpath: resolveFromCaller: failed to collect local module source deps: failed to collect local sdk: missing config file /Users/slumbering/workdir/dagger-zenith/trivy/typescrip/dagger.json
```

I'm wondering if we could improve this message. Do you think there's anything we could do to make it clearer or more effective?

e.g:

```
The typescrip SDK does not exist.

Available SDKs:
- go
- typescript
- python
- ...
```

**Comment by TomChv** [comment]
@helderco @jedevc @vito Is it still a relevant issue?

**Comment by jedevc** [comment]
Yes, the confusing error still appears.

**Comment by slumbering** [comment]
I like the way AWS CDK makes the error clear:

```shell
$ cdk init app --language g
Invalid values:
  Argument: language, Given: "g", Choices: "csharp", "fsharp", "go", "java", "javascript", "python", "typescript"
 ```

**Comment by TomChv** [comment]
@helderco I'm pretty sure it's doable from the CLI, but the `sdk` field could also be a URL so we would need to be generic on the helpers.

Like

```
The typescrip SDK does not exist.

Available SDKs:
- go
- typescript
- python

You can also use a no-bundled SDK from its github URL (e.g., https://github.com/dagger/dagger/sdk/rust@main)
```

**Comment by rajatjindal** [comment]
I am taking a look at it today. I am planning to add:

- a local var in cmd/dagger/module.go with list of sdk supported.
- a validation function that verifies that if the sdk is provided, it is either one of the configured list or an `https` url.
- add a `PreRunE` step to cobra commands `init` and `develop`.

I think we should catch this error even before our call reaches engine, and therefore i am adding validation in `PreRunE` step, but also open to suggestions here.

If this approach looks good, I can open a PR for this.

**Comment by jedevc** [comment]
> * add a `PreRunE` step to cobra commands `init` and `develop`.

Hm, this is a bit problematic. If we do this, then it means if the engine has a new SDK that the CLI doesn't know about it might not work. We have *some* tolerance for different versions of CLI and engines to connect, so we need to take that into account.

> `https` url.

The defined format is a module ref - atm, they don't have schemes at all, but #7708 will change that.

---

I think this might be relevant: https://github.com/dagger/dagger/blob/82ff692e30025f60bfb7ab1f2c126ccaf05ae460/core/schema/sdk.go#L85-L97

Potentially, this could be reworked into a global map - `builtinSDK` then just looks up the SDK using a map, and then we can easily derive the list of SDKs from that.

**Comment by rajatjindal** [comment]
Hi @jedevc , thank you for the additional info/context.

when we add and release a new built-in SDK, the engine may support the new SDK, but the CLI may not know about the new SDK yet? if that is the case, I am thinking we may need to add support to query supported sdk's from the engine, and use that to validate. because if we use global map, the CLI may still be built using old values of map?

Kindly pardon my understanding of the flow here, and please correct me if I am missing something here.

**Comment by helderco** [comment]
Could be an error returned by the engine when the request is made, instead of a pre-validation from the CLI before the request, which would have to happen even when that value is correct. Makes for a more informative error when used from the API or a custom client too (I mean `Module.withSDK`, etc).

The only downside is in the formatting (newlines, etc), but maybe that's not necessary. We already have a similar error message when using an enum with an invalid value. The `--sdk` is basically an enum too.

Even if it is worth the "rich" formatting, you could have a custom error[^1], to avoid the need for parsing the error message in order to extract the necessary information.

[^1]: No need to implement in SDKs... the custom API errors will one day be a part of codegen in an automated way.

**Comment by rajatjindal** [comment]
I am looking at this issue, and have few questions:

- should we add this validation to only topLevel sdk or the dependencies as well? I think we should add the validation irrespective of toplevel here.

- do we support running `dagger init` with local-path-sdk as well? e.g. in [collectCallerLocalDeps](https://github.com/dagger/dagger/blob/main/core/schema/modulesource.go#L1012), specifically [here](https://github.com/dagger/dagger/blob/3c52de5cd5daf202f57d4879f914dac3d2bc3ccf/core/schema/modulesource.go#L1106) after we confirmed that the sdk is NOT the in-built SDK, we verify if it is a local ref or a git ref.  

depending on whether local-sdk-path is supported or not in `dagger init`, we have two options:

- if providing local-path-sdk to `dagger init` is valid, then we need to add a check inside `case core.ModuleSourceKindLocal:` to check if the directory exists or not on host (possibly using buildkit.StatCallerHostPath() function), and error out accordingly. IMO, this is what we might have to do.

- if we don't support local-path-sdk, then we can return error if it is not a built-in sdk AND not a git ref.

**Comment by rajatjindal** [comment]
> Even if it is worth the "rich" formatting, you could have a custom error[1](https://github.com/dagger/dagger/issues/6655#user-content-fn-1-a154c74a848096a71942f9628265de58), to avoid the need for parsing the error message in order to extract the necessary information.

I tried adding it as a custom error on engine side, but by the time error is returned to `init` command, it no longer has its type retained and is of type `gqlerror.List`, so there are two options IIUC:


1. we send the final error msg from the engine side, and let the CLI print the error msg as is. (it could be either of the multiline formatted error or one line msg)
2. we send a "invalid sdk" error msg, and based on that string print a more formatted error on CLI side. 

IMO, we should send the msg from engine, and print it as is on the CLI side.
