### ISSUE TITLE
🐞 [CLI]: `dagger functions $function_name` returns an error if return type is not a dagger object

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#6731]
### What is the issue?

calling `dagger functions foo` on the following function definition raises the following error: 
`Error: function 'foo' returns non-object type STRING_KIND`

```go
package main

type Testmodule struct{}

func (m *Testmodule) Foo() string {
	return "bar"
}

```

### Dagger version

dagger v0.9.11

### Steps to reproduce

run `dagger functions foo` on the code given above

### Log output

Error: function 'foo' returns non-object type STRING_KIND

**Comment by sipsma** [comment]
Oh so this is slightly different than what you originally mentioned in discord (`Error: function 'validate' returns non-object type VOID_KIND` when the return type was a string).

`Error: function 'foo' returns non-object type STRING_KIND` is technically expected since there's no functions available on a string. I can sort of see why it might be confusing though. I'll just update the error message to be a bit more explanatory for now if nothing else.

**Comment by marcosnils** [comment]
> Oh so this is slightly different than what you originally mentioned in discord (`Error: function 'validate' returns non-object type VOID_KIND` when the return type was a string).

oh! sorry about that! Since I was trying out multiple things, I was actually getting `VOID_KIND` when the return type of the function is only an error :pray: . Just saw the PR and it's definitely more clear now. Thx for addressing it! :hugs:
