### ISSUE TITLE
Restore auto-creation of `.gitignore` file when calling `dagger mod init`

### ISSUE THREAD

**Issue by samalba** [dagger/dagger#6784]
Few releases ago, `dagger mod init` created a `.gitignore` file in the module's source directory.

We discussed today with @sipsma and @shykes to possibly add this back. Especially it would clear out questions regarding what files need to be committed with the rest of the code.

**Comment by sipsma** [comment]
One thing to clarify, that change was only to the Go SDK (since it's a compiled lang and thus linters/static-analysis/etc. need the generated code to operate). We left python/ts alone since they didn't seem impacted.

I like @shykes's suggestion to make this something configurable during `dagger init/develop`. There's cases where you do want these files committed and cases where you don't. Today, if you *do* want to ignore the Go SDK generated files you can hand-create a `.gitignore`, but this seems simple enough to just support as configuration in dagger itself and save users a little time+effort.

**Comment by samalba** [comment]
> One thing to clarify, that change was only to the Go SDK (since it's a compiled lang and thus linters/static-analysis/etc. need the generated code to operate). We left python/ts alone since they didn't seem impacted.

Indeed it's sdk specific, Python still generates one to ignore the content of `sdk/`.

> I like @shykes's suggestion to make this something configurable during `dagger init/develop`. There's cases where you do want these files committed and cases where you don't. Today, if you _do_ want to ignore the Go SDK generated files you can hand-create a `.gitignore`, but this seems simple enough to just support as configuration in dagger itself and save users a little time+effort.

Adding my 2c: it makes sense to give users the choice, however I'd default with what makes more sense and make it clear that it's a default behavior that you can change. Creating a .gitignore from scratch has some friction as opposed to generate one that you can tweak or delete. I'd create one by default and add a message after the init that explains that you can remove it.

**Comment by sipsma** [comment]
PR to add support for configuring this here: https://github.com/dagger/dagger/pull/6888

Doesn't include the CLI support for configuring it yet, just the low-level support for setting it in `dagger.json`
