### ISSUE TITLE
🖐️ Is it possible to access `Host()` from a dagger function? (Go SDK)

### ISSUE THREAD

**Issue by tonirvega** [dagger/dagger#6955]
How can I get access to the host from a dagger function?

I miss the `Host()` , Is there any way to do this?

```go
package main
 
import (
 "context"
)
 
type MyModule struct{}
 
func (m *MyModule) Test(
 
 ctx context.Context,
 
) string {
 
       // Host() does not exist
 myDir := dag.Host().Directory("/tmp/my-directory")
 
 content, err := myDir.File("my-file").Contents(ctx)
 
        if err != nil {
  panic(err)
 }
 
       return content
  
}
 
```

**Comment by lsibilla** [comment]
I just installed dagger 0.10.3 this morning and have the same issue with Python SDK.

**Comment by tonirvega** [comment]
> I just installed dagger 0.10.3 this morning and have the same issue with Python SDK.

I'm in the 0.10.2

**Comment by purpleclay** [comment]
> > I just installed dagger 0.10.3 this morning and have the same issue with Python SDK.
> 
> I'm in the 0.10.2

The approach to writing a Dagger module has changed since v10. If you need a directory from the host you can pass one in when invoking your function:

```go
package main

import (
	"context"
)

type MyModule struct{}

func (m *MyModule) Test(ctx context.Context, dir *Directory) (string, error) {
	return dir.File("my-file").Contents(ctx)
}
```

Then you would call it by:

```sh
dagger call test --dir /tmp/my-directory
```

**Comment by tonirvega** [comment]
> > > I just installed dagger 0.10.3 this morning and have the same issue with Python SDK.
> > 
> > I'm in the 0.10.2
> 
> The approach to writing a Dagger module has changed since v10. If you need a directory from the host you can pass one in when invoking your function:
> 
> ```go
> package main
> 
> import (
> 	"context"
> )
> 
> type MyModule struct{}
> 
> func (m *MyModule) Test(ctx context.Context, dir *Directory) (string, error) {
> 	return dir.File("my-file").Contents(ctx)
> }
> ```
> 
> Then you would call it by:
> 
> ```sh
> dagger call test --dir /tmp/my-directory
> ```

Thank you for your response.

So if I want to do it through code instead of a param I have to use a "standard" dagger workflow instead of a module function, right? 

Greetings.

**Comment by purpleclay** [comment]
@tonirvega That is my understanding of the difference between writing Dagger Modules and using a "standard" Dagger workflow. I am happy to be corrected by someone from the community 😄

**Comment by by-nelson** [comment]
I'm having some issues with this, I ran `dagger init --sdk python` with dagger version 0.10.3 but the documentation and code in the release don't match with the one I have in my `sdk` folder. Am I using a different sdk version or why is the `Host` class missing?

**Comment by helderco** [comment]
> the documentation and code in the release don't match with the one I have in my `sdk` folder

@by-nelson, can you be more specific on what you mean?

Some APIs are only accessible in modules, and others may be the opposite. That's the case with `Host`. See https://docs.dagger.io/manuals/developer/overview/942201/execution-environment for more on this.

**Comment by by-nelson** [comment]
@helderco sure, what I mean is that looking at the docs for the python SDK I see that there is a [Host](https://dagger-io.readthedocs.io/en/sdk-python-v0.10.3/client.html#dagger.Host) class and also that the `Client` class as a [host()](https://dagger-io.readthedocs.io/en/sdk-python-v0.10.3/client.html#dagger.Client.host) method for `v0.10.3`. But when I try it then I get that there is no host() property for Client.

Thanks!

**Comment by helderco** [comment]
Ok, great! 🙂

I'm going to close as being answered.

- In Dagger Functions, you need to explicitly accept a directory as argument, and provide it via the CLI which does have access to `Host()`.
- If the directory (or file) is inside the module's source directory, you can access it within the function (i.e., don't need an argument for it) with [`dag.CurrentModule().Source()`](https://pkg.go.dev/dagger.io/dagger#CurrentModule.Source). 
- See the documentation on the [Execution Environment](https://docs.dagger.io/manuals/developer/overview/942201/execution-environment/) for more on this.

**Comment by noah-troncoso** [comment]
I came here looking for the same information as the OP. If we have to accept a Directory as a path, we lose the ability to setup include/exclude rules.

And based on all the documentation, it seems like modules and functions are *the* way to write dagger scripts now. If there is a normal Dagger workflow (as @purpleclay called it) where is this in the documentation?

**Comment by helderco** [comment]
> I came here looking for the same information as the OP. If we have to accept a Directory as a path, we lose the ability to setup include/exclude rules.

Not quite, we have a feature called *views*:
- https://github.com/dagger/dagger/pull/6857

It’s not yet documented because we need to polish the DX for managing it with the CLI:
- https://github.com/dagger/dagger/issues/6606

We use it in our CI:

https://github.com/dagger/dagger/blob/e678cdd17bee86faea9837e10dd0c8612994aa7c/dagger.json#L6-L17

And we call it like:

```
dagger call --source=.:default test all
```

To be clear, this is only needed for files outside of the module’s source directory (`"source"` in `dagger.json`; defaults to the directory where `dagger.json` is). For that, you have:

```go
dag.CurrentModule().Source()
```

And there’s filters for limiting the files uploaded when loading a module. Example:

https://github.com/dagger/dagger/blob/e678cdd17bee86faea9837e10dd0c8612994aa7c/sdk/python/dev/dagger.json#L5-L23

However, we’re discussing a change for how modules are loaded:

- https://github.com/dagger/dagger/issues/7199

So that in the common case of needing access to the parent directory, you won’t need to pass it as an argument and set up views. You’ll be able to access it and filter from code:

```go
func (m *MyModule) Source() *Directory {
 return dag.
  Context().
  Directory(ContextDirectoryOpts{Include: []string{"*.go"})
}
```


> And based on all the documentation, it seems like modules and functions are _the_ way to write dagger scripts now. If there is a normal Dagger workflow (as @purpleclay called it) where is this in the documentation?

The term “normal” here is only in the same sense of “usual”, but only for users that have used dagger for a while, before modules were released in `v0.10`.

We think that using Functions has [many benefits](https://dagger.io/blog/introducing-dagger-functions) over what came before but to clarify a few things:
- We’re not deprecating *custom clients* (`dagger run`), we’re considering it an advanced or niche use case. Sometimes it’s necessary. Everything should still work as before. Functions work on top of that, to improve the DX, but it’s the same API and works the same underneath, just more sandboxed. That's why there's more limitations when accessing host resources, but it's also more secure, reusable and portable (less boilerplate too).
- We don’t want fragmentation in the ecosystem so it’s important to us that users with *custom clients* can call modules seamlessly. You can do it today, but you have to lower into making GraphQL queries rather than using the generated `dagger.Client` that all SDKs have. That work is scoped in: https://github.com/dagger/dagger/issues/5993
- For new users it would be too much to try to explain the two approaches so we decided to rewrite the docs in v0.10 to focus on the new approach. The previous docs are still available at https://archive.docs.dagger.io/0.9/ for those that are using that version. You may notice that link is featured on every page of the current docs, in a blue bar a the very top.
- We didn’t have time to migrate all the content over to the new docs, but we’re currently very active in doing that. The priority is for documenting Functions, but eventually, we’ll probably have a guide for the *custom client* use case and how to interop with modules.

**Comment by noah-troncoso** [comment]
Thanks for the information. This seems like a pretty fundamental thing that should have been ironed out before releasing these functions. Not to mention the DX for these "views" is awful. I need a single file added to a container, but with the views limited parameters, I can't figure out how.

```json
{
  "name": "flagsmith-scripts",
  "sdk": "typescript",
  "source": "./dagger",
  "engineVersion": "v0.11.2",
  "views": [
    {
      "name": "npmrc",
	  "patterns": [
		"!**/*",
		"$HOME/.npmrc"
	  ]
    }
  ]
}
```

**Comment by helderco** [comment]
If you only need a file you can have a `dagger.File` as a function argument and give the path to it in `dagger call`.

**Comment by dstadelm** [comment]
I'm having an issue with this approach. My example project that I would like to daggerize has many steps and each step shall receive a directory containing the source code required for that step. The steps are dependent on each other. Therefore I have to pass in N arguments if I have N steps. I would prefer a solution where I can pass in the root as argument and then define the directory to be used in each step programmatically.  

The reason I want the code in separate directories is that this will ensure that a given step is only run if the source code for that step has changed.

Maybe I'm missing something, but I would appreciate some guidance here
