### ISSUE TITLE
Enable scheduler debug for tests

### ISSUE THREAD

**Issue by jedevc** [dagger/dagger#7020]
During our test runs, we should enable the debug scheduler (see https://github.com/dagger/dagger/pull/6991#issuecomment-2032750326), so that we have a better chance of catching the nastiness around:

- #6111 
- #6234

**Comment by sipsma** [comment]
Yeah I was about to send out a PR for doing this in our local dev engine and engine service used in tests but realized that's dumb since https://github.com/dagger/dagger/pull/6843 is about to replace all that, so will wait for that to land and then send a PR out.

Then obviously once we have a release with that new buildkit version we'll want to do the same to our K8s infra engine, but can wait until then. Interestingly it used to *only* be that K8s engine where I saw this happen, but as of a few days ago I've seen #6111 in the actual test engine service created inside mage too, so I guess we at least have more data points then before :laughcry:

**Comment by sipsma** [comment]
Ended up just debugging everything in the [PR](https://github.com/dagger/dagger/pull/7128)/locally, so we don't need to do this anymore (and don't want to since the scheduler debug logs are overwhelmingly noisy)
