### ISSUE TITLE
🐞 Kubernetes integration docs + helm chart need to be updated to the latest version

### ISSUE THREAD

**Issue by marcosnils** [dagger/dagger#7105]
### What is the issue?

Coming from here: https://discord.com/channels/707636530424053791/1229798907362414673

Looks like our helm chart doesn't really work with the latest version of Dagger and it's pinned to a v0.9.x engine. We should try to keep it updated every time we release a new version. 

cc @gerhard @matipan 

### Dagger version

dagger v0.11.1

### Steps to reproduce

Follow the guide here: https://docs.dagger.io/integrations/104820/kubernetes

Try updating the engine image from v0.9.x to the latest dagger version.  The Dagger engine won't start after that.

**Comment by smolinari** [comment]
Hehe... theoretically, your CD automation should be able to take care of this (with Dagger??? :grin: ). :P

Scott

**Comment by marcosnils** [comment]
> Hehe... theoretically, your CD automation should be able to take care of this (with Dagger??? 😁 ). 😝

yep :P

**Comment by matipan** [comment]
I'm currently going through the upgrade to v0.11.1 for our internal pipelines so I'll take a look at this one! The helm chart is a bit forgotten at the moment but with the new dynamic CI we can definitely make some tests that raise this for us since we can simply target `runs-on: dagger-v0-11-1`. Maybe we could integrate some of this as part of the follow ups for the release? cc @gerhard @jedevc

**Comment by marcosnils** [comment]
:wave: just sent a PR to bump the chart for the moment here https://github.com/dagger/dagger/pull/7176

**Comment by gerhard** [comment]
Partly addressed in:
- https://github.com/dagger/dagger/pull/7205

The follow-up is to automate this.

**Comment by marcosnils** [comment]
we have improved the release process and we're already bumping the helm chart on each release. Thx @gerhard
