### ISSUE TITLE
🐞 `NotAwaitedRequestError`: Encountered an error while requesting data via graphql through a synchronous call. Make sure the function called is awaited.

### ISSUE THREAD

**Issue by gerhard** [dagger/dagger#7303]
### What is the issue?

Hit this in `sdk:typescript:test` https://github.com/dagger/dagger/actions/runs/8986965799/job/24684341907?pr=7296#step:5:6492

<img width="1391" alt="image" src="https://github.com/dagger/dagger/assets/3342/249e9cde-616f-4cd7-bcde-59562811b573">

Also:
<img width="1343" alt="image" src="https://github.com/dagger/dagger/assets/3342/7e1131e3-8278-4caf-8b99-8d34121f5b53">

cc @TomChv 

### Dagger version

dagger v0.11.2 (registry.dagger.io/engine) linux/amd64

### Steps to reproduce

Not sure how to reproduce, but I've seen our CI hit it a few times. Will comment when we hit it again.

### Log output

[NotAwaitedRequestError.txt](https://github.com/dagger/dagger/files/15237078/NotAwaitedRequestError.txt)

**Comment by vikram-dagger** [comment]
+1

**Comment by helderco** [comment]
Probably a side effect of a client connection going down.

**Comment by vikram-dagger** [comment]
Just saw this again https://github.com/dagger/dagger/actions/runs/9016111175/job/24772050665?pr=7333

**Comment by TomChv** [comment]
I'm aware of this issue, however it's quite complex to enforce the call to `await` when it's necessary, usually you can guess it yourself and this error message is a simple hint.
In the case of the error, it's related to the engine that is not reachable but it's quite hard to give a good hint on what happend.

I can do some work on parsing the error and if a connection refused error match, then it's probably not because of an await.
I keep this in mind and will start an iteration soon on error handling, there's another issue related to that: https://github.com/dagger/dagger/issues/6624.

There's also another issue related to connection: https://github.com/dagger/dagger/issues/4375

**Comment by helderco** [comment]
I want to point out that using `async` and `await` work best when used under certain rules and while in TS it seems to work when you're being flexible about using them, it doesn't mean it doesn't lead to unexpected results, and this could be one of them. At least that's the impression I have, based on research I did in the past.

I think their usage should be cleaned up at some point, but don't have any raw data to suggest that it's causing major issues and the (possible) unexpected results could in fact be negligeable.

**Comment by TomChv** [comment]
> I think their usage should be cleaned up at some point, but don't have any raw data to suggest that it's causing major issues and the (possible) unexpected results could in fact be negligeable.

I tried to use async only when it was required, but because you cannot use await in a no async func, I had 2 choices:
either using `Promise` to call these awaited function OR spreading async to almost all my function that do 1 async call to send the graphQL request in dagger.

I'm open to any suggestions, right now I think it's more related to error handling than an async issue.

**Comment by TomChv** [comment]
I'm closing this issue since it seems the error hasn't been reported for few months, feel free to reopen this issue if it happens again :)
