### ISSUE TITLE
🐞 CLI docs does not show bool type 

### ISSUE THREAD

**Issue by levlaz** [dagger/dagger#7397]
### What is the issue?

I have a function with a `bool` type parameter. When I get `--help` for this function the docs do not show the type. 

I have this parameter defined in go: 

```
	// Optional flag to disable cache
	// +optional
	// +default=false
	enableCache bool,
```

I expect the output to show this: 

```
ARGUMENTS
      --src Directory              The source directory of your docusaurus site, this can be a local directory or a remote git repo [required]
      --cache-volume-name string   Optional cache volume name (default "node-docusaurus-docs")
      --dir string                 Optional working directory if you need to execute docusaurus commands outside of your root (default "/src")
      --enable-cache bool             Optional flag to disable cache
```

But instead it shows this: 

```
ARGUMENTS
      --src Directory              The source directory of your docusaurus site, this can be a local directory or a remote git repo [required]
      --cache-volume-name string   Optional cache volume name (default "node-docusaurus-docs")
      --dir string                 Optional working directory if you need to execute docusaurus commands outside of your root (default "/src")
      --enable-cache               Optional flag to disable cache
```

### Dagger version

dagger v0.11.4 (registry.dagger.io/engine) darwin/arm64

### Steps to reproduce

Create a new function with a bool input type and run `dagger call $function --help`

**Comment by helderco** [comment]
This is expected as it's normal for boolean flags to stand on their own (without a `=true`), especially when the default is `false`. It's handled by Cobra automatically. See `docker run --help` for more examples of this, or `gh pr checkout --help`, or other CLIs.

Another way to think about this is that the `string` and `Directory` types you see next to the flags actually indicate that they **expect an argument** of that type. Boolean flags don't require an argument because they usually default to false and just by adding the flag makes their value `true`.

Some CLIs add a `--no-<flag>` when the default is `true`, or even provide both versions like `git`.

**Comment by levlaz** [comment]
Hey @helderco thanks for helping me understand this. I hear what you are saying but I am expecting our CLI --help experience to have some parity with the Daggerverse docs. Daggerverse shows Boolean along with all the other types and I think that is a better DX for people who don't already know this convention.

**Comment by helderco** [comment]
But in Daggerverse those are basically reference docs, and following GraphQL's conventions actually. More important than parity in any SDK is doing what's natural in each language as much as possible (takes balance for sure). That includes the CLI, and familiarity with other CLIs.

See how the flags library explicitly excludes it (it's for a reason):

https://github.com/spf13/pflag/blob/d5e0c0615acee7028e1e2740a11102313be88de1/flag.go#L591-L592

**Comment by helderco** [comment]
Notice also that a list of strings is named "strings" and not "string[]" or anything like it. As I said, the things next to the flag names aren't necessarily the types, they're **placeholders** for an argument to the flag, as part of the given **usage syntax**, not as a reference necessarily.

If we had a way to programatically know that a `path: String!` in the API is a local filesystem path, we could use `--path <path>` instead of `--path string`. So for booleans it wouldn't be `--enable-cache bool`, it would be `--enable-cache [bool]`:

- `--enable-cache bool` suggests a usage of `--enable-cache true`
- `--enable-cache [bool]` suggests that providing the value is optional, however that's redundant and usually omitted
- `--enable-cache` is the conventional way to define the usage for a boolean flag (binary... it's either there or isn't)

**Comment by levlaz** [comment]
Thanks for the detailed explanation @helder, I appreciate it!
