### ISSUE TITLE
🐞 Python SDK creates invalid syntax

### ISSUE THREAD

**Issue by skycaptain** [dagger/dagger#7513]
### What is the issue?

Take following example

```python
SDK_ENTRYPOINT = f"""#!/bin/sh
# Source the environment setup file
. "$(find /sdk -type f -name 'environment-setup-*')"

# Execute CMD
exec "$@"
"""


@object_type
class SdkBuilder:
    sdk_entrypoint: str = SDK_ENTRYPOINT
    ...
```

Using this module as a dependency generates the following invalid Python code in `sdk/src/dagger/client/gen.py`:

```python
...
def sdk_builder(self, sdk_entrypoint: str = "#!/bin/sh\n# Source the environment setup file\n. "$(find /sdk -type f -name \"environment-setup-*\")"\n\n# Execute CMD\nexec "$@"\n",) -> SdkBuilder:
        _args = [
            Arg("sdkEntrypoint", sdk_entrypoint, "#!/bin/sh\n# Source the environment setup file\n. "$(find /sdk -type f -name \"environment-setup-*\")"\n\n# Execute CMD\nexec "$@"\n"),
        ]
        _ctx = self._select("sdkBuilder", _args)
        return SdkBuilder(_ctx)
...
```

To support this use case I would expect the code generator to keep the triple quotes as well as use raw strings `r""` to avoid interpolation at all.

### Dagger version

dagger v0.11.5 (registry.dagger.io/engine) darwin/arm64

**Comment by helderco** [comment]
There's no way for codegen to make a distinction here. It would have to always use tripple-quoted raw-string for all string types. 

May I suggest you use a `File` argument instead?

**Comment by skycaptain** [comment]
You're correct. In this scenario, using `File` might even offer the better UX. However, it's unfortunate that the code generation can be compromised this easily.

**Comment by helderco** [comment]
The issue is not with codegen. Think about it like this, you serialize a string to JSON to store it in the server. Later you need to deserialize from JSON, for example by a Go client looking to create an interface for it or even the CLI. How do you preserve that it's a triple quoted raw string across this serialization/deserialization boundary, where the deserialized value is shared between multiple platforms/languages (so no storing extra metadata that would make sense only to Python)?

**Comment by helderco** [comment]
I'm going to close. If there's a better idea, feel free to reopen 🙂
