### ISSUE TITLE
🐞 Inconsistent handling of env var inputs when used in dagger functions

### ISSUE THREAD

**Issue by cbochs** [dagger/dagger#7743]
### What is the issue?

Dagger accepts secret parameters in the form of `env:ENV_VAR`. However, this is not broadly the case for all parameters. It was unexpected that non-secrets do not respect this form and require you to pass in environment variables as `$ENV_VAR` instead. For example,

```
dagger call -m example \
    test \
    --version  env:MY_VERSION \ # does NOT work as intended
    --platform $MY_PLATFORM \   # need to use this form instead
    --secret   env:MY_SECRET    # this works
```

### Dagger version

dagger v0.11.8 (registry.dagger.io/engine) darwin/arm64

### Steps to reproduce

Example module: _module/dagger/main.go_

```go
type Module struct {}

func (m *Module) Test(
    version string,
    secret *Secret,
) {
    fmt.Println(version)
    fmt.Println(secret)
    return Module{}
}
```

With

```
$ export MY_VERSION=3.0.7
$ export MY_SECRET=asdf
$ dagger -m module --progress plain test --version env:MY_VERSION --secret env:MY_SECRET
```

Result

```
...
9   : [0.1s] | env:MY_VERSION
9   : [0.1s] | &{0x4000096500 <nil> <nil> <nil>}
...
```

Expected

```
...
9   : [0.1s] | 3.0.7
9   : [0.1s] | &{0x4000096500 <nil> <nil> <nil>}
...
```

**Comment by helderco** [comment]
This is not a bug, it's by design. 

The `env:`, `file:` and `cmd:` prefixes are a part of the format for `dagger.Secret` only. So `env:` is not general, and doesn't work in other types of arguments. The reason `dagger.Secret` needs it is to avoid passing sensitive information through the CLI command, which can be seen by other processes.

See [Docs: Developer Manual > Secrets](https://docs.dagger.io/manuals/developer/secrets).

**Comment by cbochs** [comment]
That makes sense, thank you for taking the time to reply
