### ISSUE TITLE
🐞 Dagger can no longer be imported as a library since #6843

### ISSUE THREAD

**Issue by matipan** [dagger/dagger#7783]
### What is the issue?

Since https://github.com/dagger/dagger/pull/6843 importing `dagger/dagger` as a library in a go module fails due to `distconsts` being its own standalone module.

The gist of what happens is:
1. You import `github.com/dagger/dagger` to use dagger specific components, such as `engine/cache`
2. `github.com/dagger/dagger` then imports `github.com/dagger/dagger/engine/distconsts`, however, since its within the same top level module in the context of the import Go tries to import `github.com/dagger/dagger` at revision `engine/distconsts@<VERSION>`. Meaning, its looking for a named release in `github.com/dagger/dagger` with that name.
3. Go fails to find said release because it does not exist, it is a separate standalone module

### Dagger version

dagger v0.11.9 (registry.dagger.io/engine) linux/amd64

### Steps to reproduce

In a new directory initialize a go module:
```console
go mod init dagger-import
```

Create a `main.go` that imports `github.com/dagger/dagger`:
```go
package main

import (
	"fmt"

	"github.com/dagger/dagger/engine/cache"
)

func main() {
	r := cache.GetCacheMountConfigResponse{}
	fmt.Println(r.Skip)
}
```

Run `go mod tidy` to download dependencies and the error can be seen:
```console
$ go mod tidy
go: finding module for package github.com/dagger/dagger/engine/cache
go: found github.com/dagger/dagger/engine/cache in github.com/dagger/dagger v0.11.9
go: downloading github.com/dagger/dagger/engine/distconsts v0.11.8
go: dagger-import imports
        github.com/dagger/dagger/engine/cache imports
        github.com/dagger/dagger/core imports
        github.com/dagger/dagger/engine/buildkit imports
        github.com/dagger/dagger/engine/distconsts: github.com/dagger/dagger/engine/distconsts@v0.11.8: reading https://proxy.golang.org/github.com/dagger/dagger/engine/distconsts/@v/v0.11.8.zip: 404 Not Found
        server response: not found: github.com/dagger/dagger/engine/distconsts@v0.11.8: invalid version: unknown revision engine/distconsts/v0.11.8
```

### Log output

**Comment by matipan** [comment]
After a discussion with @marcosnils we found two potential solutions to this problem:
1. Tag distconsts on every release at `engine/distconsts/v<VERSION>`
2. Pin `distconsts` using one of the available (non-tagged) releases in pkg.go.dev (see [here](https://pkg.go.dev/github.com/dagger/dagger/engine/distconsts))

Pinning `distconsts` and then replacing it with the local path works, but we would be leaving a random version that has nothing to do with the project. 
Tagging seems like the correct approach based on [Go's documentation](https://go.dev/ref/mod#vcs-version) but it adds another step to the release process:
> If a module is defined in a subdirectory within the repository, that is, the [module subdirectory](https://go.dev/ref/mod#glos-module-subdirectory) portion of the module path is not empty, then each tag name must be prefixed with the module subdirectory, followed by a slash. For example, the module golang.org/x/tools/gopls is defined in the gopls subdirectory of the repository with root path golang.org/x/tools. The version v0.4.0 of that module must have the tag named gopls/v0.4.0 in that repository.

This is not a blocker since users can still import `github.com/dagger/dagger`, they just need to replace distconsts with a release that pkg.go.dev knows about, for example:
```gomod
replace github.com/dagger/dagger/engine/distconsts => github.com/dagger/dagger/engine/distconsts v0.0.0-20240628152425-450240400e9c
```
This is what we are doing in an internal project and it works correctly.

**Comment by marcosnils** [comment]
cc @jedevc

**Comment by jedevc** [comment]
Hm, just to clarify, is there anyone outside of our internal project that imports `github.com/dagger/dagger` right now? If there isn't, I think we can work around this with the `replace` directive, that feels like an adequate workaround.

The re-introduction (we use to have it before) of `distconsts` is to resolve a dependency issue - there are a set of shared consts that need to be shared between our CI dev module and our codebase, but the dev module and our codebase may occasionally require different versions of the same dependency (cough cough, otel). Because of this, we can't have a direct dependency between both of these, and need a third module to handle this.

Why did only show up so recently? I wonder if this is maybe due to https://github.com/dagger/dagger/blob/b38d25b1fd0d2ba73b0db5d5a11ccabb73b9f001/core/terminal.go#L169 - until this line was introduced, `/dagger/cache` shouldn't have had a dependency on `distconsts`. But with it's introduction into `core` (which depends on `distconsts`), `dagger/cache` now has that dependency.

> Tag distconsts on every release at `engine/distconsts/v<VERSION>`

I would push back very hard on this option - the tags are for consumption by users, etc, we should avoid clogging this up.

> * Pin `distconsts` using one of the available (non-tagged) releases in pkg.go.dev (see [here](https://pkg.go.dev/github.com/dagger/dagger/engine/distconsts))

This feels fine for now, IMO.

As a potential third option, since the only thing shared is a single file full of consts, we *could* just duplicate it (and have a CI step to generate/check that it's copied correctly).

As a potential fourth option, we might be able to work out how to avoid the `dagger/cache` package's dependency on `core` (which I think you added @marcosnils) - maybe just inverting the dependency might help here.

**Comment by matipan** [comment]
> Hm, just to clarify, is there anyone outside of our internal project that imports github.com/dagger/dagger right now? If there isn't, I think we can work around this with the replace directive, that feels like an adequate workaround.

Given the lack of complaints/issues about this I think its safe to assume nobody is using it.

> Why did only show up so recently? I wonder if this is maybe due to

We were using version 0.9 of `github.com/dagger/dagger` in magicache and we never upgraded it. We noticed it now because I'm making some changes to the engine that magicache needs and that lead me to the upgrade and then the error.

> As a potential fourth option, we might be able to work out how to avoid the dagger/cache package's dependency on core (which I think you added @marcosnils) - maybe just inverting the dependency might help here.

This makes sense. Alternatively (although I much prefer fixing it) we can clarify somewhere (maybe the README) that `github.com/dagger/dagger` is not to be imported as a library. Or we can use this issue as documentation

**Comment by marcosnils** [comment]
is there anything else to do here? I guess we can just use the replace directive as we're doing now and that's it?

**Comment by matipan** [comment]
> is there anything else to do here? I guess we can just use the replace directive as we're doing now and that's it?

I don't think so. If eventually we want dagger/dagger as a library we can come back to this, re-open and fix the distconst issue if it still is one.
