### ISSUE TITLE
sdks: `Sync` doesn't always work as expected with certain APIs

### ISSUE THREAD

**Issue by sipsma** [dagger/dagger#7788]
A tangential issue I noticed during some adventures with https://github.com/dagger/dagger/pull/7767

At least in the Go SDK, the generated `Sync` method will just return the query it has built so far, e.g. https://github.com/dagger/dagger/blob/adca4e6cb4cd28090bfe5a87c497c93561c9161f/sdk/go/dagger.gen.go#L2102-L2106

However, this does not play nicely with our core APIs that rely on returning a `dagql.Instance` of a different API call, e.g. https://github.com/dagger/dagger/blob/adca4e6cb4cd28090bfe5a87c497c93561c9161f/core/host.go#L63-L69

While `Sync` is correctly called, the SDK doesn't use the returned ID and instead uses the query it already built up.

This is especially wrong in the case of impure APIs, since it will result in the API being repeatedly called incorrectly with the "original" ID.
* e.g. if the query is to load a local dir and sync is called, then any subsequent calls on the returned Directory will re-run the load of the local dir.

In terms of the practical impact today, not 100% sure, it did break new APIs I was adding in #7767 but:
1. I'm not sure if it causes significant incorrect/unperformant behavior for existing core APIs. It seems possible but would require more tracing of code and testing
2. I only looked at the Go SDK so far, not sure what others are impacted if any

cc @vito @helderco @jedevc

**Comment by helderco** [comment]
It was done this way because at the time we didn't have a good way to convert any ID to its corresponding object. That changed with the `loadXFromID` fields. 

I left a comment in codegen, but was removed in https://github.com/dagger/dagger/commit/7393e19bbbb2ae2ed07c93af09183f079d0a83b5#diff-de9a6011ccf4884745982bf7658dae4ec2e8d2564dd5a5b1063ef7dbe5678de7L145-L153:

<blockquote><pre>
// FIXME: <strong>We don't have a simple way to convert any ID to its
// corresponding object (in codegen) so for now just return the
// current instance.</strong> Currently, `sync` is the only field where
// the error is what we care about but more could be added later.
// To avoid wasting a result, we return the ID which is a leaf value
// and triggers execution, but then convert to object in the SDK to
// allow continued chaining. For this, <strong>we're assuming the returned
// ID represents the exact same object but if that changes, we'll
// need to adjust.</strong>
</pre></blockquote>

**Comment by helderco** [comment]
This was fixed in Python in https://github.com/dagger/dagger/pull/5353, with this change:

https://github.com/dagger/dagger/commit/f799e778fc786947075603bee83490c4e26aca74#diff-456e93caaf55f83fa963bff05f16413d26c0bfc01505ee73c7753b915ff22a55L403-R450

This was made possible by mapping out which fields would take an ID and return the corresponding object:

https://github.com/dagger/dagger/blob/f799e778fc786947075603bee83490c4e26aca74/sdk/python/src/dagger/codegen.py#L156-L166

This logic was simplified later by https://github.com/dagger/dagger/pull/6184.

**Comment by wingyplus** [comment]
I just realize that elixir return an id, not a structure to the caller. Which is definitely a bug in the codegen. I will submit a PR to fix this and make sure the api align with other sdk in 2 or 3 days.
