### ISSUE TITLE
TUI regression?

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#7801]
## Problem

In `main`, output from the TUI stays on the terminal after completion. This is different from the behavior on the current stable release, 0.11.8.

- On 0.11.8:

```console
$ dagger call -m github.com/shykes/hello hello
hello, world!
```

- On main (3767c8f0b3076a41c218c545c96641080b0e819b):

```console
$ dagger call -m github.com/shykes/hello hello
✔ connect 0.1s
✔ initialize 3.1s
✔ prepare 0.0s
✔ hello: Hello! 0.0s
✔ Hello.hello: String! 0.2s

hello, world!
```

## Solution

Revert the behavior to be the same as 0.11.8.

**Comment by vito** [comment]
This was an intentional change. We would frequently get questions that came down to users not knowing about `-v`, so printing nothing at the end didn't really feel like a sane default to me. I found myself passing `-v` nearly all the time because running something, tabbing away, and coming back to having no visibility into what actually ran, and having nothing useful in my scrollback after repeated runs, felt pretty frustrating and not in line with the TUI experience from other tools.

**Comment by shykes** [comment]
OK, it's definitely a fair point to revisit. A heads up would be nice though, this is a known bike shedding hotspot, since nobody brought it up I assumed it was unintentional.

**Comment by shykes** [comment]
>  I found myself passing -v nearly all the time because running something, tabbing away, and coming back to having no visibility into what actually ran, and having nothing useful in my scrollback after repeated runs, felt pretty frustrating and not in line with the TUI experience from other tools.

But was that in the context of developing or debugging the engine or TUI itself? As an end user of Dagger, I can't remember ever being in that situation *unless the pipeline fails*, in which case I do get TUI output. When my pipeline doesn't fail, I find it distracting to have residue from its progress in my terminal. What use case am I missing that lead to people asking for more TUI residue when their pipeline succeeds?

**Comment by vito** [comment]
My main concern is that the quiet behavior is a sane default for toy examples like the "hello world" above but is detrimental to the experience of using Dagger "in anger" because it eliminates the return on investment for a slow command (build/test/lint). I've got 10,000 lines of scrollback and only so many hours in a day; I'd rather spend the scrollback than spend time chasing ghosts because ambient information was taken from me to keep the output clean (concrete example for this later).

> But was that in the context of developing or debugging the engine or TUI itself?

For me, it's usually in the context of running Dagger's integration tests or lints while developing Dagger. It's the same experience as you would have when testing any other product with Dagger, so I don't think it's disqualified at all by being too meta or too close to the problem - at the end of the day, I'm using Dagger for a project which just happens to be Dagger. This isn't influenced by the TUI itself; it's the other way around, dogfooding influenced the TUI.

Example: if I start a `dagger call test --count=100 --run TestFooBar` to suss out a flaky test and context-switch, I'd really prefer to come back to _something_ in the output so I can start to rebuild that context. Coming back to an empty terminal makes it hard to even tell where I was, or if I even ran the command, because I have no point of comparison ("last run took 18.9s, oh this one's different"). Also, without even a basic timing breakdown it can be difficult to notice that I actually typoed `TestFooBar` and the command just took a while to initialize and didn't run any tests at all. This has happened before, and has made me angry.

So, to me, it seems like showing a brief summary by default causes less harm than being silent by default.

I'd still be interested in hearing the perspective of others outside of Dagger though.

**Comment by vito** [comment]
Also, still willing to go back on this, don't want to sound like I've got 100% conviction on it, just wanted to outline the case for the change. :smile: Maybe there are other avenues to address the pains I and other users ran into. Either way, it felt like low enough risk to just try changing it based on the feedback so far and iterate. Would rather change it and have folks complain it's too noisy and change it back, than wonder whether the complaints so far represent a vocal minority.

**Comment by shykes** [comment]
I see. Yeah this boils down to test pipelines not returning anything useful. We're basically attacking that problem from two different angles - output verbosity, test reports - and interfering with each other somewhat. Specifically, the extra verbosity only bothers me when test pipelines print test reports- and the lack of verbosity bothers you when it doesn't 😁

**Comment by shykes** [comment]
What if we branched on pipeline output?

- If pipeline returns something (non-void return value): wipe TUI output, print the return value
- If pipeline returns nothing (void return value): don't wipe TUI

That way we keep your fix for test pipelines that return nothing; and we don't get in the way of a great experience for test pipelines that do. Best of both worlds?

**Comment by vito** [comment]
That almost does the trick, but we'd also want the progress printed in situations where the CLI automatically calls `sync`, for example if your test function returns a `Container`, since that seems like a common pattern for test functions. We also have some expensive APIs that return simple scalar values like `File.export` and `Container.publish` which I would still want to see the progress for, but I'm curious if you feel differently about those since they're examples beyond running tests.

Ideally we could define the rules for this within a closed system that's easy to explain, without relying too much on pattern-matching the shape of API calls that tend to be made for the use case we're looking for. I would still have some anxiety that these heuristics apply to tests, but for another user with a different (or even the same) use case the removal of progress ends up feeling like a non sequitur. Maybe they just want to see the `go test` output at the end but still want to notice any slowness leading up to it.

I think my perspective boils down to "if my pipeline spent a significant enough amount of time on any particular step, I want to know about it, and if it _didn't_ spend enough time when I expected it to, I want to notice that, too."

Right now "significant" is defined as >100ms, and we make an exception for top-level spans and always show them. Maybe there's a path where we adjust these? In the end these are still heuristics, but it feels like a slightly more closed system since it's derived from the value I care about in the first place (time spent) rather than incidental API patterns. If we bumped the threshold to 1 second for the final print for example, your "hello world" above would look a lot cleaner, with the caveat that you'd likely still see 'initialize' or module calls show up if there are occasional slowdowns.

Not really in love with it though. Mostly trying other dialogue trees. :) To be honest I find the output gives me a more solid grasp of what I'm building, so it doesn't bother me.

**Comment by shykes** [comment]
I don't think a "time elapsed" threshold is a good idea.

> if my pipeline spent a significant enough amount of time on any particular step, I want to know about it, and if it didn't spend enough time when I expected it to, I want to notice that, too.

I think that's where Traces comes in. Or, if it takes long enough, the in-progress TUI. By definition the longer it takes, the more time you have to look at the output.

I think between:

1. Pipelines without a return value always keeping the TUI output (my proposed change)
2. Very slow pipelines being visible longer in the TUI
3. Traces being available for free to answer "where is my pipeline spending time and why?"
4. `-v` or a new better flag to explicitly always keep the TUI output
5. Easy to change signature of test function to return void if needed

We would be in a good place.

- Test functions that return a container will print the container metadata. You don't want TUI mixed in there, it looks weird.
- Test functions that return stdout of the test command, should also only print that. If that output is not useful, change the function signature to return void instead.

Adding rules about command duration overcomplicates things with no obvious benefit. We're talking about a default, it's not like users can't set a flag or change their function signature. Better if the rule for the default is super simple so that it's intuitive to understand when it applies, and how to override it.

**Comment by jedevc** [comment]
Adding my 2 cents :moneybag: 

> I found myself passing -v nearly all the time because running something

Yup same, and to be honest, I often find myself turning it up even higher sometimes, or putting it into `plain` mode to try and understand a test run, since the test run itself gets collapsed in the output, so I can't see where the test actually ran.

Tangent: aside from just having the traces link in the output, it would be really interesting if we could replay previous runs from the CLI (or at the very least, just display the whole full explorable trace, since now we have the very cool navigable TUI).

> I don't think a "time elapsed" threshold is a good idea.

I think we should keep the current behavior: don't show super short steps, but show all top-level steps. But we should always show the trace, regardless of whether it was fast/short/etc.

This is outside the scope for this issue though, since we've been doing this for a while - pretty much since this progress view was introduced. Potentially, we could do some better filtering and encapsulation/internalizing of various pieces and maybe make having a clean progress less dependent on the time-elapsed threshold.

> Test functions that return stdout of the test command, should also only print that.

I don't think we should be altering the behavior of whether to keep the progress summary at the end based on the content of the function, etc - we have command-line verbosity flags to control verbosity, so we should use those. Having progress display sometimes, and not others, depending on return type would be really confusing.

**Comment by shykes** [comment]
@jedevc so are you arguing to a) keep the current always-verbose default, or b) revert to the 0.11.8 never-verbose default? Or something else?

**Comment by jedevc** [comment]
I think I'd rather keep the current default, where after the run completes we collapse to just the top-level.

Separately, we need to do some cleanup of the top-level.

**Comment by vito** [comment]
(trying to be brief, would rather hear more from others, I think after this comment all my thoughts are clarified)

> I think that's where Traces comes in. Or, if it takes long enough, the in-progress TUI. By definition the longer it takes, the more time you have to look at the output.

The longer something takes the more likely I am to context-switch and not look at all; when I switch back I would like my scrollback to tell me what happened. I want to use Cloud because I _want_ to, not because I _have_ to; that frustration will spill over and negatively frame my Cloud experience. Juggling a bunch of de-contextualized browser tabs isn't fun when I'm already juggling so many terminals. :face_with_spiral_eyes: 

> Better if the rule for the default is super simple so that it's intuitive to understand when it applies, and how to override it.

To me, the simplest thing is to just always show the progress summary unless you pass something like `-q` or `-s`. I don't want to have to make my API worse (by removing a useful/chainable return value) just to to appease a TUI heuristic.

> We're talking about a default, it's not like users can't set a flag or change their function signature. Better if the rule for the default is super simple so that it's intuitive to understand when it applies, and how to override it.

IMO the default should minimize wasted time. I don't see the progress as being "mixed in" with the desired output and I don't see it as "TUI residue" - it's a criticial part of the feedback loop for the tool to inform me how my code ran.

**Comment by shykes** [comment]
I disagree but don't have the energy to argue over this. Can you please give me a flag + env variable so I can at least revert to the previous behavior for my own use.

**Comment by vito** [comment]
For sure:

* #7822

Might as well put it to a vote in the meantime:

* :rocket: = hide progress on completion, pass `-v` for verbose (v0.11.x behavior)
* :eyes: = keep progress on completion, pass `-q` to hide it (#7822)

I won't vote (I'll vote both to bootstrap) since the original goal was to adjust to user feedback anyway.

**Comment by helderco** [comment]
> That almost does the trick, but we'd also want the progress printed in situations where the CLI automatically calls `sync`, for example if your test function returns a `Container`, since that seems like a common pattern for test functions.

Now `dagger call` at minimum prints the name of the object if it has no eligible functions to print. Because of this the CLI no longer calls `sync` implicitly. The object's "fields" are printed instead.

The exception is that export is still implicitly called if you use `--output`, but that's for compatibility reasons.

> We also have some expensive APIs that return simple scalar values like `File.export` and `Container.publish` which I would still want to see the progress for, but I'm curious if you feel differently about those since they're examples beyond running tests.

Export now returns the absolute path where it exported too. So both export and publish return something useful.

It's only when a function returns `Void` that nothing is returned.

**Comment by helderco** [comment]
Re: the vote, I don't have a strong opinion yet. I've felt annoyed by the lingering output, but I can see the value in leaving it in by default just to understand the times it took on each stage. It could also be a question of building the muscle memory to type -v. I don't know yet which one I'd use more: `-v` or `-q`, depending on the default.

**Comment by vito** [comment]
Just remembered you can also press `+/-` at runtime to adjust the verbosity, a feature which was added along with this change(/regression).

So if we bring back the old behavior and you forget to pass `-v`, you can just press `+`.

And if we keep it as-is and you forget to pass `-q`, you can just press `-`.

Between the two I would argue the previous behavior benefits more from this feature. I always used `-v` for slower pipelines, so I'd have more time to press `+` if I forget. But if I forget `-q` for a faster pipeline, I don't have much time to press `-` before it pollutes my scrollback. If my math is right, the user benefits in more scenarios from a `-q` default.

Arguably skipping the flags and just using `+/-` is better anyway since it keeps dupes out of your shell history. :sweat_smile: 

@helderco Yeah, I'm in the same boat really, though the output hasn't annoyed me as much. Maybe we're running different things. My guess is there just isn't a one-size-fits-all; I've found myself using `+` and `-` all the time (sometimes as a navigation technique).

**Comment by helderco** [comment]
May have been more annoyed by the surprise tbh. I wanted to make a screenshot of a command but didn’t want those progress lines. So I added `-s` to wait for a while without any output and in the end, the progress spitted out like a ghost on Halloween! 😂

Wasn’t even aware or remember `-q`. Or is that new? 🙂

That progress result didn’t feel useful because my shell already displays the elapsed time on any command, my terminal shows me when a command in history was executed just by Ctrl+R, and I can go to cloud to see how the whole thing progressed.

While it’s running I do use the navigation controls. Love `c` because I find it more usable to watch the progress in cloud instead of seeing things fly in the terminal.

**Comment by vito** [comment]
> So I added `-s` to wait for a while without any output and in the end, the progress spitted out like a ghost on Halloween! 😂
>
> Wasn’t even aware or remember `-q`. Or is that new? 🙂

Yeah the final print unintentionally ignored `-s`, which is fixed now, in the same PR that introduced `-q` (#7822). `-q` is new, since there's no way to say `-v=0`. It actually works the same way `-v` does, only in the opposite direction (you can `-qqq` for -3).

> That progress result didn’t feel useful because my shell already displays the elapsed time on any command, my terminal shows me when a command in history was executed just by Ctrl+R, and I can go to cloud to see how the whole thing progressed.

Totally fair - I think for most commands like `dagger develop`, `init`, `--help`, etc. I'd prefer it to be hidden. I only really had `call` in mind when making the change. Might be easy to make it per-command. Ultimately we're just summing the default with how many times the user passed `-q` (-1) or `-v` (+1), so it would be easy for a command to apply its own delta, too, and user flags would just become relative to that.

**Comment by shykes** [comment]
After live discussion, we have agreed to keep the new "lingering" behavior. We are leaving the door open to changing it back if users complain.

Also, this raises the bar on readability on the top-level TUI output. Specifically, we should be extra careful to not show top-level spans that are obscure or confusing to the user.
