### ISSUE TITLE
CLI: don't run a container's default args when printing it

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#7821]
## Context

Since #6515, the CLI prints objects returned by a pipeline. To do this, it calls certain functions in the returned object, specifically functions which 1) return a printable value, and 2) have no required arguments.

## Problem

When a pipeline returns a `Container` object, the CLI calls `Container.stdout()` and `Container.stderr()`. In some cases<sup>1</sup>, this will unexpectedly execute a long-running service specified in the container's `defaultArgs`.

*[1] normally, `stdout` and `stderr` return the result of the last `withExec` operation. But if there is no `withExec` in the container state, `defaultArgs` are executed as a fallback. That is what causes the unexpected behavior.*

For example:

```console
dagger call -m github.com/dagger/dagger/dev@3767c8f0b3076a41c218c545c96641080b0e819b \
 docs server
```

- Expected behavior: print container metadata, and return control to the user
- Actual behavior: execute the `defaultArgs` (in this case a long-running server), and hang forever

## Solution

~~Manually exclude `Container.stdout` and `Container.stderr` from the list of functions to call when printing an object. If any other functions in `Container` cause it to be executed, exclude that too.~~

Change the behavior of `Container.stdout` and `Container.stderr` so that it doesn't fallback to executing `defaultArgs`. Also make sure its behavior no longer depends on how many `withExec`s are in the container spec.

**Comment by shykes** [comment]
FYI @helderco

**Comment by helderco** [comment]
I guess that answers this, right? 🙂 

> _On the question of "expensive scalar functions_: for example, `Container.stdout()` is "expensive" because it forces actually executing a container, in order to retrieve its standard output. Therefore, it is argued, the CLI should not blindly call all scalar functions of an object, because it may cause expensive computation which the user does not want. _This is premature optimization_. Let's ship the feature in a naive implementation; then see how important it actually is to avoid expensive computation. My guess is that, in most cases, it won't matter. For example, if I query a container, I don't care that it's actually executed. Or, if it turns out it's a problem, then we can implement a special case in the core type. I certainly won't care if my own custom types don't benefit from such a special case.

\- _Originally posted by @shykes in https://github.com/dagger/dagger/issues/6515_

**Comment by shykes** [comment]
@helderco yeah I didn't think about the case where executing the container runs a server and never returns...

So it looks like I got this part wrong:

> For example, if I query a container, I don't care that it's actually executed.

And it's time to do this part:

> Or, if it turns out it's a problem, then we can implement a special case in the core type. I certainly won't care if my own custom types don't benefit from such a special case.

I still believe this part is correct.

**Comment by sipsma** [comment]
One note: we don't necessarily have to hardcode `stdout`/`stderr` as exceptions and keep playing whackamole forever. `TypeDef` distinguishes between Fields and Functions, where Fields are already calculated values that require no work to retrieve and functions require at least *some* work to calculate.

It seems very reasonable to me to just print Fields and skip Functions. And specifically to only print Fields that have scalar values.

The only mini-problem is that we don't distinguish between Fields and Functions in TypeDefs for core types yet, but that's a superficial problem (the underlying distinction does exist for core types, it's just not exposed [here](https://github.com/sipsma/dagger/blob/ccdea050df7fbe7fb4237a308bdcc7016ee7337c/core/schema/coremod.go#L115-L115)).

If we fix that then the CLI doesn't need any hardcoding, it will all be controlled from the server-side schemas (including benefiting user module objects).

**Comment by helderco** [comment]
> `TypeDef` distinguishes between Fields and Functions, where Fields are already calculated values that require no work to retrieve and functions require at least _some_ work to calculate.
> 
> It seems very reasonable to me to just print Fields and skip Functions. And specifically to only print Fields that have scalar values.

That's what I did initially, but we decided to try it out without that distinction. See:
- https://github.com/dagger/dagger/issues/6515#issuecomment-2130138305

**Comment by shykes** [comment]
@sipsma I feel pretty strongly that we should avoid leaking the field/not field distinction into the CLI behavior, so that module devs remain free to change a field to an accessor and vice versa, with the confidence that they're not affecting their callers in any way. Since graphql doesn't make the distinction, neither should the CLI in my opinion.

**Comment by shykes** [comment]
I wonder if future annotations related to cacheability, purity, etc. could be used as hints for this in the future somehow?

**Comment by helderco** [comment]
> > That's what I did initially, but we decided to try it out without that distinction. See:
> > 
> > * [CLI: print module object fields with `dagger call` #6515 (comment)](https://github.com/dagger/dagger/issues/6515#issuecomment-2130138305)
> 
> Right, but was there an actual issue with the Fields approach or did you just want to start w/ the "select all scalars" instead? Couldn't glean that from the comment.

No problems with the Fields approach. When I said "I have a few issues with printing the fields", I meant "fields" here in reference to the issue's title ("print module object fields with `dagger call`"), so I was balancing option 1 with option 2.

I actually implemented it at first with only selecting Fields. Then switched to the other option of just **listing** the Fields, and per Solomon's feedback returned to printing the values. That comment was made at this stage.

As he said, he feels strongly about not making any distinction between Field and Function. My main problem, even to this day, is inadvertently triggering expensive computation. Particularly nervous about selecting a function like `Deploy`, without arguments, that just returns an error. This is evidenced in the last paragraph (but also earlier comments):

> So... my gut wants to limit selecting only state functions (fields) rather than all functions, and maybe hardcode which ones in a few core types.

But... we had a chat and I agreed to give it a chance and see what the feedback is. That's what I meant by "but we won’t really know if we don’t put it out there and get feedback."

**Comment by shykes** [comment]
What I mean is that changing a field to a getter function doesn't change the schema, and that's a good thing. It allows me to keep the distinction between field and getter function hidden from my callers.

I understand how using field/not-field as a print heuristic is appealing, because a scalar field is always safe to print. But some scalar getter functions are safe to print too, and I worry that if I refactor a field into a getter function (which I do often) I will be "penalized" by my getter function disappearing from the CLI output.

**Comment by helderco** [comment]
>  Particularly nervous about selecting a function like `Deploy`, without arguments, that just returns an error.

Well, I actually forgot I exclude `Void` (wouldn't make sense to print a void anyway):

https://github.com/dagger/dagger/blob/b856383255d0a7ee8fa108c1cb85c63d10aba564/cmd/dagger/module.go#L1121-L1122

But the worry is still there if the `Deploy` returns a string like the published URL or something.

**Comment by sipsma** [comment]
> But... we had a chat and I agreed to give it a chance and see what the feedback is. That's what I meant by "but we won’t really know if we don’t put it out there and get feedback."

I see, and yeah to be clear I don't think it was wrong to start there or obvious either way. I am just advocating for switching this because:
1. It avoids the whack-a-mole of hardcoding skips of core APIs that trigger execution (which goes well beyond stdout/stderr, both now and in the future) in a consistent way. That's a meaningful maintenance burden otherwise.
2. It avoids the problem of users writing side-effectful functions that get implicitly and unobviously triggered when their function happens to have a signature that matches the current autoselection logic. Again in a consistent and obvious way for module authors (it's very obvious in the current DX whether something is a Field or a Function).

> But some scalar getter functions are safe to print too, and I worry that if I refactor a field into a getter function (which I do often) I will be "penalized" by my getter function disappearing from the CLI output.

Yeah that makes sense, I agree it would be nice if users had even more fine-grain control here (and that is possible to add too).

But just speaking in terms of the current state of things, we do need a heuristic here, which always means tradeoffs. And for me personally the potential surprise of a side-effectful Function getting triggered by autoselection if it happens to match our current logic outweighs the cost of not seeing it get autoselected. That's obviously just IMO though

The whole Field/Function difference exists for essentially all of the reasons we're talking about here. Some values are pre-calculated and can be returned without any work (or even an "actual" function invocation) and some require work and an actual function call. So it seems like a very safe behavior to start with in terms of our autoselection heuristics (besides avoiding the aforementioned whackamole) and can be improved iteratively by giving users more fine grain control.

---

Either way, that's just my 2c, I totally agree there's tradeoffs either way. The only thing I'd be firmly adamant about is that if we keep the current behavior and do the whackamole, we need to document and/or otherwise make it very very clear that Functions with no required args that return a scalar will get selected, and thus side-effectful user Functions should not have that signature.

**Comment by helderco** [comment]
> I understand how using field/not-field as a print heuristic is appealing, because a scalar field is always safe to print. But some scalar getter functions are safe to print too, and I worry that if I refactor a field into a getter function (which I do often) I will be "penalized" by my getter function disappearing from the CLI output.

That's a good point. In Python we **could** use _properties_ for that:

```python
@object_type
class Test:
    @function
    @property  # allows calling this as an attribute (aka field): `self.simple_scalar`
    def simple_scalar(self) -> str:
        return "not too bad computation"
```

in TypeScript you have [getters](https://www.typescriptlang.org/docs/handbook/2/classes.html#getters--setters):

```typescript
@object()
class Test {
  @func
  get simpleScalar() string {  // notice the `get` before the function name
      return "not too bad computation"
  }
}
```

**Comment by sipsma** [comment]
> > I understand how using field/not-field as a print heuristic is appealing, because a scalar field is always safe to print. But some scalar getter functions are safe to print too, and I worry that if I refactor a field into a getter function (which I do often) I will be "penalized" by my getter function disappearing from the CLI output.
> 
> That's a good point. In Python we **could** use a [property](https://docs.python.org/3/library/functions.html#property) for that:
> 
> ```python
> @object_type
> class Test:
>     @function
>     @property  # allows calling this as an attribute (aka field): `self.simple_scalar`
>     def simple_scalar(self) -> str:
>         return "not too bad computation"
> ```
> 
> in TypeScript you have [getters](https://www.typescriptlang.org/docs/handbook/2/classes.html#getters--setters):
> 
> ```ts
> @object()
> class Test {
>   @func
>   get simpleScalar() string {  // notice the `get` before the function name
>     return "not too bad computation"
>   }
> }
> ```

I'd be all for that sort of approach, provided the default is to not select Functions unless they have that explicit annotation as a getter. Fields are essentially our "getters" today in my mind, but it makes sense to be less rigid there, especially in languages that already have these notions like you listed.

**Comment by helderco** [comment]
> I'd be all for that sort of approach, provided the default is to not select Functions unless they have that explicit annotation as a getter.

Yes, that's why I brought it up. Go doesn't have this concept though.

> Fields are essentially our "getters" today in my mind, but it makes sense to be less rigid there, especially in languages that already have these notions like you listed.

There's already a disconnect in other places. Some parameters are optional to Dagger but required in the language for example. I don't see a disconnect here however. The `@property` descriptor is very well used in Python to make a simple function (bad practice to put expensive operations there) be used like an object attribute. So Dagger would see this function as if it were an attribute like the other "fields", just like end users of the class.

**Comment by helderco** [comment]
There's one slight disconnect though. Usually, when properties are used, you expect that code to execute every time it's called. When you don't want to re-execute on subsequent runs, then you use a [@cached_property](https://docs.python.org/3/library/functools.html#functools.cached_property).

So using `@property` with `@function` would be like using a `@cached_property` from Dagger's POV, since it becomes state. That's fine though. It's easy to explain. Just food for thought.

**Comment by vito** [comment]
Marking this "breaking" since it's a change in behavior for anyone that defined simple `unit: Container` entrypoints for CI and relied on the Dagger CLI evaluating the container with `dagger call unit`. Following this change, their CI will silently no-op without actually running their tests.

Granting that it's a conscious design change we're making, I suppose anyone currently returning `Container` expecting current DX should either:

* change the function to call `Sync` on its own and return `(*Container, error)`
  * pro: maintains same API
  * con: it feels weird to force unlazying in my code
  * con: I don't actually want the CLI to dump the container properties (it's not valuable, I'm not publishing this container)
  * con: more code to write (context.Context) - feels less like "legos"
* change the function to call `Stdout` and return `(string, error)`
  * pro: nice final output in CLI and Cloud
  * con: what if my process prints to `Stdout` *and* `Stderr`, interleaved? what if I'm not sure whether it prints to `Stdout` or `Stderr` and I guess wrong?
  * con: can't chain anymore (what if my tests dumped browser screenshots?)
  * con: more code to write (context.Context) - feels less like "legos"
* change the function to call `Sync` on its own and just return `error`
  * pro: roughly the same UX as before; just run the container rely on progress UI, don't print anything
  * pro: if my test output is large, I don't need to worry about buffering it in memory
  * con: can't chain anymore
  * con: more code to write (context.Context, discard Sync result) - feels less like "legos"
* change my CLI call to chain `stdout` or `sync`
  * ultimately same pros/cons as above equivalent

None of these feel like a surefire win - is there another option I'm missing?

Worth noting that again this mostly affects tests and lints, which I know we have some high level ideas for, but afaik all of those ideas involve deep integration with the test system, so I suspect these issues would remain in other cases, or the general case until a module is developed for it.

**Comment by sipsma** [comment]
@helderco I think it's important we make a decision + implementation here one way or another before v0.12 (added it to the milestone). 

Like I said, I'd greatly prefer we avoid the current behavior of autoselecting functions just because they happen to have a certain signature (and it seems like it we go with the annotation approach of controlling this, that would be our baseline default behavior anyways).

But if we don't then we need to very clearly document this or else it's a huge footgun waiting around.

**Comment by helderco** [comment]
I suggest we just `sync` implicitly when it's a `Container`, before selecting the scalars that don't trigger execution (just `stdout` and `stderr`). No changes in user module code and fixes the current issue.

However, it can still break user expectations when using modules. Do we give it a chance and see how it goes before reverting to only showing fields in the next release?

Just to clarity the alternative, we already have a [State as Functions](https://docs.dagger.io/manuals/developer/state-functions) page in the documentation. We can explain which functions get printed by saying it’s functions that expose "state". We don’t have to use the word "fields", that’s why that page was written like that. This is my preference but I’m willing to try @shyke’s way, so I defer to him on whether he’s convinced on changing course or not.

**Comment by vito** [comment]
@helderco I'd be good with that as an intermediate step for compatibility, though it seems to go against the spirit of this issue, which might have a longer term plan in mind.

The OP mentions that we don't want to run the container _entrypoint_:

> Actual behavior: execute the entrypoint (in this case a long-running server), and hang forever

...but my understanding is `Sync` already won't do that (it _builds_ the container, it doesn't _run_ it), so maybe there's some confusion there.

Or maybe it's using 'entrypoint' in a generic sense, imagining the post-`ENTRYPOINT` world we want to be in? But either way, I don't think we'd want to use `Container` to represent indefinitely-running services, since you'd get the same hang if you were to try to build + publish the image.

If there _is_ a longer term vision in mind I'd only suggest we quickly bikeshed an alternative for folks like me that currently rely on the `Sync` behavior.

**Comment by helderco** [comment]
> @helderco I'd be good with that as an intermediate step for compatibility, though it seems to go against the spirit of this issue, which might have a longer term plan in mind.

What exactly are you referring to? What I proposed does what OP is asking for: **print container metadata, without container execution**.

Current behavior is not that it executes the entrypoint necessarily, it's that `stdout` and `stderr` trigger execution of last `withExec`, unless there's none, in which case it triggers the entrypoint + default args. Note that after https://github.com/dagger/dagger/pull/7136, it'll fallback to loading just the default args, not the entrypoint though.

To be clear, the CLI is no longer doing `Sync` implicitly. So if we take out `stdout` and `stderr` from the list of "fields" to print from `Container`, then it'll break users that have been relying on the implicit `sync` that the CLI used to add. That's why **I suggested to bring back `sync`, before printing the metadata**. That won't trigger execution, it's backwards compatible, and keeps the new feature of printing the metadata.

The other remaining question is what to do with user modules. Limit to state or not?

**Comment by shykes** [comment]
> The OP mentions that we don't want to run the container _entrypoint_:
> 
> > Actual behavior: execute the entrypoint (in this case a long-running server), and hang forever
> 
> ...but my understanding is `Sync` already won't do that (it _builds_ the container, it doesn't _run_ it), so maybe there's some confusion there.
> 
> Or maybe it's using 'entrypoint' in a generic sense, imagining the post-`ENTRYPOINT` world we want to be in?

To be specific, it's the container's `entrypoint` + `defaultArgs` that were executed. In my particular case, the `entrypoint` was empty, so it was all the `defaultArgs`. Note that this makes my example #7136 - compliant :)

Here is the code of the function I called ([from the dagger repo](https://github.com/dagger/dagger/blob/main/dev/docs.go#L40-L51))

```golang
// Build the docs server
func (d Docs) Server() *Container {
	nginxConfig := dag.CurrentModule().Source().File("docs-nginx.conf")
	return dag.
		Container().
		From("nginx").
		WithoutEntrypoint().
		WithFile("/etc/nginx/conf.d/default.conf", nginxConfig).
		WithDefaultArgs([]string{"nginx", "-g", "daemon off;"}).
		WithDirectory("/var/www", d.Site()).
		WithExposedPort(8000)
}
```

> But either way, I don't think we'd want to use `Container` to represent indefinitely-running services, since you'd get the same hang if you were to try to build + publish the image.

Here's how you can use the `docs server` function:

- Serve the docs locally: `dagger call docs server as-service up`. I'm lobbying to get it shortened to `dagger call docs server up`, see #7399. By the way I would still love to get this..

- Open a terminal in the server for debugging: `dagger call docs server terminal`

- Publishing the server container works as well, no hang: `dagger call docs server publish --address=ttl.sh/dagger-docs-server-example`

> If there _is_ a longer term vision in mind I'd only suggest we quickly bikeshed alternative(s) for folks like me that currently rely on the `Sync` behavior.

Just to take a step back. Perhaps I was over-prescriptive in my proposed solution. Perhaps my problem is more narrowly scoped than I thought. The parameters of my problem:

- `dagger call` receives a `Container` as return value
- The `Container` has no `withExec`. It has a `defaultArgs` for a long-running service
- `dagger call` executes that long-running service, which is not what I wanted or expected

So I think my issue is *not* with evaluating a container's `withExec`s on `dagger call`. Instead it's with special cases like "if there is no `withExec`, execute the `defaultArgs`", because those special cases cause my container's long-running service to be executed when I don't want it to.

So, good news, I think this is compatible with the "unit tests that return a container" pattern described by @vito .

**Comment by helderco** [comment]
> So I think my issue is _not_ with evaluating a container's `withExec`s on `dagger call`. Instead it's with special cases like "if there is no `withExec`, execute the `defaultArgs`", because those special cases cause my container's long-running service to be executed when I don't want it to.

Yeah, to be clear it's not the CLI doing that, it's the behavior in core from:
- `stdout` and `stderr` via [`MetaFileContents`](https://github.com/dagger/dagger/blob/037a9c4fc647a2dcc87efb1f51f84e542dfc1690/core/container_exec.go#L316-L317)
- [`asService`](https://github.com/dagger/dagger/blob/037a9c4fc647a2dcc87efb1f51f84e542dfc1690/core/container.go#L1492-L1494) (not taken into consideration for this CLI feature because it doesn't return a scalar)

> So, good news, I think this is compatible with the "unit tests that return a container" pattern described by @vito .

But @vito still had good reason to want to remove `stdout` and `stderr` anyway:
- https://github.com/dagger/dagger/pull/7829

The solution to that, in response to https://github.com/dagger/dagger/issues/7821#issuecomment-2209667434  is to `sync` + print metadata without `stdout` and `stderr`.

**Comment by shykes** [comment]
> calling sync (v0.11.x, proposed fix here): good! Executes whatever's necessary to build the container, without running the entrypoint/defaultArgs.

Makes sense to me 👍 

> calling stdout and stderr (main): bad! Runs the entrypoint/defaultArgs.

*Is it* bad that `dagger call` auto-calls `stdout` and `stderr`? Or is it bad that `stdout` and `stderr` fall back to entrypoint/defaultArgs when there is no `withExec`? I now think it's the latter, actually. If `stdout` and `stderr` aligned their behavior with `sync`, I think it would be fine to keep the auto-print behavior as-is, and we don't need to worry about special cases for `stdout` and `stderr`.

**Comment by vito** [comment]
> _Is it_ bad that `dagger call` auto-calls `stdout` and `stderr`?

I think it's bad for other reasons: when this happened for my tests it filled my screen with unreadable garbage (a huge escaped string containing the full test stdout). That was my original cue to open #7829 (which includes a [demo](https://asciinema.org/a/PU8bCnemL5aVmkuLnHmFRpmlb) of the surprising UX).

I'm OK with `dagger call` printing container metadata, even though it's useless for me since I don't care about the container itself - but I definitely wouldn't be OK with it including `stdout`/`stderr`.

> Or is it bad that `stdout` and `stderr`, when they're called, fall back to entrypoint/defaultArgs when there is no `withExec`? I now think it's the latter, actually. If `stdout` and `stderr` aligned their behavior with `sync`, I think it would be fine to keep the auto-print behavior as-is, and we don't need to worry about special cases for `stdout` and `stderr`.

Yeah I can see the argument here, especially since it's probably extremely common for entrypoint/defaultArgs to refer to a long-running thing that you'd never actually want `stdout`/`stderr` from. I think the alternative is to just return an error if no exec has been run. Might make sense to do at the same time as https://github.com/dagger/dagger/pull/7136

**Comment by shykes** [comment]
When you write a test function to cover all combinations of `withExec`/`entrypoint`/`defaultArgs`, and step on an unrelated landmine... Can you spot the error?

```golang
func (m Scratch) TestContainer(exec, entrypoint, defaultArgs bool) *Container {
	ctr := dag.
		Container().
		From("alpine:latest").
		WithoutEntrypoint().
		WithoutDefaultArgs()
	if exec {
		ctr = ctr.WithExec([]string{"/bin/echo", "EXEC.."})
	}
	if entrypoint {
		ctr = ctr.WithEntrypoint([]string{"ENTRYPOINT.."})
	}
	if defaultArgs {
		ctr = ctr.WithDefaultArgs([]string{"DEFAULT", "ARGS"})
	}
	return ctr
}
```

**Comment by shykes** [comment]
> @shykes Does this fix it?
> 
> ```
> dagger call test-container --exec=false --entrypoint=false --default-args=false
> ```

Yes it does! 🤦‍♂️ And it makes sense that it does. When seeing the error, my brain rushed to the "optional boolean argument" issue from a few weeks back. Sorry for the false alarm.

**Comment by helderco** [comment]
> If we call `Sync`, to me that is still "execution" in the sense that we're running containers, just not the _entrypoint_, so I wondered this issue was requesting to do _no execution at all_ so that the you can (e.g.) merely introspect container fields without running anything.
> 
> It was either that or it really just meant 'don't run the entrypoint' - but that part confused me, because the current behavior (_before_ the change on `main` to select all fields) should have already done that, so I thought there might be something more to this issue. Now I see it clearly says "Since #6515." 🤦‍♂️

Yeah, that's right, sorry about that! I got fixated on "trigger container execution" to mean "make sure it's executed, even if no withExec", that I didn't see the confusion that `sync` executes the `withExec`s in a `Container`.

> To continue from here, I can just pop a quick `Sync` call in #7829

👍 It's not just adding a `sync` to selections though, you need to make the request and load the container from id before continuing.

**Comment by vito** [comment]
> 👍 It's not just adding a `sync` to selections though, you need to make the request and load the container from id before continuing.

Makes sense - I guess we want to avoid dumping the ID, which would happen if I just tossed it into the list.

If you have an idea in mind already for how to do this feel free to push on top of my PR! :pray: Since mine probably does more harm than good without it.

**Comment by shykes** [comment]
> > > I understand how using field/not-field as a print heuristic is appealing, because a scalar field is always safe to print. But some scalar getter functions are safe to print too, and I worry that if I refactor a field into a getter function (which I do often) I will be "penalized" by my getter function disappearing from the CLI output.
> > 
> > 
> > That's a good point. In Python we **could** use a [property](https://docs.python.org/3/library/functions.html#property) for that:
> > ```python
> > @object_type
> > class Test:
> >     @function
> >     @property  # allows calling this as an attribute (aka field): `self.simple_scalar`
> >     def simple_scalar(self) -> str:
> >         return "not too bad computation"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in TypeScript you have [getters](https://www.typescriptlang.org/docs/handbook/2/classes.html#getters--setters):
> > ```ts
> > @object()
> > class Test {
> >   @func
> >   get simpleScalar() string {  // notice the `get` before the function name
> >     return "not too bad computation"
> >   }
> > }
> > ```
> 
> I'd be all for that sort of approach, provided the default is to not select Functions unless they have that explicit annotation as a getter. Fields are essentially our "getters" today in my mind, but it makes sense to be less rigid there, especially in languages that already have these notions like you listed.

Do we really need another annotation? We're already planning to make functions cacheable by default, with a special annotation for them to *not* be cached. That no-cache annotation already covers all the functions you may want to exclude from an auto-print: deploy, publish, everything with a side effect basically.

Restricting to fields only, without any dynamic functions allowed, is super restrictive and immediately limits how I can structure my modules. Here is an example of a module that would not work with that restriction: https://github.com/dagger/dagger/pull/7803/files#diff-ede2977d7a59efd13edd531b5bc04e014d632dcaa127606df3284d1b678c5cb6

**Comment by helderco** [comment]
> Do we really need another annotation? We're already planning to make functions cacheable by default, with a special annotation for them to _not_ be cached. That no-cache annotation already covers all the functions you may want to exclude from an auto-print: deploy, publish, everything with a side effect basically.

To be fair, it's not another Dagger annotation. It's applying the same `@dagger.function` to another native feature of the language.

But I agree that the cache control can solve your issue and address Erik's concerns. However, until we have that cache control, users won't be able to "opt-out" of certain functions being printed undesirably.

What's better?
- Unrestricted functions now, possibly frustrating some users, promising to give cache control soon?
- Restricted to state now and expand later with cache control?

> Restricting to fields only, without any dynamic functions allowed, is super restrictive and immediately limits how I can structure my modules. Here is an example of a module that would not work with that restriction: https://github.com/dagger/dagger/pull/7803/files#diff-ede2977d7a59efd13edd531b5bc04e014d632dcaa127606df3284d1b678c5cb6

That's interesting. I can think of a way to restructure so that you end up with the things you want to print as primitives in an object, but it feels very restraining to around around this limitation.

I'm actually ok trying out unrestricted functions and escalating function cache. I can see how it can be an issue for some but I don't know enough about users' use cases. What if we make a poll on #General in Discord?

**Comment by shykes** [comment]
> > Do we really need another annotation?
> To be fair, it's not another Dagger annotation. It's applying the same `@dagger.function` to another [native feature](https://docs.python.org/3/library/functions.html#property) of the language.

In Go, there is no annotation for Dagger Functions: an object's method is automatically registered as a dagger function.

And in Typescript I'm not sure how it would go.

Overall it just feels like a lot of concepts to explain, when we already have quite a lot.

> But I agree that the cache control can solve your issue and address Erik's concerns. However, until we have that cache control, users won't be able to "opt-out" of certain functions being printed undesirably.

Yes that's true.

> What's better?
> 
> - Unrestricted functions now, possibly frustrating some users, promising to give cache control soon?
> 
> - Restricted to state now and expand later with cache control?

I think unrestricting functions is better. The frustration is only hypothetical: today we don't print anything when your pipeline returns an object. So nobody relies on this new behavior yet. Worst case, some users can't adopt the new behavior for some of their types. They have the choice between waiting for cache control, or tweaking their API. Either way there is no breaking change.

> > Restricting to fields only, without any dynamic functions allowed, is super restrictive and immediately limits how I can structure my modules. Here is an example of a module that would not work with that restriction: https://github.com/dagger/dagger/pull/7803/files#diff-ede2977d7a59efd13edd531b5bc04e014d632dcaa127606df3284d1b678c5cb6
> 
> 
> 
> That's interesting. I can think of a way to restructure so that you end up with the things you want to print as primitives in an object, but it feels very restraining to around around this limitation.

Yeah it's definitely possible, just unreasonably restrictive.

> I'm actually ok trying out unrestricted functions and escalating function cache. I can see how it can be an issue for some but I don't know enough about users' use cases. What if we make a poll on #General in Discord?

I don't think we need a poll for this, seems like overkill.

By the way, we could introduce the `nocache` annotation before actually implementing function caching. So from a caching perspective it would be a noop initially, but it could be used as a stopgap to mean "no print".

**Comment by helderco** [comment]
@shykes, the default args exec on stdout was added because of:
- https://github.com/dagger/dagger/issues/4833

Can you confirm is the reason for adding it in the first place no longer applies?

**Comment by shykes** [comment]
> @shykes, the default args exec on stdout was added because of:
> 
> * ["Default exec" #4833](https://github.com/dagger/dagger/issues/4833)

😭

**Comment by helderco** [comment]
> I updated the issue description to be up-to-date with the last discussions.

Need another update? We left the discussion on the other solution, right? Manually excluding `stdout` and `stdout` for now rather than change the behavior in the API with the implicit exec?

**Comment by shykes** [comment]
> Need another update? We left the discussion on the other solution, right? Manually excluding `stdout` and `stdout` for now rather than change the behavior in the API with the implicit exec?

I was wondering if I should create a separate issue - but you're right, I'll leave everything here for simplicity.

My preference would be to do both:

1. Remove `stdout` and `stderr` from autoprint
2. Also remove the reliance on implicit exec. Even know we found a way to not step on the landmine this time, we should still remove it now that we know it's there. No?

**Comment by helderco** [comment]
Yeah, I agree. On both counts.

**Comment by sipsma** [comment]
> That no-cache annotation already covers all the functions you may want to exclude from an auto-print: deploy, publish, everything with a side effect basically.

I don't think this is going to be the case in general. We also want to add cache TTLs which, once added, would likely be used for side-effectful functions. We could make the rule that we only autoselect functions that are cached with no TTL, but at that point the connection seems extremely unobvious and like we are conflating two unrelated concepts.

Separately, there's pretty easy to imagine scenarios that A) have nothing to do with caching and B) are cases where you *wouldn't* want functions to be autoselected, e.g.

```go
type TestSuites struct {
  FooSetting bool
  BarSetting string
}

// Run all of the tests using settings in TestSuites
func (t TestSuites) AllTests() (string, error) {
   // ...
}

// Run some subset of the tests using settings in TestSuites
func (t TestSuites) SomeSubsetOfTests() (string, error) {
   // ...
}
```

In that case, caching is not a consideration (I'd be happy with default caching once that's enabled), but I would not want to run both `AllTests` and `SomeSubsetOfTests` automatically (there would be overlapping test execution, which would get worse as more methods are added). I'd be perfectly happy however if autoselection on `TestSuites` just printed the settings for the test suites and tests only actually ran if I explicitly selected the function.
* And I'd be even happier if I'm a more advanced user who wanted fine grain control and had an annotation I could put on one of the Functions that resulted in it getting autoselected and thus executed.

I like the separate annotation for enabling a function to be autoselected because:
1. In the "simple"/"default" case where users aren't thinking about any of this, the behavior is safe (only print values on the object that are already calculated anyways, i.e. fields)
2. In more advanced cases, where the user wants fine grain control, you have to add an annotation (just a single line of code on a Function

The general principle being "default case is safe+obvious + easy knobs for more advanced cases"

> I think unrestricting functions is better. The frustration is only hypothetical: today we don't print anything when your pipeline returns an object. So nobody relies on this new behavior yet. Worst case, some users can't adopt the new behavior for some of their types. They have the choice between waiting for cache control, or tweaking their API. Either way there is no breaking change.

Let me double check I'm fully following everything. If we did a release today, there would functions that previously did not run unless explicitly selected and now will run automatically in some cases (when they have the right signature and end up getting autoselected). That would be a breaking change right?

I realize that the number of users practically impacted by this is likely to be small, but it's plausibly non-zero and since it involves avoiding surprising/potentially-unsafe behavior it feels worth it to me to go out of our way to avoid it (even if that means adding more annotations or other potential solutions).

**Comment by helderco** [comment]
@sipsma, do you mind creating a new issue re: limiting the functions selection to state?
