### ISSUE TITLE
🐞 Docker build secrets seems broken in Python + Example in documentation is wrong for build secrets in Python

### ISSUE THREAD

**Issue by lepouletsuisse** [dagger/dagger#8035]
### What is the issue?

Injecting a secret in the `Directory.docker_build()` function seems either broken or extremely confusing.
First, the example provided in the Cookbook (See https://docs.dagger.io/cookbook#use-secret-in-dockerfile-build in Python tab) is wrong, no `dagger.DockerBuildArgs` exists, only `dagger.BuildArgs` exists, which I suppose is the one required here as it correctly injects the build args in the Dockerfile. 
Also, the example seems wrong, the `id=gh-secret` in the Dockerfile cannot exist as the id should be the name of the Dagger secrets, which should be the SHA256 of the secret (If I refer to [this comment](https://github.com/dagger/dagger/issues/5242#issuecomment-2051557730)).

Second, even while following the instruction from [this contributor](https://github.com/dagger/dagger/issues/5242#issuecomment-2051557730), I can't make these build secrets work, no matter what. 
Maybe I didn't understand at all how injecting the Docker secrets work but I can't figure out how to do it in Python. I would like to inject it as a Secret to avoid exposing it in Dagger Cloud as we plan to use it when our PoC of Dagger is done.
I tried multiple ways but nothing seems to work, just like the `secrets=[...]` part of the `Directory.docker_build()` function doesn't get correctly translated to `docker build --secret id=<secret_name>,src=<location of the secret for Dagger> ...` and doesn't include the secret at all during the build process.

### Dagger version

dagger v0.12.0 (registry.dagger.io/engine) linux/amd64

### Steps to reproduce

**Dagger main.py code**
```
# I have a Secret injected from the cmd set in self.gh_secret. I checked that the value is correctly set in the secret using 
# the plaintext function
secret_name = await self.gh_secret.name()
test_container = self.source.docker_build(
    dockerfile="Dockerfile",
    build_args=[BuildArg(name="SECRET_ID", value=secret_name)],
    secrets=[self.gh_secret]
)
```

**Dockerfile**
```
...
ARG SECRET_ID
RUN --mount=type=secret,id=$SECRET_ID,target=/run/secrets/secret.txt cat /run/secrets/secret.txt
...
```

### Log output

```
295 : 5e6e16f8957437ef:     [requirements_installer  7/10] RUN --mount=type=secret,id=1e1b5c3ed2d9588e8d152288a5e506352c852efdd840041772783a9e1f466d68,target=/run/secrets/secret.txt cat /run/secrets/secret.txt
295 : 5e6e16f8957437ef:     [0.1s] | cat: /run/secrets/secret.txt: No such file or directory
277 : d6f0549640d02d31: MyApp.backendUnitTests: String!
277 : d6f0549640d02d31: [7.2s] | ╭─ Error ──────────────────────────────────────────────────────────────────────╮
277 : d6f0549640d02d31: [7.2s] | │ Function execution error: resolve: process "/bin/sh -c cat                   │
277 : d6f0549640d02d31: [7.2s] | │ /run/secrets/secret.txt" did not complete successfully: exit code: 1         │
277 : d6f0549640d02d31: [7.2s] | ╰──────────────────────────────────────────────────────────────────────────────╯
283 : 3a0952b39d08fe69:   Directory.dockerBuild(buildArgs: [{name: "SECRET_ID", value: "1e1b5c3ed2d9588e8d152288a5e506352c852efdd840041772783a9e1f466d68"}], dockerfile: "Dockerfile", secrets: [xxh3:402db5f0cb15dcf6]): Container!
295 : 5e6e16f8957437ef:     [requirements_installer  7/10] RUN --mount=type=secret,id=1e1b5c3ed2d9588e8d152288a5e506352c852efdd840041772783a9e1f466d68,target=/run/secrets/secret.txt cat /run/secrets/secret.txt ERROR [0.2s]
295 : 5e6e16f8957437ef:     ! process "/bin/sh -c cat /run/secrets/secret.txt" did not complete successfully: exit code: 1
292 : 2c472795bce0bfaa:   Container.sync ERROR [1.0s]
```

We see that in the debug options of the `Directory.dockerBuild` that the build_arg and the secret are correctly set, but as there is no way to see the `docker` command that is run by Dagger to build the container, I can't check if the secret is correctly added in the command.

**Comment by helderco** [comment]
See:
- https://github.com/dagger/dagger/issues/5242#issuecomment-2051557730

**Comment by helderco** [comment]
Sorry, I see you reference this issue so you know about it. The docs will be fixed, thanks.

I'll take a closer look at why you can't make it work later.

**Comment by sipsma** [comment]
Looked into this a bit:
1. The bug has existed for a while, but it used to result in the secret being missing during dockerfile evaluation but after v0.12.1 there was some more validation added so it errors a little bit earlier ([here](https://github.com/sipsma/dagger/blob/d9a15262229f1dba0aa53dbd0216908438331995/core/container.go#L358-L358)). Same end effect either way
2. The load of the dockerfile that errors is hit when the module return value is being loaded by the caller, specifically it fails when loading a core ID here: https://github.com/sipsma/dagger/blob/d9a15262229f1dba0aa53dbd0216908438331995/core/schema/coremod.go#L312-L312
3. My guess at the underlying problem atm is
   * pre-v0.12.1: the dockerfile definition gets re-evaluated during the load above (due to secret being impure, thus skipping dagql caching) but ends up using accessor from the wrong client here: https://github.com/dagger/dagger/blob/133917c6f9ce36d8cfdc595d9b7bd2c14cbc2c20/core/container.go#L407
   * post-v0.12.1: the load of the dockerfile happens before the returned secrets get set in the caller (load [here](https://github.com/dagger/dagger/blob/c544987c852dbacc285d46c5688cf4ff6d5360fd/core/modfunc.go#L295), secrets set [here](https://github.com/dagger/dagger/blob/c544987c852dbacc285d46c5688cf4ff6d5360fd/core/modfunc.go#L308)), so when the load happens the secret isn't found.

Overall, it seems highly specific to this Dockerfile created in a Module w/ secrets case.

I'm still thinking about the best way to fix; hit timebox on it for today.

**Comment by sipsma** [comment]
*Think* I figured out the fix, but it's very subtle so want to add some more integ test coverage before merging: https://github.com/dagger/dagger/pull/8049

**Comment by helderco** [comment]
So, here's both fixes:
- https://github.com/dagger/dagger/pull/8049
- https://github.com/dagger/dagger/pull/8058
