### ISSUE TITLE
Don't wipe older container engine

### ISSUE THREAD

**Issue by shykes** [dagger/dagger#8195]
## Problem

When upgrading Dagger, a new container engine is created (so far so good). Then the older container engine is immediately wiped. This can be very frustrating when one is, for example, switching back and forth between Dagger versions to reproduce an issue. In addition of the overhead of removing and re-creating a container a container each time, it also wipes the cache each time.

See also https://github.com/dagger/dagger/issues/8364

## Solution

Continue wiping old engines by default, but allow leaving them untouched with an env var: `DAGGER_LEAVE_OLD_ENGINE=1`.

If that env var is set, don't remove the old engine with `docker rm`. Simply leave it there.

**Comment by jedevc** [comment]
I think this is doable, but this is dependent on something like https://github.com/moby/buildkit/pull/5079 (planning on picking this up again soon), or we're just going to exacerbate https://github.com/dagger/dagger/issues/7711.

Having two different dagger engines both attempting to consume 70% of the disk (the current policy) will end with even more users hitting out-of-disk issues than are currently. If we turn off the old engine GC behind a flag, then we could enable this very easily, since users are opting into this - but if we make this the default, we probably need to fix https://github.com/moby/buildkit/pull/5079 first.

**Comment by shykes** [comment]
This continues to be very painful...

I understand the concern about doing this *by default*. I would perfectly happy with an opt-in env variable:

`DAGGER_LEAVE_OLD_ENGINE=1 dagger ...`
