### ISSUE TITLE
🐞 Engine cannot start: `sh: error setting limit: Operation not permitted`

### ISSUE THREAD

**Issue by yann-soubeyrand** [dagger/dagger#8210]
### What is the issue?

Since v0.12.5, the engine fails to start with this error in the logs:
```
#!/bin/sh
set -e

cat $0

# cgroup v2: enable nesting
# see https://github.com/moby/moby/blob/38805f20f9bcc5e87869d6c79d432b166e1c88b4/hack/dind#L28
if [ -f /sys/fs/cgroup/cgroup.controllers ]; then
	# move the processes from the root group to the /init group,
	# otherwise writing subtree_control fails with EBUSY.
	# An error during moving non-existent process (i.e., "cat") is ignored.
	mkdir -p /sys/fs/cgroup/init
	xargs -rn1 < /sys/fs/cgroup/cgroup.procs > /sys/fs/cgroup/init/cgroup.procs || :
	# enable controllers
	sed -e 's/ / +/g' -e 's/^/+/' < /sys/fs/cgroup/cgroup.controllers \
		> /sys/fs/cgroup/cgroup.subtree_control
fi

# expect more open files due to per-client SQLite databases
# many systems default to 1024 which is far too low
ulimit -n 1048576

exec /usr/local/bin/dagger-engine --config /etc/dagger/engine.toml "$@"
sh: error setting limit: Operation not permitted
```

I’m using Podman and I guess the issue only happens with Podman.

### Dagger version

dagger v0.12.5 (registry.dagger.io/engine:v0.12.5) linux/amd64

### Steps to reproduce

```
mkdir test
cd test
dagger init
```

**Comment by jeremywitte** [comment]
I'm also experiencing this with dagger v0.12.5 and podman v5.2.0.

**Comment by scottames** [comment]
Same here. 

```bash
❯ podman version
Client:       Podman Engine
Version:      5.2.1
API Version:  5.2.1
Go Version:   go1.22.5
Built:        Tue Aug 13 17:00:00 2024
OS/Arch:      linux/amd64
❯ dagger version
dagger v0.12.5 (registry.dagger.io/engine:v0.12.5) linux/amd64
```

**Comment by samalba** [comment]
Looks like it's coming from the ulimit from the engine entrypoint. We should allow it to fail (`ulimit -n 1048576 || true`).

Pinging @vito since this was introduced as part of [https://github.com/dagger/dagger/pull/7996](https://github.com/dagger/dagger/pull/7996)

**Comment by yann-soubeyrand** [comment]
As a workaround I put the following content in `~/.config/containers/systemd/dagger-engine@.container`:
```
[Container]

ContainerName=dagger-engine
Image=registry.dagger.io/engine:%i
Entrypoint=["/usr/local/bin/dagger-engine", "--config", "/etc/dagger/engine.toml"]
Volume=/var/lib/dagger
SeccompProfile=unconfined
SecurityLabelDisable=true
Unmask=ALL
AddCapability=ALL

[Service]

Restart=always
```

Then I execute:
```
systemctl --user daemon-reload
systemctl --user start dagger-engine@v0.12.5
```

I finally set this environment variable:
```
export _EXPERIMENTAL_DAGGER_RUNNER_HOST=podman-container://dagger-engine
```

It seems to work.

**Comment by jedevc** [comment]
Hm, I can't repro this - curious what distro users who are hitting this are using?

Can someone with this issue share the results of (I guess within the context of a generic `alpine` podman container):

- `ulimit -n`
- `cat /proc/sys/fs/nr_open`

I'm trying to understand if the limit of `1048576` is just too high, or whether it just can't be set at all.

---

> Looks like it's coming from the ulimit from the engine entrypoint. We should allow it to fail (`ulimit -n 1048576 || true`).

This should be a last resort - we upped this limit since the default of 1024 is too low, so if we just continue on without this, we later might hit the possibility that we just can't open critical files, which would cause *even* more difficult to debug issues.

**Comment by yann-soubeyrand** [comment]
Hi @jedevc,

I’m using Fedora 40. Here are the info you asked for:

```
❯ podman run --rm -it docker.io/alpine sh -c "ulimit -n"
524288

❯ podman run --rm -it docker.io/alpine cat /proc/sys/fs/nr_open 
1073741816
```

**Comment by scottames** [comment]
Same here, Fedora 40 (Silverblue, shouldn't matter here)

```
❯ podman run --rm -it docker.io/alpine sh -c "ulimit -n"
524288
❯ podman run --rm -it docker.io/alpine cat /proc/sys/fs/nr_open
1073741816
```

**Comment by samalba** [comment]
I was able to repro with podman on Mac (linux vm started with `podman machine start`). By default, podman runs in rootless, which makes the ulimit fail (`sh: error setting limit: Operation not permitted`), I got the same error from the engine logs.

Configuring the podman vm with privileged container engine: `podman machine set --rootful` - it works.

Pretty much the equivalent of the systemd config from @yann-soubeyrand above.

I don't think there is a bug, just related to rootless runtime that can't work with Dagger as of now.

**Comment by vito** [comment]
Yeah I don't think we should just `|| true` this; it was added because we anticipate holding open more files than usual. and without it you're likely to hit cryptic errors at high concurrency.

Maybe we could have it run conditionally, only if the detected `ulimit` is at or below a low enough threshold? Then you can increase it externally, and the entrypoint will just do a no-op.

Is everyone facing this running the engine in a rootless container? If so, [that's not supported at the moment](https://docs.dagger.io/faq/#can-i-run-the-dagger-engine-as-a-rootless-container) and I'm frankly surprised if it ever worked considering all the things the engine does.

**Comment by yann-soubeyrand** [comment]
I don’t know if rootless is the right term, but I’m running the engine using a privileged container run as my user. This means that my container is running as root, but this root is mapped to my user on the host:

```
mkdir tmp
podman run --rm -it --privileged -v $(pwd)/tmp:/mnt --entrypoint '["sh", "-c"]' registry.dagger.io/engine:v0.12.5 "ls -la /mnt"
ls -la tmp
rmdir tmp
```

**Comment by mailhost** [comment]
Also facing this issue, and also running podman rootless (with `--privileged`). Running podman rootful on the same host does not encounter the issue. Current workaround is overriding the entrypoint.

I would certainly appreciate the conditional check, as it would also avoid potentially _reducing_ `nr_open` for the ambitious folks that have it set to more than what dagger is aiming to set it.

**Comment by zephyros-dev** [comment]
The issue here is that the ulimit function is not available for rootless podman user https://github.com/containers/podman/discussions/22011, which means that running podman as a root user does work.
Given that previous version of dagger works with the setup, I think that there should be some official documentations on the rootless podman setup. The ulimit can be increased by the host user themselves, so simply allowing the ulimit command to fail should suffice for the rootless podman use-case.
> Is everyone facing this running the engine in a rootless container? If so, [that's not supported at the moment](https://docs.dagger.io/faq/#can-i-run-the-dagger-engine-as-a-rootless-container) and I'm frankly surprised if it ever worked considering all the things the engine does.
Rootless podman means that the podman process is ran as a non-root user. They can still be run with `--privileged`, it just that the capabilities of the process will not exceed the capabilities that are granted to the non-root user.

**Comment by vito** [comment]
Thanks for the details. My bandwidth is pretty low at the moment but I'd happily review a PR if anyone has time to put one together. 🙏

**Comment by samalba** [comment]
I just submitted this PR: https://github.com/dagger/dagger/pull/8356 - PTAL

It's a PITA to test given the latest engine is required to build the dev engine, and both rootful/rootless VM do not share any data. Once the PR is merged, you'll have to wait for the next engine release, unless you want to do the container export/import described in the PR...
