### ISSUE TITLE
🐞  core(SSH_AUTH_SOCK): encoding issue on socket path

### ISSUE THREAD

**Issue by sheldonhull** [dagger/dagger#8401]
### What is the issue?

The path for agent.socket is being evaluated as a URL, escaping spaces for example on darwin, which gave values like `%20` for space etc.

### Dagger version

v0.12.7

**Comment by sheldonhull** [comment]
cc @grouville

**Comment by grouville** [comment]
Adding some context: 
The way the engine requests the socketPath to load to the client is being serialized by `url.Parse`, which encodes the spaces into `%20`: https://github.com/dagger/dagger/blob/main/core/socket.go#L174-L189.

As part of https://github.com/dagger/dagger/pull/8365, it seems the relying on `url.PathEscape()` is mandatory to handle properly such cases. It seems that this issue has been here since implementation of `core.Socket` type. Quite surprised that this has not been found out earlier :pray:

**Comment by grouville** [comment]
@sheldonhull could you please test the new version v0.13.1, and see if you still have the issue, without using the symlink workaround ?

**Comment by sheldonhull** [comment]
Ok, I upgraded and ran again and don't have to set the SSH_AUTH_SOCK override any further.
If I run into the encoding issue or related I'll be sure to let you know with an update. Thanks for the follow-up and your time!
