### ISSUE TITLE
🐞 Create Platform-specific image from a scratch image

### ISSUE THREAD

**Issue by Vad1mo** [dagger/dagger#8908]
### What is the issue?

I am trying to copy a platform-specific binary into a scratch image. Scratch images are platform-agnostic, so I should be able to do something like the following:

```golang

func (m *Harbor) BuildImage(ctx context.Context, platform string, pkg string) *dagger.Container {
	bc := m.buildBinary(ctx, platform, pkg)
	img := dag.Container(dagger.ContainerOpts{Platform: dagger.Platform(platform)}).
		From("scratch").
		WithFile("/bin/", bc.Container.File(bc.BinaryPath))

	return img
}

```

The above code isn't working and I don't see any possible workaround. 

### Dagger version

0.13.6 and 0.14.0

### Steps to reproduce

try to create a plafrom specific image that is based on scratch. 

### Log output

```console
  ✘ Container.from(address: "scratch"): Container! 0.5s
  ! failed to resolve image docker.io/library/scratch:latest: failed to resolve source metadata for docker.io/library/scratch:latest: docker.io/library/scratch:latest: not found
    ✘ resolving docker.io/library/scratch:latest 0.5s
    ! docker.io/library/scratch:latest: not found
      ✘ remotes.docker.resolver.HTTPRequest 0.2s
        ✘ HTTP HEAD 0.2s
      ✔ HTTP GET 0.2s
      ✘ remotes.docker.resolver.HTTPRequest 0.1s
        ✘ HTTP HEAD 0.1s
```

**Comment by jedevc** [comment]
You should just be able to leave out the `From` function call - if you don't have one of those, it will just have a completely empty image, i.e. `scratch` :tada:

So your snippet would just become:

```golang

func (m *Harbor) BuildImage(ctx context.Context, platform string, pkg string) *dagger.Container {
	bc := m.buildBinary(ctx, platform, pkg)
	img := dag.Container(dagger.ContainerOpts{Platform: dagger.Platform(platform)}).
		WithFile("/bin/", bc.Container.File(bc.BinaryPath))

	return img
}

```

---

The reason you're actually getting an error is because the `scratch` image doesn't *really* exist - https://hub.docker.com/_/scratch (there are no tags for it). In `Dockerfile`s it's actually handled as a special case to mean the empty image - in dagger, the corresponding way to do it is just to leave off the `From`.

**Comment by Vad1mo** [comment]
Thanks, for the explanation. It makes sense from that point now. It also works as suggested as outlined.
