### ISSUE TITLE
Test suite: `dagger call check --targets=sdk/go` fails to run in CI from an upstream branch

### ISSUE THREAD

**Issue by gerhard** [dagger/dagger#9023]
<img width="1068" alt="image" src="https://github.com/user-attachments/assets/733976e8-331f-46b2-9e96-89b6e40d9bbb">

Dagger Cloud trace: https://dagger.cloud/dagger/traces/32a617781fc7ceb70228f10669351cc4

This is not a flake, it happens consistently:
1. https://github.com/dagger/dagger/actions/runs/11955188869/job/33326999788#step:3:17208
2. https://github.com/dagger/dagger/actions/runs/11955734409/job/33328800503#step:3:17539

It was working fine 3 hours ago: https://github.com/dagger/dagger/actions/runs/11953083867/job/33320214719

These are the only changes since the last time this passed:
1. https://github.com/dagger/dagger/commit/e6d47bd549f8a5b6d8c4ba332fdb1a42f72fc945 @helderco 
2. https://github.com/dagger/dagger/commit/c3ed7490b475dfbdb16c71e9ddae7697a5b7313b @helderco 
3. https://github.com/dagger/dagger/commit/ab4ae221c5dd80a16d342b757522c849042206ab @rajatjindal 

This is all the time that I have to investigate this particular issue, but still worth taking the first step towards this new habit:
- https://github.com/dagger/dagger/pull/8998#issuecomment-2491426455

---

cc @jedevc @sipsma in case you know what the issue is by skimming it.

**Comment by jedevc** [comment]
Looks like we have this: https://dagger.cloud/dagger/traces/32a617781fc7ceb70228f10669351cc4?span=4a4eb949733c92c8#1b65c00adbc4fbe9

```
$ git checkout ci-alt-runners-common-terminology --
fatal: invalid reference: ci-alt-runners-common-terminology
```

**Comment by jedevc** [comment]
Right, this is actually caused by an intentional regression in #8442 - this is likely because something is running a dev version of dagger off of main.

Discussing in discord here with @vito https://discord.com/channels/707636530424053791/1003718839739105300/1309198728455917620, to see if we can avoid a breakage, or at least minimize it.

**Comment by jedevc** [comment]
Putting it into the milestone so that we at least don't forget about this! There's a few possible ways forward that don't break backwards-compat, but we would at least need to keep `Stdout`/`Stderr` on `ExecError` if we want to do that, and *maybe* try and keep the format of `Error` (but bleh, that's annoying that we depend on that).
